### ISSUE TITLE
节点名称没有渲染

### ISSUE THREAD

**Issue by frPhoenix** [seeksdream/relation-graph#1]
![image](https://user-images.githubusercontent.com/31149009/97264646-4e07e780-1860-11eb-873f-8b9963389b46.png)

如图，节点名称没有。
代码就是官网上的“快速上手”那里的示例代码：
![image](https://user-images.githubusercontent.com/31149009/97264704-6972f280-1860-11eb-9038-73d989de3972.png)

是我哪里配置错了吗？

**Comment by TQJG** [comment]
相同的问题

**Comment by seeksdream** [comment]
在使用vue2.5及更低版本时会出现这个问题，下个版本会解决。通过slot插槽方式自定义node可以解决此问题（有个参考示例：http://relation-graph.com/#/demo/adv-slot），具体方法和代码可以联系我，qq:3235808353
