### ISSUE TITLE
关系线怎么才可以接收到hover事件，显示信息

### ISSUE THREAD

**Issue by acyxc** [seeksdream/relation-graph#10]
我想实现一个鼠标hover在关系线上弹出个提示信息框的功能，这个怎么才能实现？

**Comment by forwardZhang** [comment]
请问这个问题解决了吗？

**Comment by seeksdream** [comment]
目前关系线没有hover事件，目前来看这个需求没有普遍性
如果你一定需要的话，建议把relation-graph的源代码作为你的项目组件放到你的项目中，然后自己加一下

如果后续还有其他人提出这个需求，我会加上这个事件
