### ISSUE TITLE
移动端使用碰见的问题

### ISSUE THREAD

**Issue by yuguaa** [seeksdream/relation-graph#104]
移动端使用的情况下，出现了ios12以前白屏，鸿蒙系统也会出问题，应该是某个api不支持，没有排查出来，作者是否可以给些提示或者将源码中的使用的较新的api标注一下（v1的代码我没全看）

**Comment by seeksdream** [comment]
我这里只有一个ipad，最新版本v2.x我简单测试过，有问题，不过还没有白屏的现象

**Comment by yuguaa** [comment]
最近迭代项目，降级vconsole看到了报错，组件的语法报错，猜想可能是webpack5的问题，因为配置好了babel的。后来框架降级，使用webpack4，页面正常渲染了，但是部分机型还是有点问题，不得已使用了G6重构。
