### ISSUE TITLE
npm版本v1.1.0自动布局报错

### ISSUE THREAD

**Issue by MiQifirefly** [seeksdream/relation-graph#11]
![image](https://user-images.githubusercontent.com/26457163/109593025-3cef2000-7b4b-11eb-96c9-1e20e7821d37.png)

**Comment by DingQi1990** [comment]
解决了 老哥？

**Comment by seeksdream** [comment]
试试最新的v2版本
你还可以通过在线工具，自定义数据、自定义配置试试最新版是否还有这个问题：
https://seeksdream.github.io/#/options-tools
