### ISSUE TITLE
相同的数据节点会变少

### ISSUE THREAD

**Issue by happynova4728** [seeksdream/relation-graph#12]
第一次进入页面正常,第二次进入的时候
节点数据会变少
![image](https://user-images.githubusercontent.com/39641665/109616706-75edbb80-7b70-11eb-94d7-f90fde7cee92.png)
需要布局的节点数量： 7
与第一个比数量减少

**Comment by seeksdream** [comment]
v1版本中某些情况下的确会有这个问题
你试试最新版v2.x，这个问题应该是被解决了

你还可以通过这个在线工具，设置数据后来试试：
https://seeksdream.github.io/#/options-tools
