### ISSUE TITLE
通过cdn链接引入不生效 setJsonData方法报错

### ISSUE THREAD

**Issue by Dirtyblack1995** [seeksdream/relation-graph#123]
通过cdn链接引入不生效 setJsonData方法报错

**Comment by seeksdream** [comment]
请参考一下这个demo:
https://seeksdream.github.io/#/docs/start
<img width="1743" alt="image" src="https://user-images.githubusercontent.com/40479975/220345781-a479b8ee-9b7c-46c3-9984-9570d4c50a2b.png">

上图可见，这个示例是可以运行的，但也有可能会因为网络的问题加载不到这些js，导致各种奇怪的问题，你可以把这几个js下载下来放到你的项目中使用。

你再试试
