### ISSUE TITLE
节点少时连接线文字缺失

### ISSUE THREAD

**Issue by Zy76278** [seeksdream/relation-graph#124]
节点少时，连接线上面的文字部分不显示，现在测的是少于五个节点会缺一个。
就拿官网上面的例子讲就少一个。
<img width="656" alt="1" src="https://user-images.githubusercontent.com/92496121/216873267-44c15392-4948-4c06-b86f-fb68efef7280.png">
<img width="524" alt="2" src="https://user-images.githubusercontent.com/92496121/216873302-4ebd681d-892a-4f02-8414-8993cb6d1c01.png">

**Comment by Zy76278** [comment]
但是动一下连接线连接的节点就能显示文字了

**Comment by hevolf** [comment]
我最近也一直在搞这个问题，还没找到解决方法

**Comment by seeksdream** [comment]
这个是一个bug,在版本2.0.15中已经解决，更新一下就好了
@Zy76278 @hevolf

**Comment by hevolf** [comment]
Cannot find "/vue2/relation-graph.umd.js" in relation-graph@2.0.15

**Comment by hevolf** [comment]
> 这个是一个bug,在版本2.0.15中已经解决，更新一下就好了 @Zy76278 @hevolf
https://unpkg.com/relation-graph@2.0.15/vue2/relation-graph.umd.js
Cannot find "/vue2/relation-graph.umd.js" in relation-graph@2.0.15
@seeksdream

**Comment by Zy76278** [comment]
> > 这个是一个bug,在版本2.0.15中已经解决，更新一下就好了 @Zy76278 @hevolf
> > https://unpkg.com/relation-graph@2.0.15/vue2/relation-graph.umd.js
> > Cannot find "/vue2/relation-graph.umd.js" in relation-graph@2.0.15
> > @seeksdream

我也遇到了，但重新启动下项目就好了
