### ISSUE TITLE
多个跟节点的关系图怎么处理呢？

### ISSUE THREAD

**Issue by anne-jia** [seeksdream/relation-graph#125]
多个跟节点的时候关系图重贴太严重，数量大的时候加载效率也慢。
不能像图上面那样间距
![image](https://user-images.githubusercontent.com/55428501/217403907-5c8720c0-6653-4080-bf3b-fa3b08497279.png)

**Comment by seeksdream** [comment]
relation-graph支持对一个关系网布局，里面只包含与根节点有直接或者间接关系的节点，称之为【默认关系网】，之前是只会为【默认关系网】中的节点分配位置。
从2.0.1版本开始，还支持对孤点（无其他节点无任何关系的节点）自动分配位置
从2.0.15（2月21日发布）版本开始，支持对不包含在【默认关系网】中的节点（这些节点之间可以有关系）自动分配位置。

目前的自动分配位置其实就是让它们飘来飘去（效果见这个示例中的那些孤点：[https://seeksdream.github.io/#/demo/line）](https://seeksdream.github.io/#/demo/line%EF%BC%89)
飘来飘去的方式可能没法完全符合需要。

后续会通过api来让图谱可以真正的对多个网络进行布局，比如左侧一个树状网络，右侧一个圆形中心网络。
到时候文档会放在这里：https://seeksdream.github.io/#/demo/graph-instance-api
到时候我再关闭这个issue

**Comment by Lonfar** [comment]
> 多个跟节点的时候关系图重贴太严重，数量大的时候加载效率也慢。 不能像图上面那样间距 ![image](https://user-images.githubusercontent.com/55428501/217403907-5c8720c0-6653-4080-bf3b-fa3b08497279.png)

请问您的多个根节点的数据结构是什么样子的？可以发一下么？

**Comment by seeksdream** [comment]
现在最新版本中可以支持多个关系网自动展示：
只需要在options中加上：
`placeOtherGroup: true,`
即可
多个关系网+孤点一起展示的效果（多种布局均支持）：
https://www.relation-graph.com/#/demo/multi-group
https://www.relation-graph.com/#/demo/multi-group-2
https://www.relation-graph.com/#/demo/multi-group-3
