### ISSUE TITLE
Cannot read properties of undefined (reading 'placed')

### ISSUE THREAD

**Issue by Reeyc** [seeksdream/relation-graph#127]
![image](https://user-images.githubusercontent.com/51184461/218303818-ccb17f32-1702-403b-ba79-14815c315224.png)
![1676194933103](https://user-images.githubusercontent.com/51184461/218303708-6e097bb4-0219-4be7-8110-a3bd22d46e96.jpg)
直接copy的demo代码，没有任何修改，在项目中报错，麻烦帮忙看一下谢谢 https://github.com/seeksdream/relation-graph/blob/master/examples/views/seeks-graph-docs/demo/Demo4Line.vue

**Comment by seeksdream** [comment]
升级到最新版2.0.14试试，还是不行的话，你加我qq 3235808353
