### ISSUE TITLE
树形布局支持多个根节点，有什么好的解决办法

### ISSUE THREAD

**Issue by CaiNiaoFeng** [seeksdream/relation-graph#129]
当节点种存在，除了根节点 还有其他无父级节点的假根节点时，假根节点会自动渲染到左上角，并且多个会自动重叠在一起；期望他们 渲染在 子节点的附近
![image](https://user-images.githubusercontent.com/49576222/219028555-f0cc8666-c348-49e0-b934-29f22e2d8f8f.png)

**Comment by Yikhan** [comment]
我的办法是生成一个隐藏的顶层根节点，把所有假根节点和真的根节点都连接到这个顶层不可见的根节点上，同时把之间的关系线也设置为隐藏

**Comment by seeksdream** [comment]
relation-graph支持对一个关系网布局，里面只包含与根节点有直接或者间接关系的节点，称之为【默认关系网】，之前是只会为【默认关系网】中的节点分配位置。
从2.0.1版本开始，还支持对孤点（无其他节点无任何关系的节点）自动分配位置
从2.0.15（2月21日发布）版本开始，支持对不包含在【默认关系网】中的节点自动分配位置。

目前的自动分配位置其实就是让它们飘来飘去（效果见这个示例中的那些孤点：https://seeksdream.github.io/#/demo/line）
飘来飘去的方式可能没法完全符合需要。

后续会通过api来让图谱可以真正的对多个网络进行布局，比如左侧一个树状网络，右侧一个圆形中心网络。
到时候文档会放在这里：https://seeksdream.github.io/#/demo/graph-instance-api
到时候我再关闭这个issue

**Comment by seeksdream** [comment]
最新版本中可以一定程度上解决这个问题，至少不会让节点重叠在左上角，同时支持多个关系网同时展示。

现在最新版本中可以支持多个关系网自动展示：
只需要在options中加上：
`placeOtherGroup: true,`
即可
多个关系网+孤点一起展示的效果（多种布局均支持）：
https://www.relation-graph.com/#/demo/multi-group
https://www.relation-graph.com/#/demo/multi-group-2
https://www.relation-graph.com/#/demo/multi-group-3
