### ISSUE TITLE
建议适配移动端，touchmove和双指放大缩小。

### ISSUE THREAD

**Issue by gawinZhang** [seeksdream/relation-graph#13]

**Comment by seeksdream** [comment]
目前v2版本支持简单的触摸操作，后续会实现你说的双指放大缩小功能。
如果支持了我再回复你
欢迎大家发送pull request来参与开发，完善

**Comment by seeksdream** [comment]
最新版本v2.0.9起，已开始支持双指缩放。
我只在我的手机和pad上做了测试，欢迎大家在更多设备上测试：
https://seeksdream.github.io/#/demo/simple
