### ISSUE TITLE
移动端  on-node-expand   on-node-collapse方法失效

### ISSUE THREAD

**Issue by guanguangqiang** [seeksdream/relation-graph#130]
在移动端  on-node-expand   on-node-collapse方法失效
![image](https://user-images.githubusercontent.com/28950569/219335452-f119429e-4cfe-493e-a3ba-2a1ce93387b5.png)

**Comment by qin795217119** [comment]
同问

**Comment by seeksdream** [comment]
最新版中已解决此问题，之前是移动端并没有做太多的适配，更新到最新版本试试。

你也可以使用移动端访问在线示例，看看其中关于展开收缩的功能是否正常：
https://www.relation-graph.com/#/demo/list
