### ISSUE TITLE
是否可以使得偏移量centerOffset在自动居中时也能生效？

### ISSUE THREAD

**Issue by Yikhan** [seeksdream/relation-graph#131]
当启用moveToCenterWhenRefresh参数后，关系图会在居中时忽略centerOffset属性
这在有隐藏节点时十分不灵活，居中依然会把所有的节点（无论隐藏与否）统一计算

建议：
1. 增加一个option参数，让centerOffset可以在refresh后依旧生效
2. 或者增加一个参数，可以让isHide=true的节点不参与布局计算

**Comment by seeksdream** [comment]
好建议，我一定会想办法解决你这个问题

**Comment by seeksdream** [comment]
现在已经支持，但使用方式不太一样，详细这个文档中关于graphOffset_x和graphOffset_y的说明：
https://relation-graph.com/#/docs/graph
或者这里的说明：
https://relation-graph.com/#/options-tools
<img width="889" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/4a7d0a24-487c-4401-a9d4-44b60260b957">

**Comment by seeksdream** [comment]
https://relation-graph.com/#/demo/graph-offset
在线示例
