### ISSUE TITLE
on-line-click事件参数问题

### ISSUE THREAD

**Issue by Yikhan** [seeksdream/relation-graph#132]
版本号： v2.0.9

根据文档on-line-click事件回调提供两个参数：(lineObject, $event)

实际使用中发现第二个参数$event并非鼠标点击事件，而是和第一个参数一样是线条对象
![image](https://user-images.githubusercontent.com/22538712/219566987-734bb441-06e0-4b77-9ee3-aa06ab3e9480.png)

第三个参数为期望的点击事件$event (PointerEvent)，应该是函数签名定义有错误

但仅当点击线条本身时才会有第三个参数传递，否则为undefined

这里的另外一个问题是，点击线条的文本会使得线条进入点选状态，但是不会传递$event

**Comment by seeksdream** [comment]
的确存在这个问题，从2.0.14版本起，点击线条和文字都会传3个参数（lineObject, linkObject， $event），后续也会更新文档
