### ISSUE TITLE
引入会有这个报错，怎么解决

### ISSUE THREAD

**Issue by zxjdzxb** [seeksdream/relation-graph#135]
![image](https://user-images.githubusercontent.com/66003758/220025562-aedca3f3-d916-4aba-9921-e1b83533282f.png)

**Comment by seeksdream** [comment]
一般来说这个错误不影响使用：
![image](https://user-images.githubusercontent.com/40479975/220047104-ae1adc85-010f-4613-ad03-2780af0918c4.png)
但建议你升级到vue 2.x较新的版本，比如：
"vue": "2.7.14",
 "vue-template-compiler": "2.7.14",
