### ISSUE TITLE
vue3引入 Eslint报错

### ISSUE THREAD

**Issue by MuyianKing** [seeksdream/relation-graph#136]
'import/no-duplicates': 'off',
'import/no-self-import': 'off',
'import/no-cycle': 'off',
'import/no-relative-packages': 'off',
'import/no-named-as-default': 'off',
'import/no-named-as-default-member': 'off',
'import/named': 'off',

需要把这几个关掉，不影响代码运行，最好解决一下
![image](https://user-images.githubusercontent.com/44827414/220057002-33f7758d-8ea9-464f-9dec-c972ecdc4e99.png)

**Comment by seeksdream** [comment]
这是之前的版本，当时还没有.d.ts类型描述，你更新下最新版再试试
