### ISSUE TITLE
vue是最新版，relation-graph是2.0.8版本，运行报错

### ISSUE THREAD

**Issue by zhangtiaotiao151** [seeksdream/relation-graph#137]
error  in ./node_modules/relation-graph/lib/relation-graph.common.js

Module parse failed: Unexpected token (9979:2)
You may need an appropriate loader to handle this file type.
| }
| /* harmony default export */ var src_0 = ({
|   ...core4vue,
|   RelationGraphCore,
|   Layout,

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/SystemHelp.vue 11:0-43
 @ ./src/views/SystemHelp.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8888 webpack/hot/dev-server ./src/main.js

vue是最新版，relation-graph是2.0.8版本，运行报错，请问大佬如何解决？

**Comment by seeksdream** [comment]
升级到最新版2.0.14试试，还是不行的话，你加我qq 3235808353

**Comment by zhangtiaotiao151** [comment]
您的邮件已发到我的邮箱啦，辛苦啦！致敬
