### ISSUE TITLE
点击某一个节点时，关联节点是否能全部高亮展示

### ISSUE THREAD

**Issue by jason94188** [seeksdream/relation-graph#138]
![image](https://user-images.githubusercontent.com/44861773/220555456-9092037b-fc07-44f4-b39d-a03b817b755d.png)
比如点击了节点9，对应的节点91和节点2及连线同时高亮

**Comment by seeksdream** [comment]
可以，你可以参考这个例子：
http://relation-graph.com/#/demo/adv-effect2
这个例子可以让与被点击节点相关的连线全部高亮，做法就是:
1，通过getLinks获取所有关联，在丛中找出与被点击节点相关的关联，再丛中找到所有的线条。
2，更改这些线条的颜色

你按照这个思路也可以这样做：
1，获取被点击的节点nodeX，通过nodeX.targetNodes可以获取到与nodeX关联的节点数组arr
2，将arr中所有节点的颜色修改为高亮色

**Comment by hypgo** [comment]
你好，在这个效果的基础上，能不能实现给非关联节点添加一个半透明度的蒙版，让视觉效果都聚焦到点击选中的那些关联节点上。
