### ISSUE TITLE
是否支持分组，用不同颜色包裹区分呢

### ISSUE THREAD

**Issue by orgccc** [seeksdream/relation-graph#139]

**Comment by seeksdream** [comment]
目前还不支持自动分组，但可以通过画布插槽让节点分区域显示，这个方法有点傻，但也许能解决你的问题：
https://www.relation-graph.com/#/demo/area-set

代码：

`vue
<template>
  <div>
    <div style="width: calc(100% - 2px);height:calc(100vh - 60px);">
      <RelationGraph ref="graphRef" :options="userGraphOptions">
        <template slot="canvas-plug">
          <div style="width:1600px;height:800px;position:relative;margin-left:-800px;margin-top:-400px;">
            <div style="width:500px;height:800px;position:absolute;left:0px;top:0px;background-color: rgba(15,71,255,0.18);" />
            <div style="width:500px;height:800px;position:absolute;left:550px;top:0px;background-color: rgba(116,255,5,0.24);" />
            <div style="width:500px;height:800px;position:absolute;left:1100px;top:0px;background-color: rgba(255,247,9,0.24);" />
          </div>
        </template>
        <div slot="node" slot-scope="{node}">
          <div v-if="node.id === 'table-1'">
            <table class="c-data-table">
              <tr>
                <td colspan="3">{{node.text}}</td>
              </tr>
              <tr>
                <th>列1</th>
                <th>列2</th>
                <th>列3</th>
              </tr>
              <tr>
                <td>xxxx</td>
                <td>xxxx</td>
                <td>xxxx</td>
              </tr>
            </table>
          </div>
          <div v-if="node.id === 'table-2'">
            <table class="c-data-table">
              <tr>
                <td colspan="3">{{node.text}}</td>
              </tr>
              <tr>
              <th>列1</th>
              <th>列2</th>
              <th>列3</th>
              </tr>
              <tr>
              <td>xxxx</td>
              <td>xxxx</td>
              <td>xxxx</td>
              </tr>
            </table>
          </div>
          <div v-if="node.id === 'table-3'">
            <table class="c-data-table">
              <tr>
                <td colspan="3">{{node.text}}</td>
              </tr>
              <tr>
              <th>列1</th>
              <th>列2</th>
              <th>列3</th>
              </tr>
              <tr>
              <td>xxxx</td>
              <td>xxxx</td>
              <td>xxxx</td>
              </tr>
            </table>
          </div>
          <div v-if="node.id === 'table-4'">
            <table class="c-data-table">
              <tr>
                <td colspan="3">{{node.text}}</td>
              </tr>
              <tr>
              <th>列1</th>
              <th>列2</th>
              <th>列3</th>
              </tr>
              <tr>
              <td>xxxx</td>
              <td>xxxx</td>
              <td>xxxx</td>
              </tr>
            </table>
          </div>
          <div v-if="node.id === 'table-5'">
            <table class="c-data-table">
              <tr>
                <td colspan="3">{{node.text}}</td>
              </tr>
            </table>
          </div>
          <div v-if="node.id === 'table-6'">
            <table class="c-data-table">
              <tr>
                <td colspan="3">{{node.text}}</td>
              </tr>
              <tr>
              <th>列1</th>
              <th>列2</th>
              <th>列3</th>
              </tr>
              <tr>
              <td>xxxx</td>
              <td>xxxx</td>
              <td>xxxx</td>
              </tr>
            </table>
          </div>
          <div v-if="node.id === 'table-7'">
            <table class="c-data-table">
              <tr>
                <td colspan="3">{{node.text}}</td>
              </tr>
              <tr>
              <th>列1</th>
              <th>列2</th>
              <th>列3</th>
              </tr>
              <tbody>
              <td>xxxx</td>
              <td>xxxx</td>
              <td>xxxx</td>
              </tbody>
            </table>
          </div>
        </div>
      </RelationGraph>
    </div>
  </div>
</template>

<script>
// 如果您没有在main.js文件中使用Vue.use(RelationGraph); 就需要使用下面这一行代码来引入relation-graph
// import RelationGraph from 'relation-graph';
const userGraphOptions = {
  'backgrounImage': '',
  'backgrounImageNoRepeat': true,
  'layouts': [
    {
      'label': '手工',
      'layoutName': 'fixed',
      'layoutClassName': 'seeks-layout-fixed',
      'defaultJunctionPoint': 'border',
      'defaultNodeShape': 0,
      'defaultLineShape': 1
    }
  ],
  'defaultNodeBorderWidth': 0,
  'defaultNodeShape': 1,
  'defaultJunctionPoint': 'lr',
  'defaultLineShape': 4,
  defaultLineWidth: 2,
  defaultLineColor: '#000'
};
export default {
  name: 'Demo4Area',
  components: { },
  data() {
    return {
      g_loading: true,
      userGraphOptions
    };
  },
  created() {
  },
  mounted() {
    this.setGraphData();
  },
  methods: {
    setGraphData() {
      const graphData = {
        rootId: 'root',
        nodes: [
          { id: 'table-1', text: '表格1', x: -760, y: 100 },
          { id: 'table-2', text: '表格2', x: -760, y: 300 },
          { id: 'table-3', text: '表格3', x: -760, y: 600 },
          { id: 'table-4', text: '表格4', x: -200, y: 100 },
          { id: 'table-5', text: '山西xx贸易公司', x: -200, y: 400 },
          { id: 'table-6', text: '表格6', x: -200, y: 600 },
          { id: 'table-7', text: '表格7', x: 350, y: 100 }
        ],
        lines: [
          { from: 'table-2', to: 'table-4' },
          { from: 'table-2', to: 'table-5' },
          { from: 'table-2', to: 'table-6' },
          { from: 'table-3', to: 'table-6' },
          { from: 'table-5', to: 'table-7' },
          { from: 'table-6', to: 'table-7' }
        ]
      };
      this.$refs.graphRef.setJsonData(graphData, (graphInstance) => {

      });
    }
  }
};
</script>


<style scoped>
.c-data-table{
  background-color: #ffffff;
  border-collapse:collapse;
  width: 400px;
}
.c-data-table td,.c-data-table th{
  border:1px solid #333333;
  color: #333333;
  padding: 2px;
}
</style>

`
