### ISSUE TITLE
开发建议

### ISSUE THREAD

**Issue by SmallTeddy** [seeksdream/relation-graph#14]
因为看到目前已经可以实现了拖拽的效果，但是还不能更改子节点与父节点、子节点与子节点的关系，无法改变to、from的对象
另外，无法在配置里设置渲染结构的百分比，比如我想一打开就是70%大小展示（虽然可以缩放，但是有的时候图太大，一上来显示完整的要好一些）

**Comment by seeksdream** [comment]
更改子节点，父节点，关系，from，to这些都可以通过重新组织json_data后调用setJsonData方法来实现，只不过会重新布局而已。
目前最新版本的v2.x已经支持通过配置选项zoomToFitWhenRefresh=true，可以默认自动缩放到合适大小（展示所有节点）。
https://seeksdream.github.io/#/docs/graph
<img width="480" alt="image" src="https://user-images.githubusercontent.com/40479975/210181652-02767f39-307b-469d-ae0e-44aaecedca0c.png">

你还可以通过缩放方法来缩放到指定比例，请参考：
#35
