### ISSUE TITLE
怎么取消点击边的事件，取消边的特效

### ISSUE THREAD

**Issue by gitguang** [seeksdream/relation-graph#145]
点击边有一个流动的特效，这个怎么取消？
![image](https://user-images.githubusercontent.com/34731815/221545611-f23a9029-4b63-49b7-8a27-0a624339d14f.png)

**Comment by Yikhan** [comment]
文档里有说明：
<html>
<body>


options.disableLineClickEffect | 是否禁用线条默认的点击效果（选中、闪烁）
-- | --



</body>
</html>
