### ISSUE TITLE
生产环境打包后不显示连接线

### ISSUE THREAD

**Issue by hsk1995** [seeksdream/relation-graph#146]
![image](https://user-images.githubusercontent.com/40809868/221744565-40b533e5-b274-4571-9621-4b116262f76c.png)
如图，上图是测试环境下，并无异常
![image](https://user-images.githubusercontent.com/40809868/221744751-8536f864-ba94-4583-9015-38eb3803c5b5.png)
上图是生产环境，连接线无法显示
relation-graph的版本是2.0.20
vue的版本是2.6.13

**Comment by seeksdream** [comment]
你提供的信息还没法分析，也重现不了问题，你加一下我的qq: 3235808353，我看看

**Comment by seeksdream** [comment]
已联系 [hsk1995](https://github.com/hsk1995)解决，环境问题。
