### ISSUE TITLE
RelationGraph引入报错

### ISSUE THREAD

**Issue by Yikhan** [seeksdream/relation-graph#148]
version: >=2.0.19

import RelationGraph时报错：
<img width="703" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/22538712/222016722-5b146ae3-3721-401c-835e-494b9806b2c2.png">

源代码的申明文件似乎有问题：
relation-graph/vue2/index.d.ts
![image](https://user-images.githubusercontent.com/22538712/222016849-a5abd6e0-20ad-4f5f-af97-0be3e7ce22a6.png)
可以看到的导出的RelationGraph是interface，并非可以实例化的class

在2.0.19之前的版本导出是这样的：
![image](https://user-images.githubusercontent.com/22538712/222017037-779f62f8-5ded-46ed-ba6f-c37f406f49db.png)

**Comment by seeksdream** [comment]
的确存在这个问题，回头我修改一下
