### ISSUE TITLE
提供图形化操作界面

### ISSUE THREAD

**Issue by nidegexing** [seeksdream/relation-graph#15]
建议开发图形化操作界面，拖动创建节点和连线，自动生成数据。
类似百度脑图，非常感谢！！！

**Comment by seeksdream** [comment]
暂时没有这个计划，应该不会直接提供拖拽创建节点和线条的功能。
不过后续会开放图谱的方法api，可以自行实现你要的这些功能。

相关文档整理中，完成后可以在这里看到：
https://seeksdream.github.io/#/demo/graph-instance-api
