### ISSUE TITLE
线型加上各种虚线

### ISSUE THREAD

**Issue by chuwj** [seeksdream/relation-graph#150]
线型加上各种虚线，感觉更加完美；
另外例子中都是vue2的，vue3改动的比较大所以很多都不能用

**Comment by seeksdream** [comment]
现在示例中所有功能，都可以在vue2，vue3，react中使用了，需要更新到最新版。
你要的多种虚线样式：
https://www.relation-graph.com/#/demo/line-style1
选中效果样式：
https://www.relation-graph.com/#/demo/line-style2
