### ISSUE TITLE
引入报错

### ISSUE THREAD

**Issue by DragonQing** [seeksdream/relation-graph#152]
./node_modules/relation-graph/vue2/relation-graph.mjs
Module parse failed: Unexpected token (29:12)
You may need an appropriate loader to handle this file type.
|     try {
|       i.documentElement.doScroll("left");
|     } catch {
|       return void setTimeout(l, 50);
|     }

**Comment by seeksdream** [comment]
现在relation-graph的编译目标已设为：target: ['es2016']，你更新到最新版2.0.23试试
