### ISSUE TITLE
【bug】布局为“tree”模式时，defaultLineShape连线默认样式不生效?

### ISSUE THREAD

**Issue by wangkaisGH** [seeksdream/relation-graph#155]
1，layouts:{layoutName: "tree"}模式下，defaultLineShape这个字段的配置不生效么？但是我看工具栏里面的连线样式的切换能全局生效
2，连线上的文字useTextPath为true时，右侧节点连接左侧节点时text文字颠倒了

**Comment by seeksdream** [comment]
1，2.0.x中间版本有这个bug，现在最新版本已经修改了，你可以试试。
2，使用useTextPath和不使用，各有优缺点，具体还得看你的使用场景。

目前树装布局时，借助曲线+useTextPath和文字位置设置，基本绝大部分场景都能满足需求：
https://www.relation-graph.com/#/demo/line-text-position
https://www.relation-graph.com/#/demo/lineAdv2
