### ISSUE TITLE
版本1.1.0 使用 getLinks获取连线报错 

### ISSUE THREAD

**Issue by wengmm** [seeksdream/relation-graph#157]
如果升级版本 发现之前版本使用的 拓扑图样式变的有问题 1.1.0版本就没有getlinks这个方法可以用了吗 【难受】

**Comment by seeksdream** [comment]
如果你之前使用了fixed布局，更新到2.0.1到2.0.22，的确有问题，你更新到最新版2.0.23试试，另外新的fixed布局坐标系会有一些变化（现在是以图谱中心位置坐标为0,0），但都很好解决。
建议你升级到2.x，有问题可以联系我，qq: 3235808353
