### ISSUE TITLE
树状布局时，当数据量较多，展示正常，但是下载有问题，图形的背景色超出一定范围丢失

### ISSUE THREAD

**Issue by dream-fengwu** [seeksdream/relation-graph#161]
树状布局，下载的图片里，方框或者圆框的背景色超出一定范围就没有了

**Comment by chuckDch** [comment]
附议

**Comment by seeksdream** [comment]
请更新到最新版本试试，之前关于图谱下载的问题可能在不同版本中表现不一样，最新版本中vue3,react都做了升级优化，所有示例功能都支持vue3和react，也包括图谱下载功能的统一:
https://www.relation-graph.com/#/demo/list

如果升级后还是存在问题，请提供更多信息，比如截图或者操作步骤，非常感谢
