### ISSUE TITLE
右边的全屏、放大缩小等功能控件可以改语言吗？

### ISSUE THREAD

**Issue by shijunshen** [seeksdream/relation-graph#163]
想把这些全部改成英文请问有没有什么办法？

**Comment by seeksdream** [comment]
请更新到最版本，通过工具栏插槽可以实现你要的效果。

你还可以看看新版本工具栏中，默认已不再展示文字，而全是图标：
https://www.relation-graph.com/#/demo/list

如果你还是需要自定义工具栏，可以参考这个链接：
https://github.com/seeksdream/relation-graph/issues/178
