### ISSUE TITLE
自定义连线内容的插槽使用插槽slot=line不生效

### ISSUE THREAD

**Issue by HelenSilas** [seeksdream/relation-graph#164]
```vue
 <RelationGraph
  ref="seeksRelationGraph"
  :options="graphOptions"
  :on-node-click="onNodeClick"
  :on-line-click="onLineClick"
>
  <line-comp
      slot="line"
      slot-scope="{ line, link, relationGraph }"
      :line="line"
      :link="link"
      :relation-graph="relationGraph"
   />
</RelationGraph>

**Comment by Amyanhh** [comment]
<RelationGraph
        ref="seeksRelationGraph"
        :options="graphOptions"
        :on-node-click="onNodeClick"
        :on-line-click="onLineClick"
      >
        <line-comp
          slot="line"
          slot-scope="{ line, link, relationGraph }"
          :line="line"
          :link="link"
          :relation-graph="relationGraph"
        />
      </RelationGraph>

**Comment by AnHCat** [comment]
版本的问题，升级版本就可以了

**Comment by seeksdream** [comment]
最新版本中有更多关于连线插槽的示例：
https://www.relation-graph.com/#/demo/list?g=1

**Comment by jxl-hash** [comment]
请问自定义连线插槽中如何设置箭头的指向和自定义箭头呢
