### ISSUE TITLE
各节点之间的线条起始位置和文本位置如何调整呢？

### ISSUE THREAD

**Issue by RoyMustang617** [seeksdream/relation-graph#165]
想统一下各节点之间箭头的起始位置和线条上文字的位置，想留点空白，请问该如何操作呢？

**Comment by seeksdream** [comment]
在options中lineUseTextPath设置为true，再通过调整defaultLineTextOffset_x和defaultLineTextOffset_y来调整连线文字位置。
`
 lineUseTextPath: true,
  defaultLineTextOffset_x: 0,
  defaultLineTextOffset_y: 0,
`
 
效果请参考这个示例：
https://www.relation-graph.com/#/demo/line-text-position
