### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jwhyliujikai** [seeksdream/relation-graph#166]
鼠标放到节点上，与节点相连接的先可以添加一些动画，比如线条流动的动画

**Comment by seeksdream** [comment]
你可以通过以下思路实现这个效果：
1，参考这个示例通过插槽实现鼠标放在节点上的事件监听：
https://www.relation-graph.com/#/demo/adv-node-tips
2，在事件中获取节点相关的其他节点及连线，参考这个示例：
https://www.relation-graph.com/#/demo/adv-effect2
3，通过样式穿透、插槽自定义样式等让节点、连线展示成你要的效果：
https://www.relation-graph.com/#/demo/line-style1
https://www.relation-graph.com/#/demo/line-style2
