### ISSUE TITLE
 折叠某个展开的元素。另外一个折叠元素会一直闪动（应该是重新布局，重复了折叠元素个数次的布局）

### ISSUE THREAD

**Issue by benbtx** [seeksdream/relation-graph#167]
![1680578781313](https://user-images.githubusercontent.com/19159482/229679608-6e7f80ef-d2ca-4596-aa74-716ef44bd478.png)

折叠某个展开的元素。另外一个折叠元素会一直闪动（应该是重新布局，重复了折叠元素个数次的布局）

**Comment by yugestrive** [comment]
同问

**Comment by seeksdream** [comment]
我刚才尝试了一下并没有重现这个问题。
请更新到最新版试试是否还存在此问题，如果还存在请联系我，我们一起解决这个问题：QQ:3235808353。
