### ISSUE TITLE
为什么我只是在项目里import这个组件，就直接报错了

### ISSUE THREAD

**Issue by chimmyxi** [seeksdream/relation-graph#168]
![image](https://user-images.githubusercontent.com/59924267/232234843-e464e632-2994-44fc-b381-c2ad32b96da2.png)

**Comment by seeksdream** [comment]
目前还没有其他人反馈过此问题。
请更新到最新版试试是否还存在此问题，如果还存在请联系我，我帮你看看具体什么问题：QQ:3235808353。
