### ISSUE TITLE
移动画布使画布上的某一点居中

### ISSUE THREAD

**Issue by xialvjun** [seeksdream/relation-graph#17]
看 graph 对象上有 文档中没有的 api ： `graph.animateGoto(x, y, time, callback)` 以及 `graph.animateToZoom(zoom, time, callback)`, 可是用它跟 节点的 xy 去做操作，怎么操作都不能让节点居中，不懂这个函数的逻辑。

有这个函数的使用讲解吗？还是说 relation-graph 不支持 移动画布使画布上的某一点居中 ？

**Comment by seeksdream** [comment]
通过focusNodeById方法可以让一个node居中，animateGoto是一个组件内部使用，还不太成熟的方法。
