### ISSUE TITLE
节点能否加上鼠标双击，左键，右键等事件呢

### ISSUE THREAD

**Issue by Kevin185** [seeksdream/relation-graph#171]
你好，下个版本节点能否加上鼠标双击，左键，右键等事件呢

**Comment by xxafei** [comment]
你直接用节点插槽，然后绑定事件呗

**Comment by seeksdream** [comment]
首先更新到最新版，可以直接使用on-contextmenu事件：
https://www.relation-graph.com/#/demo/create-object-from-menu

观察示例，你会发现在此事件中可以获取到当前右键选中的是节点、连线、画布，以及具体的节点、连线对象
