### ISSUE TITLE
vue 3版本在IOS 上不显示

### ISSUE THREAD

**Issue by ayayui** [seeksdream/relation-graph#174]
vue 3版本在IOS 上不显示

**Comment by qq441269150** [comment]
vue3在IOS上报错 import_screenfull.default. on is nota function，希望作者早日解决

**Comment by qq441269150** [comment]
screenfull.js在ios上有点问题，在vue3/relation-graph.mjs文件中搜索de.on("change", i)，在前面加上de.on && 后，ios可以正常显示，只是全屏功能无效

**Comment by seeksdream** [comment]
此问题在最新版本中已修改。
