### ISSUE TITLE
加了动画平移 频繁点击按钮抖动问题

### ISSUE THREAD

**Issue by hua-222** [seeksdream/relation-graph#175]
![image](https://user-images.githubusercontent.com/59311968/234769765-aa147dfb-999c-4527-8a1d-6c643c93a728.png)
例如频繁点击单个按钮时 就会出现抖动问题了 我看到文档的demo也有这个bug 请问是什么问题导致的 具体要怎么解决

**Comment by seeksdream** [comment]
请参考这个回答：
https://github.com/seeksdream/relation-graph/issues/176

总之这个不是什么大问题，当然后续有时间的话，我会解决这个问题。
