### ISSUE TITLE
当设置成自动布局时 刚进页面就点击按钮 有抖动问题而且位置不正确 

### ISSUE THREAD

**Issue by hua-222** [seeksdream/relation-graph#176]
![image](https://user-images.githubusercontent.com/59311968/234771446-9dbabf9c-704a-4e18-a370-ce499626b445.png)
![image](https://user-images.githubusercontent.com/59311968/234771621-9fa5c2d9-5e43-488e-8423-9e2957230bb5.png)

当设置成自动布局时 刚进页面就点击按钮 有抖动问题而且位置不正确 如题 官方的效果、控制demo也有这个问题 不过手速要快 官网的debug时间较快

**Comment by yugestrive** [comment]
同问

**Comment by seeksdream** [comment]
哈哈，这个没有办法，当force布局正在进行时，节点会受到布局器持续影响，抖动不可避免。
如果一定要解决这个问题倒也很容易：
1，直接修改布局算法，首先为要移动的某个节点做标记，在布局器布局时，根据标记判断忽略它，这样就不会抖动了。
