### ISSUE TITLE
Vite + Vue3 引入的时候报错

### ISSUE THREAD

**Issue by 2239682857** [seeksdream/relation-graph#177]
✘ [ERROR] No matching export in "node_modules/vue/dist/vue.esm-bundler.js" for import "default"

    node_modules/relation-graph/vue2/relation-graph.mjs:14:7:
      14 │ import I from "vue";
         ╵        ^

4:56:09 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/relation-graph/vue2/relation-graph.mjs:14:7: ERROR: No matching export in "node_modules/vue/dist/vue.esm-bundler.js" for import "default"
    at failureErrorWithLog (.../node_modules/esbuild/lib/main.js:1636:15)
    at .../node_modules/esbuild/lib/main.js:1048:25
    at .../node_modules/esbuild/lib/main.js:1512:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

代码是写的中心化的Demo，麻烦您帮忙看一下呗，应该怎么处理

**Comment by xtthaop** [comment]
我的也报错，请问您是怎么解决的？

**Comment by xtthaop** [comment]
![QQ图片20231013111300](https://github.com/seeksdream/relation-graph/assets/34789109/74912ffc-c2ad-446e-a53e-76d3dfdc419f)

这个办法亲测可用
