### ISSUE TITLE
工具栏添加自定义按钮

### ISSUE THREAD

**Issue by Zy76278** [seeksdream/relation-graph#178]
怎么在工具栏添加自定义按钮呢

**Comment by seeksdream** [comment]
关于工具栏，基本可以支持你想要的任何功能：

通过插槽完全自定义工具栏：
https://www.relation-graph.com/#/demo/custom-toolbar

你还可以通过自己编写一个div，看起来像工具栏，然后把默认工具栏隐藏起来：
https://www.relation-graph.com/#/demo/my-graph-app
https://www.relation-graph.com/#/demo/find-min-path

自定义工具栏位置、样式：
https://www.relation-graph.com/#/demo/toolbar-position
