### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Yupung** [seeksdream/relation-graph#183]
能够加一个设置默认显示百分比的方法或配置

**Comment by seeksdream** [comment]
你可以通过以下方法设置默认缩放比例：
`const graphInstance = this.$refs.graphRef.getInstance();
graphInstance.setZoom(80);// 80表示80%`

一般你可以在setJsonData的回调函数中执行，或者在之后的 任何时候都可以。

**Comment by seeksdream** [comment]
https://www.relation-graph.com/#/demo/zoom
