### ISSUE TITLE
scale布局下图表布局问题建议

### ISSUE THREAD

**Issue by 17864307898** [seeksdream/relation-graph#184]
![image](https://github.com/seeksdream/relation-graph/assets/53637830/b36ac0a9-34a3-4e8f-b78f-fc92f73e9ddb)
建议自动获取当前页面的缩放比例，或者提供参数支持传入当前的缩放比例，根据缩放的比例重新计算当前图谱的位置及大小

**Comment by seeksdream** [comment]
非常好的建议，我会找个合适的时机实现这个需求
