### ISSUE TITLE
当连线太短时，箭头就会反方向

### ISSUE THREAD

**Issue by axiea5** [seeksdream/relation-graph#185]
目前为止还没找到解决方案

**Comment by lirl-cn** [comment]
线最短宽度设置大点...

**Comment by axiea5** [comment]
还有就是树形结构时，线条样式不能更改。这是新版本直接定死了吗

**Comment by LiangYongH** [comment]
@lirl-cn 怎么设置呢

**Comment by seeksdream** [comment]
一般出现这个问题的原因都是因为层级距离设置太少了，可以设置大一些试试：
解决方法参考：
https://github.com/seeksdream/relation-graph/issues/186
