### ISSUE TITLE
树结构，节点高度不一致时，会导致连接线出现弯折

### ISSUE THREAD

**Issue by lirl-cn** [seeksdream/relation-graph#186]
树结构，节点高度不一致时，会导致连接线出现弯折

**Comment by lirl-cn** [comment]
或者可以描述成节点之间的对齐方式不是上下居中导致

**Comment by seeksdream** [comment]
一般出现这个问题的原因都是因为层级距离设置太少了，可以设置大一些试试：
设置方法：
两种设置方式：
<img width="663" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/a6ff7640-ed5c-456c-849f-b747e6bfeb64">

https://www.relation-graph.com/#/demo/tree-distance
