### ISSUE TITLE
vue3版本下载jpg图失败

### ISSUE THREAD

**Issue by Ryanmx95** [seeksdream/relation-graph#190]
vue2版本，downloadAsImage(format, fileName)
vue3版本，downloadAsImage(fileName?: string, format = 'png')

下载按钮 @click="relationGraph.downloadAsImage('jpg')"，参数问题导致vue3版本下载jpg图失败，结果是 jpg.png

**Comment by seeksdream** [comment]
你再试试最新版本中是否还存在此问题。最新版本中关于react和vue3的下载功能都做了调整，应该能解决这个问题。
