### ISSUE TITLE
动态生成元素时候,沿着x轴排列时候 y轴保持不变时候元素的连线文字位置错乱,拖动后恢复

### ISSUE THREAD

**Issue by zoucc** [seeksdream/relation-graph#191]
showSeeksGraph() {

            var __graph_json_data = {
                rootId: 'a',
                disableDrag: true,
                nodes: //this.arrDataList,
                    [
                        { id: 'e2', text: 'E2', width: 20, height: 20, fixed: true, fixed: true, x: 0, y: 0 },
                        { id: 'e3', text: 'E3', width: 20, height: 20, fixed: true, fixed: true, x: 100, y: 0 },
                        { id: 'e4', text: 'E3', width: 20, height: 20, fixed: true, fixed: true, x: 200, y: 0 },
                    ],
                lines: [
                    { from: 'e2', to: 'e3', text: '关系1', color: '#43a2f1' },
                    { from: 'e3', to: 'e4', text: '关系1111', color: '#43a2f1' },
                ]
            }

            // this.mianData = __graph_json_data
            this.$refs.seeksRelationGraph.setJsonData(__graph_json_data, (seeksRGGraph) => {
                // this.mianData = seeksRGGraph.nodeViewList
                console.log(this.mianData);
            })
        },

![微信图片_20230606105157](https://github.com/seeksdream/relation-graph/assets/19507445/1d6393d7-b9af-4ea1-8f9f-e6df7b36c3bc)

**Comment by seeksdream** [comment]
你试试最新版本中是否还存在这个问题。
如果是，你可以在line的属性中加入useTextPath试试看看是否能解决此问题。
如果实在不行，你还可以每次给新节点的x加1，说不定能解决这个问题。
