### ISSUE TITLE
树形图节点展开/隐藏的样式可以单独修改吗

### ISSUE THREAD

**Issue by miswenwen** [seeksdream/relation-graph#192]
现在树形图 节点展开/隐藏的图标似乎和节点本身的背景色以及透明度捆绑在一起了。
这样节点如果使用了白底或者透明度，会导致节点展开/隐藏的这个图标要么看不见，要么变的半透明导致下面的节点间的连线会露出来。
不太美观

**Comment by seeksdream** [comment]
可以单独设置，通过样式穿透、通过插槽：

https://github.com/seeksdream/relation-graph/issues/208

https://www.relation-graph.com/#/demo/expand-holder-slot
