### ISSUE TITLE
目录文件重复 relation-graph-vue2-demo/src/demo/demo

### ISSUE THREAD

**Issue by zhuningbo** [seeksdream/relation-graph#194]
demo文件夹下，仍有demo文件夹，且内容和上一级文件夹内容一样。
![image](https://github.com/seeksdream/relation-graph/assets/22904749/a61af6af-477f-4bf0-b4c9-31ce07a63220)

**Comment by seeksdream** [comment]
非常好的意见，能看出来你是一位非常细心认真的人，给你点个赞。
