### ISSUE TITLE
节点相互关联，但是会重叠显示，需要手动拖动

### ISSUE THREAD

**Issue by u10k** [seeksdream/relation-graph#195]
环境
系统:win10
vue版本：2.6.13
relation-graph版本：2.0.26

拖动前：
![Snipaste_2023-06-08_17-01-07](https://github.com/seeksdream/relation-graph/assets/22042799/ae4a4b3b-67bb-4630-b7c4-cc19dcb42bdf)
拖动后：
![Snipaste_2023-06-08_17-00-54](https://github.com/seeksdream/relation-graph/assets/22042799/cf0559f5-3250-4ace-b79f-0dedb66a20f7)

**Comment by u10k** [comment]
找到问题了，不指定rootId就没这个问题了
![image](https://github.com/seeksdream/relation-graph/assets/22042799/811ffc52-fc0a-4129-98b7-8712def8a5f5)

**Comment by lichengze520** [comment]
> 找到问题了，不指定rootId就没这个问题了 ![image](https://private-user-images.githubusercontent.com/22042799/244333603-811ffc52-fc0a-4129-98b7-8712def8a5f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDE3MzUsIm5iZiI6MTcyNDY0MTQzNSwicGF0aCI6Ii8yMjA0Mjc5OS8yNDQzMzM2MDMtODExZmZjNTItZmMwYS00MTI5LTk4YjctODcxMmRlZjhhNWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAzMDM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYWZkMGY2YjllMWVhOTVmY2E1NGQwY2Y3MDQ0ZTk3MmMyNmU2YmJlZTU1YzE4YjM2NjY1OTM3ODJlMWI3OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFPM39o2Q54jpAUZ3GgrgEJM3sFuJBIq1wrm5kLuQog)

我也遇到了这个问题，that.focus(that.rootId）这块是怎么写的，大佬
