### ISSUE TITLE
已经将vue 和 vue-template-compiler 的版本改到2.6.13了 但是页面还是undefined

### ISSUE THREAD

**Issue by danweigongchengshi** [seeksdream/relation-graph#197]
![98c515804b1fc9ae18387cf419fce4d](https://github.com/seeksdream/relation-graph/assets/24502417/bcd0982e-3249-4235-9c9c-326ac9781220)
![274d923f50d0cff954b323308d5f634](https://github.com/seeksdream/relation-graph/assets/24502417/97414639-937f-47c6-9f3d-e608a02189bc)
![891fbc90ba9623a6068719437512cf4](https://github.com/seeksdream/relation-graph/assets/24502417/a77c5434-d73c-490e-bf27-9a396c93df5a)
控制台也没有报错

**Comment by danweigongchengshi** [comment]
一开始我使用的是最新版本的relation-graph  后来改为2.0.19

**Comment by u10k** [comment]
你node的版本是多少，我遇到这个问题，本地是显示正常没错，但是打包后显示的undefined

**Comment by danweigongchengshi** [comment]
node版本是14.21.2

**Comment by u10k** [comment]
> 

类似控制台没用输出报错信息么？
![image](https://github.com/seeksdream/relation-graph/assets/22042799/66372d82-de49-4c05-bf78-59e0791d84a9)

**Comment by u10k** [comment]
> 你node的版本是多少，我遇到这个问题，本地是显示正常没错，但是打包后显示的undefined

这个问题也找到了，还是因为打包时候vue版本的问题，总之版本不低于2.6.12就可以了

**Comment by Coderyida** [comment]
你们都咋解决的  版本已经升级到2.7.14了  也不行   uniapp中使用
