### ISSUE TITLE
单独引入组件后未按视窗大小定位中心点以及缩放大小

### ISSUE THREAD

**Issue by Douysl-MT** [seeksdream/relation-graph#198]
![捕获](https://github.com/seeksdream/relation-graph/assets/136286303/be421988-bb6a-4fc6-bd4d-7e96b3c6d12b)
单独引用组件，并用V-if控制显示或隐藏时，出现了无法根据当前父组件宽高自动重新定位中心点和大小缩放。

**Comment by lizhesystem** [comment]
遇到相同问题 +1 
默认缩放,没有根据父元素自动撑满

**Comment by seeksdream** [comment]
当图谱默认不是可见状态的处理办法：
https://www.relation-graph.com/#/demo/adv-hide-2-show
当图谱的容器大小发生变化时的处理方法：
https://www.relation-graph.com/#/demo/graph-resize
