### ISSUE TITLE
如何获取节点之间拖拽关系？

### ISSUE THREAD

**Issue by SingleJoy** [seeksdream/relation-graph#199]
如何获取节点之间拖拽关系？

**Comment by SingleJoy** [comment]
如何获取节点之间拖拽关系？

**Comment by seeksdream** [comment]
节点之间没有拖拽关系。
如果你想获取某个接口的相关节点，可以使用node1. targetNodes来获取与node1有关的所有其他节点。

**Comment by SingleJoy** [comment]
其中一个为未连线的孤立结点，拖拽到另外一个节点上，如何获取两个连线节点的关系？
