### ISSUE TITLE
线条的长度

### ISSUE THREAD

**Issue by cloris-l** [seeksdream/relation-graph#2]
连接节点的线条长度可以设置吗？怎么设置呢？

**Comment by seeksdream** [comment]
树状布局可以通过设置层级距离来设置线条的长度，参考：http://relation-graph.com/#/docs/layout，中的《tree / 树状布局 特有的选项》
其他布局暂时不支持，后续版本中会提供选项来实现线条长度的设置。

**Comment by seeksdream** [comment]
按照目前的设计，线条的长度其实完全取决于节点之间的距离。
在v1.1.0为中心布局添加新的配置distance_coefficient，可以设置各层级之间的距离，以达到调整连线长度的视觉效果。请参考：http://relation-graph.com/#/docs/layout 中的章节《center / 中心布局 特有的选项》），示例：http://relation-graph.com/#/demo/distance_coefficient

树状布局中的层级距离调整，请参考：http://relation-graph.com/#/docs/layout 中的章节《tree / 树状布局 特有的选项》。示例：http://relation-graph.com/#/demo/tree-distance

**Comment by chenjinsongcc** [comment]
目前其他布局依然不能设置线条长度
