### ISSUE TITLE
新增节点的时候 节点会重叠在同一个位置

### ISSUE THREAD

**Issue by zhangkuangwen** [seeksdream/relation-graph#200]

**Comment by huangziqiangj** [comment]
我也是，部分节点会完全重叠在一起，且不受自动布局改变所变化，必须手动拖拽开。想知道为什么

**Comment by huangziqiangj** [comment]
我也是，部分节点会完全重叠在一起，且不受自动布局改变所变化，必须手动拖拽开。想知道为什么

**Comment by HBA123** [comment]
可以看看我之前的[问题与解决方法](https://github.com/seeksdream/relation-graph/issues/189)。很有可能是添加的新节点与其它节点没有连接，导致节点会重复并且无法拖动，目前该组件还不支持多关系网，好像只能有一个关系网络。

**Comment by seeksdream** [comment]
导致这个问题的原因基本上是因为数据中存在多个关系网：
1，图谱默认只会处理一个关系网，即从根节点触发，与根节点有直接或者间接关系的节点组成的主关系网。
2，如果一些节点不能与根节点产生直接或者间接关系，那么这些节点就不会被分配位置。

最新版本中可以在options中设置一个选项placeOtherGroup: true,可以让图谱处理其他的关系网，示例效果：

https://www.relation-graph.com/#/demo/multi-group

https://www.relation-graph.com/#/demo/multi-group-2

https://www.relation-graph.com/#/demo/multi-group-3
