### ISSUE TITLE
点与边之间无法正常连线是什么问题啊（急）

### ISSUE THREAD

**Issue by luvi65** [seeksdream/relation-graph#201]
![image](https://github.com/seeksdream/relation-graph/assets/130231636/430cea86-56ee-4024-9736-d13c4e8e2780)
![image](https://github.com/seeksdream/relation-graph/assets/130231636/d430a962-4c24-4cec-8318-ed846a4489a1)

**Comment by 115552233** [comment]
你好解决了吗

**Comment by luvi65** [comment]
没有解决，还是那个莫名其妙的bug，不知道什么原因，正常的数据格式进行连线，有些可以有些不可以，然后页面部分点还会卡死
&nbsp;


也.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月24日(星期四) 晚上6:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [seeksdream/relation-graph] 点与边之间无法正常连线是什么问题啊（急） (Issue #201)





 
你好解决了吗

**Comment by seeksdream** [comment]
导致这个问题的原因基本上是因为数据中存在多个关系网：
1，图谱默认只会处理一个关系网，即从根节点触发，与根节点有直接或者间接关系的节点组成的主关系网。
2，如果一些节点不能与根节点产生直接或者间接关系，那么这些节点就不会被分配位置。

最新版本中可以在options中设置一个选项placeOtherGroup: true,可以让图谱处理其他的关系网，示例效果：

https://www.relation-graph.com/#/demo/multi-group

https://www.relation-graph.com/#/demo/multi-group-2

https://www.relation-graph.com/#/demo/multi-group-3
