### ISSUE TITLE
是否有缩略图效果

### ISSUE THREAD

**Issue by MisterPengPeng** [seeksdream/relation-graph#203]
大佬，这个插件有实现整体的缩略图效果么？

**Comment by wei-xingliang** [comment]
`allowShowMiniView: true` 官网文档里不知道为什么没有，而且个人这边试一下发现部分效果不生效，不是很好，你可以试试

**Comment by seeksdream** [comment]
目前不支持缩略图，原本做了一个半成品准备继续完善，但目前来看有这个需求的不多，所以这个需求一直搁置着。
