### ISSUE TITLE
React图片下载只展示右下角

### ISSUE THREAD

**Issue by AntArcticAnt** [seeksdream/relation-graph#206]
<img width="1627" alt="image" src="https://github.com/seeksdream/relation-graph/assets/17830772/2ffdade9-a9e5-4544-9082-05284a3a1393">

<img width="829" alt="image" src="https://github.com/seeksdream/relation-graph/assets/17830772/b5d7da78-4598-44a3-8cea-3fb447ede7d4">

**Comment by seeksdream** [comment]
你试试最新版本，针对react的图片下载功能做了不少优化。
