### ISSUE TITLE
折线箭头指向问题

### ISSUE THREAD

**Issue by LiangYongH** [seeksdream/relation-graph#207]

**Comment by LiangYongH** [comment]
![image](https://github.com/seeksdream/relation-graph/assets/77262179/7f3f75af-78c5-4ecb-a761-376687b845ab)

**Comment by seeksdream** [comment]
如果你的图并不是标准的树状结构，建议你可以使用曲线，那样效果会好一些：

示例：
https://www.relation-graph.com/#/demo/lineAdv2

（示例中的功能通过文档和Typescript描述文件中的说明都可以实现）
