### ISSUE TITLE
Tauri适配问题

### ISSUE THREAD

**Issue by Dessera** [seeksdream/relation-graph#209]
我在Tauri下使用该组件，在触发点击 / 拖拽事件时会报错，导致关系图不能操作，请问该如何解决这种情况？
![截图_选择区域_20230728143335](https://github.com/seeksdream/relation-graph/assets/60534347/af56eef6-1216-428c-b0bd-b95d6337a527)

**Comment by seeksdream** [comment]
你好，目前没有针对tauri平台做过测试。
类似uniapp,taro,tauri之类的平台较多，而目前relaiton-graph只根据用户需求，针对uniapp做了一些适配。
