### ISSUE TITLE
设置子节点全部隐藏后 父节点设置为收起后 子节点并没有隐藏。

### ISSUE THREAD

**Issue by changjiaqio** [seeksdream/relation-graph#215]
if (thisNode.id !== 'N1') { 
                thisNode.isShow = false;    //子节点全部隐藏
  } else {
      thisNode.expanded = false; 
      thisNode.expandHolderPosition = 'bottom';
  }
  
![image](https://github.com/seeksdream/relation-graph/assets/97518513/60549f2e-4743-4b15-b026-c809c14755b3)

**Comment by seeksdream** [comment]
在relation-graph v2.x较新的版本中，都不需要在展开收缩时自己去设置子节点的显示状态，你可能使用的版本比较旧：

试试最新版本，你可以看看这个示例：
https://www.relation-graph.com/#/demo/scene-org
