### ISSUE TITLE
节点连接线的建议

### ISSUE THREAD

**Issue by 1179193605** [seeksdream/relation-graph#218]
![image](https://github.com/seeksdream/relation-graph/assets/72011530/cc719a4b-3fa7-4852-ae75-33bbc66598c4)
节点间的效果可以加一个这种的吗？十分需要。

**Comment by 1179193605** [comment]
连接线需要有个运动的状态，echarts有但节点的分布不如这个灵活。

**Comment by seeksdream** [comment]
可以实现，但这个应该不会成为优先要实现的future
如果有需要，请联系我QQ 3235808353
