### ISSUE TITLE
relation-graph/react 内置下载问题

### ISSUE THREAD

**Issue by changjiaqio** [seeksdream/relation-graph#219]
1. 文档提供demo下载仍然是有问题的 下载时不会自动调整位置，必须手动updteView，并且updateView后-下载成功后并不会调整至原有位置。

2. onImageDownload => false 未生效 导致无法自定义下载。

3. onImageSaveAsFile 定义后下载动作不会生效（导致无法下载，就会导致下载动作无法知道何时图片下载完成--建议有一个下载完成的事件 emit 出来）。

4. 内置功能- 全屏时 右侧工具栏不会自动调整位置需要click body后才会调整位置。

5. 目前有lineClick事件 希望添加一个lineTextClick 事件。或者在 lineClick 事件 内冗余一个参数类型 ，当前click的是line 还是为 lineText。

**Comment by changjiaqio** [comment]
checked node 时 闪烁样式希望有一个defaultColor

**Comment by seeksdream** [comment]
问题1：react之前的版本中可能确实存在这个问题，你再试试最新版本。
问题2，3：现在自定义下载有很多种办法，比如现在支持getImageBase64方法来获取图谱的base64，这样你可以完全自定义下载过程。
问题4：这个问题已经解决，更新最新版试试。
问题5：现在点击连线文字也可以触发on-line-click事件，你是想让文字点击事件和连线分开吗？不建议这么做，因为连线本身就不容易被点中，再把文字点击事件分离开，连线更难被点中了。如果你想获取被点击的是文字，也有办法，比如获取点击事件的target来判断。

节点选中样式可以完全自定义修改，通过【样式穿透】/【全局样式重写】去修改即可，可以参考这个链接，他通过全局样式重写修改了选中连线的颜色和动画：
https://www.relation-graph.com/#/demo/line-style2
