### ISSUE TITLE
firefox 火狐浏览器显示有问题

### ISSUE THREAD

**Issue by stiei13wangluo** [seeksdream/relation-graph#22]
火狐浏览器 root节点显示有问题
<img width="1043" alt="图片" src="https://user-images.githubusercontent.com/10474594/116089836-d2370c80-a6d5-11eb-873d-516da6a1691c.png">

**Comment by seventeenbrother** [comment]
![image](https://user-images.githubusercontent.com/49639578/117279523-5fc3ea80-ae94-11eb-9e16-8d49acfb42bc.png)
在火狐浏览器中节点位置计算是出了什么问题吗 祖节点也会偏移，

**Comment by WindChimeBell** [comment]
设置下transform: none;就可以了

**Comment by seeksdream** [comment]
最新版本v2.x已修复此问题
