### ISSUE TITLE
动态添加节点数量超过6个就会变得卡顿，导致渲染不出来

### ISSUE THREAD

**Issue by wly13** [seeksdream/relation-graph#220]
![image](https://github.com/seeksdream/relation-graph/assets/33365251/480e584d-b600-4713-9408-1ad06a69ea1f)
我在代码中，会通过点击节点请求数据，这个数据量可能比较大，目前是一次性返回是个节点数据和连线，就会导致点击后，页面直接类似崩溃无法点击得卡顿现象，请求出来得节点和数据也没有渲染出来，这个有什么解决办法吗

**Comment by seeksdream** [comment]
我按照你的描述试着动态添加节点，动态追加100个也可以正常，没法重现你的问题。
你还有其他信息可以提供吗？如果现在还存在这个问题你可以加我QQ: 3235808353 我们一起进一步分析下原因
