### ISSUE TITLE
节点重叠在一起

### ISSUE THREAD

**Issue by 115552233** [seeksdream/relation-graph#221]
两节点之间有连线，但是节点叠在一起了，拖拽也托不动

**Comment by zohucen** [comment]
> 一般是因为这些节点不在主关系网中，即与根节点没有直接或者间接的关系，他们不会被分配位置，所以为挤在一起，也是因为没有被分配位置，所以x,y都是NaN,也无法正常拖拽。 最新版2.0.33中支持展示多个关系网： https://ssl.relation-graph.com/#/demo/multi-group

多个节点需要 手动分配 x,y 么？

**Comment by CreateSol** [comment]
placeOtherGroup: true, 追加此属性后依旧重叠在一起 
版本："relation-graph-vue3": "^2.2.1",
