### ISSUE TITLE
连线上文字多时，位置严重偏移，导致部分文字直接和节点重合，无法看全文字

### ISSUE THREAD

**Issue by zjznero** [seeksdream/relation-graph#222]
场景：在tree中，两个节点一起指向一个节点，一边连线的文字出现位置偏移，一边正常，同时连线上的文字也是非居中的

**Comment by seeksdream** [comment]
当tree布局+折线的情况下，当 箭头方向混乱时，的确会出现这种情况，因为折线上文字是一个绝对位置。
你可以通过以下几个方式解决这个问题：
1，尝试使用曲线，并使用文字顺着连线走的选项，这样会好一些，参考示例：
https://www.relation-graph.com/#/demo/lineAdv2
2，根据你的图谱的具体情况，调整折线上连线文字的位置：
https://www.relation-graph.com/#/demo/line-text-position

以上示例中的内容都能通过文档或Typescript描述文件中找到。
