### ISSUE TITLE
怎么能点击空白区域让选中状态消失？

### ISSUE THREAD

**Issue by y327595826** [seeksdream/relation-graph#223]
怎么能点击空白区域让选中状态消失？

**Comment by seeksdream** [comment]
你可以通过on-canvas-click时间来捕获画布空白处被点击的事件，然后通过以下代码来取消被选中的节点、连线：
`const graphInstance = this.$refs.graphRef.getInstance();
graphInstance.options.checkedNodeId = ''; // 设置选中的节点为空
graphInstance.options.checkedLineId = ''; // 设置选中的线条为空`

参考示例：
https://www.relation-graph.com/#/demo/canvas-event
