### ISSUE TITLE
设置transform 后 拖拽异常

### ISSUE THREAD

**Issue by qq441269150** [seeksdream/relation-graph#224]
因为项目需要横屏展示，所以设置组件为transform: rotate(90deg)

出现拖拽异常，观察发现是x y 轴的节点拖拽设置坐标还是参照的竖屏

例如：往横屏的上方边拖拽节点，期望节点在Y轴方向移动，实际在X轴方向移动，拖拽图谱时也是一样

因为项目紧急所以直接改了node_modules中拖拽的代码并打了补丁

希望能提供设置图谱展示方向的属性，支持css旋转后的拖拽功能

**Comment by seeksdream** [comment]
好的，这个需求我记下了，以后会考虑实现，但这将是一个优先级很低的需求
你的这个问题作为issues，我先关闭了哟
