### ISSUE TITLE
版本v2.0.25,vue版本2.6.14,不显示连线

### ISSUE THREAD

**Issue by yizhanghong** [seeksdream/relation-graph#225]
开发及生产模式均不显示连线，尝试过罪行的2.0.34及vue2.7.14 也不显示，
我的邮箱 865362414@qq.com 
packpage配置如下图
![360截图20230921111500539](https://github.com/seeksdream/relation-graph/assets/27800776/7e5927eb-65e4-4c3c-ac68-dbfb05a09c7c)

![360截图20230921111336254](https://github.com/seeksdream/relation-graph/assets/27800776/8e5a2ff8-271d-49f5-aeb3-d8c38f7b2ac8)

![360截图20230921111528998](https://github.com/seeksdream/relation-graph/assets/27800776/812e5ce4-072e-4eb7-a4b5-d56b12b95386)

**Comment by seeksdream** [comment]
你应该是使用了uniapp之类的平台，在这个平台上，你通过修改package.json中的vue版本并不能改变真正的vue版本。你可以安装一个vue dev tool，就能看到你的vue版本还是低版本的vue。

现在最新版本中已经支持针对uniapp的兼容功能，你可以试试。但在uniapp+vue2下，使用插槽自定义节点、连线还是需要一些额外处理才行。
