### ISSUE TITLE
开发环境和打包发布测试后展示效果不一致是为啥？

### ISSUE THREAD

**Issue by ma-zy1995** [seeksdream/relation-graph#228]
![1696663736714](https://github.com/seeksdream/relation-graph/assets/74633168/f5182d3c-bf1a-42a2-a122-71a328e5095e)

![1696663291084](https://github.com/seeksdream/relation-graph/assets/74633168/638c745c-a805-4217-ae04-922f0d5020e9)

**Comment by seeksdream** [comment]
你能提供更详细的信息吗？
有一种情况，如果你使用到了流水线工具来在测试、生产环境来发布你的程序，有可能会导致两边版本不一致，有可能会出现此问题（因为的确有个别版本中会对一些默认值做改动），如果是这样，你可以在package.json使用一个非常具体的版本，可以避免这个问题。

如果以上还不能解决你的问题，你可以联系我QQ：3235808353
