### ISSUE TITLE
图加载之后links丢失from和to字段

### ISSUE THREAD

**Issue by yourenit** [seeksdream/relation-graph#23]
this.$refs.seeksRelationGraph.setJsonData(graph, (seeksRGGraph) => {
      // 这些写上当图谱初始化完成后需要执行的代码
});
执行上述代码之后打印图的数据
console.log(this.$refs.seeksRelationGraph.getGraphJsonData());

结果links丢失from和to字段
![image](https://user-images.githubusercontent.com/16984341/116676973-3b6e9680-a9da-11eb-83d1-1ae93e24f6d8.png)

是我用法不对吗？

**Comment by seeksdream** [comment]
你可以这样做：
每一个link都会有fromNode和toNode属性，分别指向两个节点，这个link表示两个点之间的关联，两个有直接关系的节点之间有且只有一个link。
如果你想获取字符串类型from和to，你可以通过_link.fromNode.id和_link.toNode.id来获取
同时link中会存放relations，这是一个数组，里面包含着fronNode和toNode之间的多个线条数据，就像你图中的这个对象
