### ISSUE TITLE
树状布局下，子节点希望可以支持自定义布局

### ISSUE THREAD

**Issue by KTBOY** [seeksdream/relation-graph#232]
大概效果图1：![image](https://github.com/seeksdream/relation-graph/assets/52773276/eb44ca0b-ae48-4d83-8b1b-53c5294cbc54)
大概效果图2：![image](https://github.com/seeksdream/relation-graph/assets/52773276/e0f9f42c-5992-44c6-9fe7-bf6e0297d88d)

比如类似ant v G6 ,子节点可以竖向对齐
```
      treeGraph.node(function (node) {
      return {
        label: node.id,
        labelCfg: {
          offset: 10,
          position: node.children && node.children.length > 0 ? "" : "right"
        }
      };
    });
```

**Comment by seeksdream** [comment]
可以通过自定义布局来实现，具体还得看你的需求和数据特征:

作为通用布局其实很难满足这样的需求。而一切需求明确，数据特征明确，自定义布局可以满足你的任何需求：
https://www.relation-graph.com/#/demo/mix-layout
https://www.relation-graph.com/#/demo/smart-tree-layout
