### ISSUE TITLE
如何直接使用源码作为一个component放到你的项目中去用

### ISSUE THREAD

**Issue by AtroxEzerel** [seeksdream/relation-graph#235]
1.vue2使用源码作为一个component放到项目中去用，应该下载使用那些文件？

2.为什么issues只有1个了，之前的issues去哪看？

**Comment by seeksdream** [comment]
1，clone项目，将项目中relation-graph-xxx(vue2、vue3、react根据你使用版本)下的src文件夹放到你项目中并改名如MyGraph，然后你就可以在你的项目中引入这个MyGraphj了。
2，因为之前的issues已经被解答、已经被解决、或者确定无法解决而被关闭了。你可以点击issues列表顶部的Closed查看。
