### ISSUE TITLE
使用ltrb默认连接点时是用什么判断连接点在哪个方位的

### ISSUE THREAD

**Issue by Acmhuang** [seeksdream/relation-graph#236]
我使用的是fixed手工设定坐标布局，在使用ltrb默认连接点时如果距离过远会出现这种情况
![fe45f646339bd6b7241d1fb239e4820](https://github.com/seeksdream/relation-graph/assets/118154550/882e3c88-3ac1-4658-8109-01e50597d446)

**Comment by seeksdream** [comment]
你可以更换为lr或者将默认线条形状（defaultLineShape: 1 | 2| 3| 4| 5| 6）更改为其他的。
因为连接点位置没有问题，只不过在布局为树状且线条为折线时仍然选择上方作为连接点就看起来很怪异。
也许以后会优化这个连接点选择的逻辑，会加入这些判断。而目前暂时对这个优化需求没有足够的时间预算。

**Comment by Acmhuang** [comment]
那请问大佬可以单独设置每个节点的连接方位吗

**Comment by seeksdream** [comment]
> 那请问大佬可以单独设置每个节点的连接方位吗

目前还不可以，以后的版本中会支持。
但支持的方式不一定是给节点单独设置连接点方位。而是针对【连线】设置在【起始节点】的连接点方位和在【终止节点】的连接方位。具体还没想好，得再想想。
