### ISSUE TITLE
vue3本地项目:on-node-click事件不生效

### ISSUE THREAD

**Issue by user-xms-0313** [seeksdream/relation-graph#238]
![image](https://github.com/seeksdream/relation-graph/assets/48503176/a39c1342-48bf-4a6a-a821-64df743a2c98)
![image](https://github.com/seeksdream/relation-graph/assets/48503176/513c6170-9452-42a6-99a5-cf5048f075d7)
直接clone vue3的demo工程在本地运行，点击事件是有效的；把demo里面的app.vue代码复制到自己vue3项目中，关系图能正常加载，但是各类点击事件失效！

**Comment by seeksdream** [comment]
你可以尝试将on-node-click改成onNodeClick

图谱中的事件都是定义成这种onNodeClick驼峰写法的，但这种on-node-click的方式在大部分情况下也能用。

感谢你的反馈，后续我会将示例中的写法都改成onNodeClick

**Comment by user-xms-0313** [comment]
我尝试了下，在我项目中把on-node-click改为onNodeClick也不能触发自定义的事件，后面改成在onMounted中手动给instance的listeners.onNodeClick属性赋值就可以！
![image](https://github.com/seeksdream/relation-graph/assets/48503176/0180016a-1db4-4dfb-8955-67b11679dfed)

**Comment by seeksdream** [comment]
2.1.13这个版本的vue3事件确实有问题
事件的不能触发的问题会在下个版本2.1.14解决。

**Comment by seeksdream** [comment]
这个问题已经在2.1.14中修复，使用on-node-click或者onNodeClick都可以了
