### ISSUE TITLE
代码只开源到2.0.24版本吗

### ISSUE THREAD

**Issue by Lucifer1** [seeksdream/relation-graph#239]

**Comment by seeksdream** [comment]
不，代码会全部开源，但会滞后。

详细说明：

**【关于PR贡献】**
你看提交历史应该也能看到，relation-graph2023年8月之前经常性的持续半年没有更新，原因是我本身工作很忙，同时，小项目也很少有其他人来贡献PR。

**【关于版本更新的驱动力】**
relation-graph从2.0.24开始推出会员服务（[https://www.relation-graph.com/#/vip-services](https://www.relation-graph.com/#/vip-services)），到最新的2.1.15，近两个月的20多个版本更新基本都是由企业会员需求驱动，功能在完善，运行更稳定。
我们将这些为企业会员开发的新功能为【前瞻性功能】，这些功能当前也许仅适用于某会员的场景（比如会员使用的是react，那么可能这个功能是优先在react中完善的，vue2/vue3可能不包含或者尚未完善），企业会员可以随时获取最新的源代码。

**【关于开源代码到哪个版本】**
无论从要保持企业会员的领先性来讲，还是新功能包含个性化内容需要磨合需要版本对齐来讲，都不方便实时的将最新代码开源，这一点你需要理解，这是非常合理的做法。

**我会在2.1.x结束时，同时2.2.x发布时，公开2.1.x的源代码。**

**【结语】**
没有人有纯粹的奉献精神，尤其是作为IT从业者大家的收入都不低，时间就是金钱的道理在这个行业更明显一些。
作为项目发起者，我不希望在繁忙生活工作下连我都失去对这个库的维护动力，让relaion-graph变成一个死库。那样的话最新源代码可能永远都是2.0.24了。商业价值是它最好的维护下去的意义，没有之一，否则它更像是就是我一个人的玩具。

同时，新功能和特性也回馈了所有人，以企业会员不到5%的价格开通个人会员，就能看到额外的60多个包含了新特性的功能示例及代码。

感谢你的关注。

https://www.relation-graph.com/#/vip-services

<img width="1235" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/7c5e9a11-f02c-4087-850a-0b9cc0365385">
