### ISSUE TITLE
怎么从头开始使用你的项目，程序怎么运行

### ISSUE THREAD

**Issue by haoopan** [seeksdream/relation-graph#24]

**Comment by seeksdream** [comment]
1，使用vue2脚手架创建一个vue项目
2，yarn add relation-graph
3，参考这个页面来创建一个vue组件 并让他在App.vue中显示https://seeksdream.github.io/#/docs/start
4，yarn dev或yarn start来启动项目，你就可以在浏览器中看到了

如果你使用最最传统的网页开发，你可以参考以下页面的最下方章节《二，通过CDN方式使用》
https://seeksdream.github.io/#/docs/start
