### ISSUE TITLE
vue3中使用graphPlug的问题

### ISSUE THREAD

**Issue by ListeningRift** [seeksdream/relation-graph#240]
在vue3+ts项目中使用到了graphPlug插槽，按照示例上写#graph-plug但是ts报类型错误，
![image](https://github.com/seeksdream/relation-graph/assets/47731748/0f15b598-edb4-4ab6-bbd7-4023d4c9004b)，
直接写#graphPlug又完全不生效，插槽中的内容完全不会渲染出来

**Comment by seeksdream** [comment]
这是因为声明文件写的有问题，但不影响使用。使用graph-plug没有问题，只不过你这可能设置的ts校验太严格了，禁用掉这个错误或者暂时手工修改一下声明文件都可以解决这个问题：
<img width="1266" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/b981dfce-c1fa-4d3a-b0f2-3225127a0d3b">
下个版本会更新声明文件的错误。就这两天会发布出来，relation-graph@2.1.18
