### ISSUE TITLE
vue3不支持自定义【节点】插槽

### ISSUE THREAD

**Issue by kytool** [seeksdream/relation-graph#244]
使用官网示例https://www.relation-graph.com/#/demo/adv-slot2
目标：
![image](https://github.com/seeksdream/relation-graph/assets/98650328/bc6c8930-e044-41fe-9f55-3143ed9912bf)
实际：
![image](https://github.com/seeksdream/relation-graph/assets/98650328/0c2d10cc-0b99-40fe-b902-799970d1bebb)

**Comment by seeksdream** [comment]
这个示例写的比较早，是vue2早期的写法，你按照vue3的写一下就好了：
<img width="584" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/4ad1d382-fd13-4047-9b1a-5a75c110249c">
