### ISSUE TITLE
relation-graph怎么引入Sigmajs和Dagre布局啊

### ISSUE THREAD

**Issue by 18801214376lk** [seeksdream/relation-graph#247]

**Comment by seeksdream** [comment]
就正常在你的组件中import引入就行了
但关键不在这里，在relation-graph中使用其他布局的关键是：
1，将节点先传给sigmajs，让sigmajs布局
2，sigmajs布局完成后获取节点的位置
3，让relation-graph使用fixed布局来处理这些已经被分配位置的节点。

以上实现思路非常清晰，实现起来也并不难。

具体示例：
https://www.relation-graph.com/#/demo/use-sigma-layout
