### ISSUE TITLE
lineUseTextPath报错

### ISSUE THREAD

**Issue by konsin** [seeksdream/relation-graph#248]
2.1.19版本 VUE 3 无法设置文字跟随路径。提示`TypeError: Cannot read properties of undefined (reading 'getArrow')` 错误。
看源码的话是RGLinePath组件的问题，直接使用了未定义的relationGraph对象。
应该是`graphInstance$.value`吧

**Comment by seeksdream** [comment]
对的，下个版本解决解决这个问题。会和其他修改一起在本周内发布
