### ISSUE TITLE
节点位置不正确

### ISSUE THREAD

**Issue by Zy76278** [seeksdream/relation-graph#249]
节点的位置有偏移，偏移到线段连接以外的地方
![Snipaste_2023-12-04_10-37-55](https://github.com/seeksdream/relation-graph/assets/92496121/363710c1-d833-49d2-af50-8670e3cd710b)
官网示例也是：
![Snipaste_2023-12-04_10-39-41](https://github.com/seeksdream/relation-graph/assets/92496121/99108eb6-610d-4fe4-9fdd-852f69bd74b6)

**Comment by Zy76278** [comment]
> 你用的是什么浏览器，哪个版本呢？

谷歌浏览器，版本：107.0.5304.88（正式版本） （64 位）

**Comment by Zy76278** [comment]
> 你用的是什么浏览器，哪个版本呢？

我换成电脑自带的edge浏览器看是正常的

**Comment by seeksdream** [comment]
> > 你用的是什么浏览器，哪个版本呢？
> 
> 谷歌浏览器，版本：107.0.5304.88（正式版本） （64 位）

我找个时间下载一下这个版本的浏览器试试

**Comment by seeksdream** [comment]
兄弟实在抱歉，我精力有限，只能确保在firefox,edge,chrome的主流版本中正常使用，具体一个之前的某个具体版本中的问题我也不太好处理，下载一个对应版本的chrome也挺麻烦的。如果这个版本对你很重要，你可以考虑付费的人工技术支持服务：
https://relation-graph.com/#/vip-services
感谢理解

**Comment by seeksdream** [comment]
> 兄弟实在抱歉，我精力有限，只能确保在firefox,edge,chrome的主流版本中正常使用，具体一个之前的某个具体版本中的问题我也不太好处理，下载一个对应版本的chrome也挺麻烦的。如果这个版本对你很重要，你可以考虑付费的人工技术支持服务： https://relation-graph.com/#/vip-services 感谢理解

这个问题已修改，更新到relation-graph@2.1.25即可
