### ISSUE TITLE
mac 上 zoom 的方向很奇怪

### ISSUE THREAD

**Issue by xialvjun** [seeksdream/relation-graph#25]
https://github.com/seeksdream/relation-graph/blob/master/src/index.vue#L425-L436

目前是

向上滚动：放大
双指拉开：缩小

把 https://github.com/seeksdream/relation-graph/blob/master/src/index.vue#L431 这一行的 `1` 与 `-1` 交换位置（其实就是不需要对 mac 特殊对待），则会

向上滚动：缩小
双指拉开：放大

上下滚动 到底是缩小还是放大，它区别不明显，但是 双指拉开 这种 用户期望的肯定是 放大。所以似乎根本不应该对 mac 做特殊处理。

**Comment by seeksdream** [comment]
最新版本v2.0.9已修正，现在在mac和windows上都是一致效果
