### ISSUE TITLE
线上怎么绑定鼠标移入移出事件呢

### ISSUE THREAD

**Issue by GuocaiL** [seeksdream/relation-graph#251]
您好，我想实现一个类似节点详情悬浮框的功能，实现连边的详情悬浮框功能，请问怎么实现呢

**Comment by seeksdream** [comment]
你可以通过以下步骤实现：
1，在包裹<relation-graph>的div上添加mousemove事件。
2，鼠标在移动时，触发mousemove事件，通过事件e.target来判断当前是否移动到了线条上面。
3，判断是否移动到线条上的逻辑为：判断e.target是否拥有c-rg-line样式（移动到连线文字上的判断也同理），如果有则展示你的详情悬浮框，更合理的逻辑应该是判断e.target、及其父元素、及其爷爷元素。。。这些都是小问题，你可以解决的。
4，如果是移动到连线上，在使用e.target向上寻找时肯定可以寻找到一个盛放两点之间所有线条的元素.rel-link-peel，这个元素上有一个id，通过graphInstance.getLinkById（id）方法，可以获取到对应的Link，注意这个不是线条。
5，通过link.relations[0]可以获取到线条数据line，如果有Link中有多个线条（两点之间有多个线条时）你想获取到具体的线条，你可以判断e.target对应的.c-rg-line在.rel-link-peel中的索引lineIndex,然后通过link.relations[lineIndex]获取准确的线条。
<img width="1081" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/08e60a49-20c0-416a-9b0c-230f3cf92cf4">

relation-graph目前没有现成的针对线条的鼠标移入移出事件，添加太多这种不常用的事件会让这个组件太臃肿。而以上思路实现起来也很灵活，以下是一个示例，里面包含了线条的移入移出事件：
https://relation-graph.com/#/demo/visible-stuff-in-fullscreen
