### ISSUE TITLE
图谱显示异常

### ISSUE THREAD

**Issue by tozlam** [seeksdream/relation-graph#253]
![image](https://github.com/seeksdream/relation-graph/assets/19501383/6af27982-bc72-4444-a399-64b911a850d0)
节点少且横向显示时，在下方会有条黑线，有节点移动到黑线处时会擦除黑线

![image](https://github.com/seeksdream/relation-graph/assets/19501383/ef809af3-4608-4358-ab4a-095c4c6dafda)
节点有多条连接线时，线和文字会重叠显示

**Comment by seeksdream** [comment]
好的，这个问题我记下了
如果你要临时解决你的问题，你可以将【物理机】和【型号】这两个节点变大一些，这样空间更多能展示的线条也更多。
上面这个解决方法好像有点儿傻，但如果一定要解决这个问题好像只能让线条更拥挤，你的图中看起来空间还有可利用的空间，但如果线条再多一些呢？所以让线条更拥挤来解决这个问题好像也不太合适。
我思考一下如何合理的解决这个问题吧，也可能没有什么好办法，到时候我会把这个问题关闭。

另一个思路：你可以判断当两节点之间的线条过多时，可以将他们合并成一个线条，然后让他更粗一些，可点击，点击之后展示他们之间的所有关系信息。
