### ISSUE TITLE
force 模式下 animation 动画还没有结束 callback就已经执行了

### ISSUE THREAD

**Issue by MirThree** [seeksdream/relation-graph#254]

**Comment by seeksdream** [comment]
force布局下，并不会以force布局结束为标志调用callback，因为force布局可以设置布局测试，如果设置了100万次可能今天都调用不上callback了。
你可能是想问如何获取foce布局结束的信号，然后去做一些事儿，你可以使用定时检测graphInstance.options.autoLayouting===false来判断自动布局一结束。
