### ISSUE TITLE
官网的图示例全都是错位，就这么迫不及待推出VIP会员服务么

### ISSUE THREAD

**Issue by hevolf** [seeksdream/relation-graph#255]
![image](https://github.com/seeksdream/relation-graph/assets/24458343/7f8e5840-e092-44f7-88a8-0ab26c874b21)
![image](https://github.com/seeksdream/relation-graph/assets/24458343/6dbb72f9-f581-4d74-a9ee-d7f8391fd235)

**Comment by seeksdream** [comment]
【迫不及待】这个词儿用的好。
你在发现问题的时候都不查查以往的issues，也不留下你的浏览器版本。而是【迫不及待】的吐槽我提供会员服务了，好焦急的样子。

这个项目还有不少问题，我平时还要上班解决的不及时，比如这个问题，在某些chrome版本下存在错位。
但这些都不是我不能推出会员服务的理由，只要有人需要，并且我愿意，我就可以推出。

作为一个开源项目，如果你的主观能动性强，这些样式问题你能复现，很轻松就能解决，我也不奢求你贡献PR，但你觉得我是必须把代码写好、测试好然后交付给你使用，不能有问题否则就开喷，对吗？大哥你坐错位置了，那是甲方大客户的座位，你闪一边儿去。

最后，即使是甲方大客户，只要他们智商健全情绪稳定也不会在你们的软件出问题时质问你们：就这么【迫不及待】的要开公司吗？

**Comment by hevolf** [comment]
我焦急个啥，反正我又不用，只是之前体验过，但没一个稳定版本，再次看还是问题一大堆，你没时间解决跟我关系大么，我提出意见你可以改可以不改，跟开公司比合适么，至少有个基本产品跟服务吧，你又说自己时间不够，不够就别步子跨那么大，容易扯着（产品有问题很正常，但基本使用都有问题那还能说啥）
我提个意见而已，到底是谁急了，产品能做的更好点跟我又有屁大点关系

**Comment by seeksdream** [comment]
> 我焦急个啥，反正我又不用，只是之前体验过，但没一个稳定版本，再次看还是问题一大堆，你没时间解决跟我关系大么，我提出意见你可以改可以不改，跟开公司比合适么，至少有个基本产品跟服务吧，你又说自己时间不够，不够就别步子跨那么大，容易扯着（产品有问题很正常，但基本使用都有问题那还能说啥） 我提个意见而已，到底是谁急了，产品能做的更好点跟我又有屁大点关系

谁急你心理没点儿逼数吗
好好沟通你都不会，我得再按你的模式造句：
就你这智商和沟通能力，【迫不及待】着急上班赚钱合适吗？

**Comment by hevolf** [comment]
> > 我焦急个啥，反正我又不用，只是之前体验过，但没一个稳定版本，再次看还是问题一大堆，你没时间解决跟我关系大么，我提出意见你可以改可以不改，跟开公司比合适么，至少有个基本产品跟服务吧，你又说自己时间不够，不够就别步子跨那么大，容易扯着（产品有问题很正常，但基本使用都有问题那还能说啥） 我提个意见而已，到底是谁急了，产品能做的更好点跟我又有屁大点关系
> 
> 谁急你心理没点儿逼数吗 好好沟通你都不会，我得再按你的模式造句： 就你这智商和沟通能力，【迫不及待】着急上班赚钱合适吗？

呵呵，自己体会

**Comment by seeksdream** [comment]
> > > 我焦急个啥，反正我又不用，只是之前体验过，但没一个稳定版本，再次看还是问题一大堆，你没时间解决跟我关系大么，我提出意见你可以改可以不改，跟开公司比合适么，至少有个基本产品跟服务吧，你又说自己时间不够，不够就别步子跨那么大，容易扯着（产品有问题很正常，但基本使用都有问题那还能说啥） 我提个意见而已，到底是谁急了，产品能做的更好点跟我又有屁大点关系
> > 
> > 
> > 谁急你心理没点儿逼数吗 好好沟通你都不会，我得再按你的模式造句： 就你这智商和沟通能力，【迫不及待】着急上班赚钱合适吗？
> 
> 呵呵，自己体会

你也就只会呵呵，也组织不起几句有逻辑的话，还不能和开公司类比，还你只是提个意见而已，还容易扯着，扯着啥？你的蛋吗？
你感觉呵呵退场吧，缺教养思维混乱只会呵呵傻子

**Comment by seeksdream** [comment]
> > > > 我焦急个啥，反正我又不用，只是之前体验过，但没一个稳定版本，再次看还是问题一大堆，你没时间解决跟我关系大么，我提出意见你可以改可以不改，跟开公司比合适么，至少有个基本产品跟服务吧，你又说自己时间不够，不够就别步子跨那么大，容易扯着（产品有问题很正常，但基本使用都有问题那还能说啥） 我提个意见而已，到底是谁急了，产品能做的更好点跟我又有屁大点关系
> > > 
> > > 
> > > 谁急你心理没点儿逼数吗 好好沟通你都不会，我得再按你的模式造句： 就你这智商和沟通能力，【迫不及待】着急上班赚钱合适吗？
> > 
> > 
> > 呵呵，自己体会
> 
> 你也就只会呵呵，也组织不起几句有逻辑的话，还不能和开公司类比，还你只是提个意见而已，还容易扯着，扯着啥？你的蛋吗？ 你感觉呵呵退场吧，缺教养思维混乱只会呵呵傻子

抱歉，说傻子不是在贬损你。只是我的真实评价，就像你感觉我要扯着一样

**Comment by hevolf** [comment]
> > > > > 我焦急个啥，反正我又不用，只是之前体验过，但没一个稳定版本，再次看还是问题一大堆，你没时间解决跟我关系大么，我提出意见你可以改可以不改，跟开公司比合适么，至少有个基本产品跟服务吧，你又说自己时间不够，不够就别步子跨那么大，容易扯着（产品有问题很正常，但基本使用都有问题那还能说啥） 我提个意见而已，到底是谁急了，产品能做的更好点跟我又有屁大点关系
> > > > 
> > > > 
> > > > 谁急你心理没点儿逼数吗 好好沟通你都不会，我得再按你的模式造句： 就你这智商和沟通能力，【迫不及待】着急上班赚钱合适吗？
> > > 
> > > 
> > > 呵呵，自己体会
> > 
> > 
> > 你也就只会呵呵，也组织不起几句有逻辑的话，还不能和开公司类比，还你只是提个意见而已，还容易扯着，扯着啥？你的蛋吗？ 你感觉呵呵退场吧，缺教养思维混乱只会呵呵傻子
> 
> 抱歉，说傻子不是在贬损你。只是我对你的客观评价而已，就像你感觉我要扯着一样

自己脸上糊了一坨，还好意思，谁家官网这样，说一两句戳到你痛处了吧

**Comment by hevolf** [comment]
就你这智商也就这样了，但凡正常一点的都不会在issues里跟我互怼，玻璃心稀碎了吧

**Comment by seeksdream** [comment]
> 就你这智商也就这样了，但凡正常一点的都不会在issues里跟我互怼，玻璃心稀碎了吧

你这是示弱吗？智商不够我就该同情你？就该惯着你？

**Comment by hevolf** [comment]
> > > > > > 我焦急个啥，反正我又不用，只是之前体验过，但没一个稳定版本，再次看还是问题一大堆，你没时间解决跟我关系大么，我提出意见你可以改可以不改，跟开公司比合适么，至少有个基本产品跟服务吧，你又说自己时间不够，不够就别步子跨那么大，容易扯着（产品有问题很正常，但基本使用都有问题那还能说啥） 我提个意见而已，到底是谁急了，产品能做的更好点跟我又有屁大点关系
> > > > > 
> > > > > 
> > > > > 谁急你心理没点儿逼数吗 好好沟通你都不会，我得再按你的模式造句： 就你这智商和沟通能力，【迫不及待】着急上班赚钱合适吗？
> > > > 
> > > > 
> > > > 呵呵，自己体会
> > > 
> > > 
> > > 你也就只会呵呵，也组织不起几句有逻辑的话，还不能和开公司类比，还你只是提个意见而已，还容易扯着，扯着啥？你的蛋吗？ 你感觉呵呵退场吧，缺教养思维混乱只会呵呵傻子
> > 
> > 
> > 抱歉，说傻子不是在贬损你。只是我对你的客观评价而已，就像你感觉我要扯着一样
> 
> 自己脸上糊了一坨，还好意思，谁家官网这样，说一两句戳到你痛处了吧
> 
> 笑死，你终于是要展示你来的真实目的，喷人嘛，bug不能好好讨论喷会员服务，会员服务讲不过再开始喷官网，总要加一句，你急什么，戳到痛处了吧，现在终于开始人身攻击了。
> 
> 兄弟，硬气一点，直接骂多好，讲道理不是难为你自己吗，骂出来，这样你的嘴里会轻松点儿，能看出来你嘴里肯定有不少坨呢

我有啥好骂的，一两年前体验过，今天逛一下偶然再看到，别把自己想的多有用处，我示弱干嘛，就算评论区稀碎你觉得能影响我啥，你这情商智商真不适合

**Comment by seeksdream** [comment]
> 就你这智商也就这样了，但凡正常一点的都不会在issues里跟我互怼，玻璃心稀碎了吧

兄弟别怂，既然都开始人身攻击了，那就别藏着掖着：
<img width="967" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/9e5b2a0c-4fde-43bd-8e29-3d6b0d2e560a">

**Comment by seeksdream** [comment]
> > > > > > > 我焦急个啥，反正我又不用，只是之前体验过，但没一个稳定版本，再次看还是问题一大堆，你没时间解决跟我关系大么，我提出意见你可以改可以不改，跟开公司比合适么，至少有个基本产品跟服务吧，你又说自己时间不够，不够就别步子跨那么大，容易扯着（产品有问题很正常，但基本使用都有问题那还能说啥） 我提个意见而已，到底是谁急了，产品能做的更好点跟我又有屁大点关系
> > > > > > 
> > > > > > 
> > > > > > 谁急你心理没点儿逼数吗 好好沟通你都不会，我得再按你的模式造句： 就你这智商和沟通能力，【迫不及待】着急上班赚钱合适吗？
> > > > > 
> > > > > 
> > > > > 呵呵，自己体会
> > > > 
> > > > 
> > > > 你也就只会呵呵，也组织不起几句有逻辑的话，还不能和开公司类比，还你只是提个意见而已，还容易扯着，扯着啥？你的蛋吗？ 你感觉呵呵退场吧，缺教养思维混乱只会呵呵傻子
> > > 
> > > 
> > > 抱歉，说傻子不是在贬损你。只是我对你的客观评价而已，就像你感觉我要扯着一样
> > 
> > 
> > 自己脸上糊了一坨，还好意思，谁家官网这样，说一两句戳到你痛处了吧
> > 笑死，你终于是要展示你来的真实目的，喷人嘛，bug不能好好讨论喷会员服务，会员服务讲不过再开始喷官网，总要加一句，你急什么，戳到痛处了吧，现在终于开始人身攻击了。
> > 兄弟，硬气一点，直接骂多好，讲道理不是难为你自己吗，骂出来，这样你的嘴里会轻松点儿，能看出来你嘴里肯定有不少坨呢
> 
> 我有啥好骂的，一两年前体验过，今天逛一下偶然再看到，别把自己想的多有用处，我示弱干嘛，就算评论区稀碎你觉得能影响我啥，你这情商智商真不适合

哇塞，好似一个温情脉脉的老朋友，开喷了你又来这个，又要转移？你就不能直面眼下吗？

**Comment by hevolf** [comment]
就你这情商，怪不得你需要迫不及待赚钱，你这智商还是算了吧，比喻都看不懂，谁家公司门面上糊了一坨，客户还愿意进，
真的不知好歹

**Comment by seeksdream** [comment]
> 就你这情商，怪不得你需要迫不及待赚钱，你这智商还是算了吧，比喻都看不懂，谁家公司门面上糊了一坨，客户还愿意进， 真的不知好歹

对嘛，直接开喷，但麻烦你不要抄袭我的文案号码？你就真的一句有力度的话都组织不起来吗？

**Comment by hevolf** [comment]
> > 就你这情商，怪不得你需要迫不及待赚钱，你这智商还是算了吧，比喻都看不懂，谁家公司门面上糊了一坨，客户还愿意进， 真的不知好歹
> 
> 对嘛，直接开喷，但麻烦你不要抄袭我的文案号码？你就真的一句有力度的话都组织不起来吗？

我还需要喷吗？单看你在这的回复都知道心窝子都被戳碎了吧

**Comment by seeksdream** [comment]
> > > 就你这情商，怪不得你需要迫不及待赚钱，你这智商还是算了吧，比喻都看不懂，谁家公司门面上糊了一坨，客户还愿意进， 真的不知好歹
> > 
> > 
> > 对嘛，直接开喷，但麻烦你不要抄袭我的文案号码？你就真的一句有力度的话都组织不起来吗？
> 
> 我还需要喷吗？单看你在这的回复都知道心窝子都被戳碎了吧

你真的好搞笑啊，【你急个什么】【戳中痛处了吧】【心窝子戳碎了吧】，你好像一个活在自己世界里意淫的孤儿，你说的这些我全没有，我就想不通我是把我当成你了吗？你这是对我最大的侮辱

**Comment by seeksdream** [comment]
> > > 就你这情商，怪不得你需要迫不及待赚钱，你这智商还是算了吧，比喻都看不懂，谁家公司门面上糊了一坨，客户还愿意进， 真的不知好歹
> > 
> > 
> > 对嘛，直接开喷，但麻烦你不要抄袭我的文案号码？你就真的一句有力度的话都组织不起来吗？
> 
> 我还需要喷吗？单看你在这的回复都知道心窝子都被戳碎了吧

你为何把问题关闭了呢？你在再努努力，开出一个有100+ comment的issue，同时也让大家看看什么是转移换题，不讲逻辑，以及该如何应对像你这样的傻子

**Comment by hevolf** [comment]
> > > > 就你这情商，怪不得你需要迫不及待赚钱，你这智商还是算了吧，比喻都看不懂，谁家公司门面上糊了一坨，客户还愿意进， 真的不知好歹
> > > 
> > > 
> > > 对嘛，直接开喷，但麻烦你不要抄袭我的文案号码？你就真的一句有力度的话都组织不起来吗？
> > 
> > 
> > 我还需要喷吗？单看你在这的回复都知道心窝子都被戳碎了吧
> 
> 你为何把问题关闭了呢？你在再努努力，开出一个有100+ comment的issue，同时也让大家看看什么是转移换题，不讲逻辑，以及该如何应对像你这样的傻子

但凡有点脑子的人，第一时间肯定关注的是官网为什么乱了，而不是关注【迫不及待】，还说没戳到玻璃心，我真的笑了
自己慢慢玩吧

**Comment by seeksdream** [comment]
> > > > > 就你这情商，怪不得你需要迫不及待赚钱，你这智商还是算了吧，比喻都看不懂，谁家公司门面上糊了一坨，客户还愿意进， 真的不知好歹
> > > > 
> > > > 
> > > > 对嘛，直接开喷，但麻烦你不要抄袭我的文案号码？你就真的一句有力度的话都组织不起来吗？
> > > 
> > > 
> > > 我还需要喷吗？单看你在这的回复都知道心窝子都被戳碎了吧
> > 
> > 
> > 你为何把问题关闭了呢？你在再努努力，开出一个有100+ comment的issue，同时也让大家看看什么是转移换题，不讲逻辑，以及该如何应对像你这样的傻子
> 
> 但凡有点脑子的人，第一时间肯定关注的是官网为什么乱了，而不是关注【迫不及待】，还说没戳到玻璃心，我真的笑了 自己慢慢玩吧

不不不，问题要解决的，但也必须得回复你，【交流】是很有必要的，不能惯着你，否则你觉得自己不讲道理、东拉西扯无敌了呢，以为没人治得了你了呢。

**Comment by seeksdream** [comment]
这个问题已修改，更新到relation-graph@2.1.25即可
