### ISSUE TITLE
关于vue3+vite打包到线上报错的问题。

### ISSUE THREAD

**Issue by GuoChang2032** [seeksdream/relation-graph#256]
报错截图如下
![image](https://github.com/seeksdream/relation-graph/assets/24536679/a66faa5b-6dbd-4ad7-b99b-cc3827030f21)
![image](https://github.com/seeksdream/relation-graph/assets/24536679/a36e57e3-9a2d-4be0-a5e1-c61295eb8d39)

vue 3.2.25
vite 2.9.9
relation-graph 2.1.23

本地开发环境是好的，发布到线上就有这个问题，请问是怎么回事？

**Comment by seeksdream** [comment]
你的项目中在线上环境中应该是使用去除console.log打印日志了，但也许做的不完善，在去掉打印日志代码的同时，导致了问题。
如果可以配置，你需要排除relation-graph。如果不能，你需要解决如何让剔除日志打印的代码逻辑正确运行。

<img width="884" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/5eb35364-15ab-4989-8555-4fe7e1d6426b">

**Comment by GuoChang2032** [comment]
> 你的项目中在线上环境中应该是使用去除console.log打印日志了，但也许做的不完善，在去掉打印日志代码的同时，导致了问题。 如果可以配置，你需要排除relation-graph。如果不能，你需要解决如何让剔除日志打印的代码逻辑正确运行。
> 
> <img alt="image" width="884" src="https://private-user-images.githubusercontent.com/40479975/293844140-5eb35364-15ab-4989-8555-4fe7e1d6426b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjI2NTEsIm5iZiI6MTcwNDI2MjM1MSwicGF0aCI6Ii80MDQ3OTk3NS8yOTM4NDQxNDAtNWViMzUzNjQtMTVhYi00OTg5LTg1NTUtNGZlN2UxZDY0MjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA2MTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YjVmYTMyMmE1MGI1OWE0ZjViY2E5YzY5ZmIzZjY1ZDYyMDZiYzIyN2ZiNzA1MGVhY2MwNTNlZWZjYzc2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CUlJc5L-R94jTcLQsqq9lAAnpmnI9Wo3F9HGjUwsIb0">

好的，我试试！

**Comment by GuoChang2032** [comment]
解决了，感谢！顺便一提，你做的东西很棒！
