### ISSUE TITLE
请问官网的节点错位怎么解决

### ISSUE THREAD

**Issue by bgx1012** [seeksdream/relation-graph#257]
![1704264837732](https://github.com/seeksdream/relation-graph/assets/56542232/0bba4aff-bfc7-4e62-8f39-0b0194e8b330)
这种错位怎么解决

**Comment by seeksdream** [comment]
请提供一下你的浏览器版本，我现在手里的几个设备都没法复现这个问题，我先收集一下哪些版本下有问题，我统一做对应环境调试解决。

**Comment by bgx1012** [comment]
> 请提供一下你的浏览器版本，我现在手里的几个设备都没法复现这个问题，我先收集一下哪些版本下有问题，我统一做对应环境调试解决。
QQ浏览器12.1.1

**Comment by seeksdream** [comment]
这个问题已修改，更新到relation-graph@2.1.25即可

现象是：使用chromium107内核的浏览器在奖浏览器缩放比例调整为不能被5整除的比例时会显示异常（我观察到的），新版本的浏览器中不存在这个问题，但可以通过修改代码来解决这个问题，目前已经解决。你可以用你的QQ浏览器访问https://relation-graph.com/#/options-tools验证一下是否解决了。我的兼容性测试工具不支持QQ浏览器：
<img width="813" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/17a3d342-850c-49b7-9580-8a7822214453">
你帮忙测试一下，如果没问题了，可以关闭一下这个issues
