### ISSUE TITLE
节点如果是离散的多个树，展开功能似乎有问题

### ISSUE THREAD

**Issue by MagicLogic** [seeksdream/relation-graph#258]
你好，
       不知道是否支持离散节点的折叠功能，麻烦解答，感谢！
       如图，描述2节点无法折叠下游节点
![image](https://github.com/seeksdream/relation-graph/assets/22311672/f7c9e017-0826-4556-a7ec-686d0c7aa030)
```json

{
    "lines": [
        {
            "data": {},
            "from": "1",
            "lineWidth": 2,
            "text": "",
            "to": "4"
        },
        {
            "data": {},
            "from": "2",
            "lineWidth": 2,
            "text": "",
            "to": "3"
        }
    ],
    "nodes": [
        {
            "data": {},
            "expandHolderPosition": "right",
            "id": "1",
            "nodeShape": 1,
            "text": "描述1"
        },
        {
            "expandHolderPosition": "right",
            "id": "3",
            "nodeShape": 1,
            "text": "描述3"
        },
        {
            "expandHolderPosition": "right",
            "id": "4",
            "nodeShape": 1,
            "text": "描述4"
        },
        {
            "expandHolderPosition": "right",
            "id": "2",
            "nodeShape": 1,
            "text": "描述2"
        }
    ]
}
```

**Comment by seeksdream** [comment]
图谱默认只处理一个关系网（即以根节点扩散出来的主关系网，如果没有设置根节点，则会使用第一个节点作为根节点），节点2节点3默认不在主关系网中。
所以被没有被2,3所在的次关系网就没有被处理，所以没法获取节点的子节点父节点信息，也就不能折叠起来。你可以在options中加入"placeOtherGroup": true，这样就可以处理这些与根节点没有之间或者间接关系的节点。

**Comment by seeksdream** [comment]
> 图谱默认只处理一个关系网（即以根节点扩散出来的主关系网，如果没有设置根节点，则会使用第一个节点作为根节点），节点2节点3默认不在主关系网中。 所以被没有被2,3所在的次关系网就没有被处理，所以没法获取节点的子节点父节点信息，也就不能折叠起来。你可以在options中加入"placeOtherGroup": true，这样就可以处理这些与根节点没有之间或者间接关系的节点。

当加上placeOtherGroup选项时，你的数据会展示成这样：
<img width="825" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/9225afeb-02e1-4b93-a31a-efcd86d96650">
但效果是节点3看起来像是父节点，原因是节点3出现在nodes中的顺序早于节点2，使得图谱在处理其他关系网时，默认使用了节点3作为根节点向外扩散，你可以调整一下数据顺序。

对于多个关系网的处理方法现在还不完善，但一些简单的场景还是可以的，效果参考：
https://www.relation-graph.com/#/demo/multi-group
https://www.relation-graph.com/#/demo/multi-group-2
https://www.relation-graph.com/#/demo/multi-group-3


还有其他办法可以处理这种数据零散的、多个小关系网的方法，就是给他们之间建立虚拟关系（opacity=0线条）把他们连在一起，效果参考：
https://www.relation-graph.com/#/demo/show-single-nodes2
https://www.relation-graph.com/#/demo/show-single-nodes
https://www.relation-graph.com/#/demo/show-single-nodes3

**Comment by MagicLogic** [comment]
非常感谢！
