### ISSUE TITLE
节点多的时候，线条会乱

### ISSUE THREAD

**Issue by yinlingshishangS** [seeksdream/relation-graph#26]
![image](https://user-images.githubusercontent.com/35954690/117453265-5495bb00-af77-11eb-9e8c-1cfd1cca1414.png)

**Comment by WindChimeBell** [comment]
因为节点高度是动态的，高度不一，需要设置min_per_width、min_per_height属性，设置大一些就可以了
链接：http://relation-graph.com/#/docs/layout

**Comment by seeksdream** [comment]
你可以通过设置横向间隔距离来实现：
https://seeksdream.github.io/#/demo/tree-distance
