### ISSUE TITLE
树形图节点文字过长时，节点之间距离依赖的是min_per_width而不是max_per_width？

### ISSUE THREAD

**Issue by wjy012** [seeksdream/relation-graph#261]
官网在线配置工具，节点文字过长时，线条跑到前面去了，需要调min_per_width才能正常显示，不应该是设置节点最大间距吗？
![image](https://github.com/seeksdream/relation-graph/assets/67452478/6d83081f-e67c-4a38-b0e1-9b0baf44db2c)
![image](https://github.com/seeksdream/relation-graph/assets/67452478/58d493ca-05f1-472e-89b2-bfa70d953a6f)
![image](https://github.com/seeksdream/relation-graph/assets/67452478/5838a800-a598-481d-a3b4-112094cc1fd9)

**Comment by seeksdream** [comment]
你可以看看这个：https://www.relation-graph.com/#/demo/tree-distance

图谱默认会让图形在可见区域内尽量舒展开来。
但当你的屏幕非常大，而节点非常少时，你不想让你的伸展的很开，这时你设置的max会生效.
当你的屏幕非常小，而你又不想让你的图挤在一起时，这时你设置的min会生效.


另外，这个【间距】可能有一些歧义，因为它不是真正的间距，而是第N层节点的{中心}与第N+1层节点{中心}的距离（默认为{中心},可以通过node的alignItems属性设置为left/right/top/bottom，当设置为left时，指的就是第N层节点的{最左侧}与第N+1层节点{最左侧}的距离）。
所以可能有事看起来有些怪，但是只要理解了并做出正确设置，基本上也能解决大部分问题。
