### ISSUE TITLE
edge浏览器relation-graph错位的解决

### ISSUE THREAD

**Issue by wz0322** [seeksdream/relation-graph#263]
![cca83f7505507c1e53cdca71f8da59f](https://github.com/seeksdream/relation-graph/assets/109068083/89af9f14-6510-4f0f-bd3e-8fea0969c2b0)

**Comment by seeksdream** [comment]
请提供一下你的edge浏览器的版本
还是你使用的relation-graph的版本。

**Comment by seeksdream** [comment]
如果你使用的不是relation-graph@2.1.25，你可以先更新到2.1.25试试
