### ISSUE TITLE
双向数使用折线的情况下，左边折线上的文字会出现重合，右边是正常的，按理说左边折线上的文字的Y轴应该和节点对齐

### ISSUE THREAD

**Issue by 1016184576** [seeksdream/relation-graph#264]
![2121](https://github.com/seeksdream/relation-graph/assets/19464158/0916c5aa-0ed4-431c-883d-49f460d19ec1)
希望大佬回复一下

**Comment by seeksdream** [comment]
这个暂时没有什么简单解决的办法，只能通过自定义连线插槽来自定义文字位置。或者粗暴一些不显示文字。
以后会针对单个线条自定义文字的位置（靠近起点、中间、靠近终点）或者提供百分比设置（10%，50%，90%这种）。

**Comment by seeksdream** [comment]
现在，在最新版2.1.42或者2.2.0中，可以通过为线条设置以下属性，来指定文字在线条上的位置：
placeText: '20%'
效果：
<img width="1041" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/04c6d909-edb1-4c27-8b7c-17d8a1ed684b">
<img width="1089" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/48b01192-95c7-43e8-a889-6c401169f264">
示例地址：
https://www.relation-graph.com/#/demo/vue2?id=lineAdv2
