### ISSUE TITLE
图谱下载为图片，节点中的头像丢失了！！！！

### ISSUE THREAD

**Issue by taozuidesongshu** [seeksdream/relation-graph#265]
以这个图片链接为例子
https://dfiles.tms.beisen.com/portal/111077/b18e226d439c46ccbab050b84bd9458b_s.jpeg

### 这是代码开发界面，节点中是有头像的
![Snipaste_2024-01-17_19-42-45](https://github.com/seeksdream/relation-graph/assets/37061056/0a504422-efd9-4f89-a8bb-98763df38a41)

但是使用图谱的下载功能，下载后，头像却消失了
### 这是图片下载后预览
![relation-graph-89771](https://github.com/seeksdream/relation-graph/assets/37061056/6c7756e3-e1cc-488a-9791-0d1f328b892c)

**Comment by seeksdream** [comment]
这个具体原因我也不太确定，我猜可能是因为图片不支持跨域访问？
你可以看看这个示例：
https://www.relation-graph.com/#/demo/search-and-focus
这个示例中，图片都可以正常在截图中生成。
生成图片的过程不是直接截取像素的，而是在canvas画板中根据节点线条的颜色、大小、位置、内容等信息重新画一遍，而在花图片的时候可能会涉及跨域请求。

你这样嘛，我上面示例中的图片都支持跨域，你试着在你的图谱中使用这些图片，看看是否会正常，如果正常了，那就确定问题原因了

**Comment by taozuidesongshu** [comment]
谢谢你的回答
尝试使用了demo中的图片，进行截图，对比后发现结果确实不一样。你的猜测很有用。
