### ISSUE TITLE
有没有类似于缩进树这种呢

### ISSUE THREAD

**Issue by bxhz** [seeksdream/relation-graph#269]
![image](https://github.com/seeksdream/relation-graph/assets/40491201/290b4b78-5d14-4242-8b9b-20a112b4b4ba)

**Comment by seeksdream** [comment]
现在有了：
https://www.relation-graph.com/#/demo/vue2?id=layout-folder

https://www.relation-graph.com/#/demo/vue2?id=layout-folder2
