### ISSUE TITLE
节点间有多条线时怎么判断点击的是哪一条

### ISSUE THREAD

**Issue by mdkjs** [seeksdream/relation-graph#27]

**Comment by mwh1209** [comment]
同问

**Comment by seeksdream** [comment]
最新的v2版本在on-line-click事件中可以接收到3个参数(line,link,event)
line表示线条，即当前被点击的线条
link表示关联，节点之间的关联，两个有直接关系的节点之间有且只有一个关联（link），一个关联上会有一个或多个线条（link.relations）

所以，在on-line-click事件中你可以获取到被点击的线条，还可以获取到所有的线条
