### ISSUE TITLE
部分手机上显示异常

### ISSUE THREAD

**Issue by xxd310** [seeksdream/relation-graph#270]
在电脑端显示正常，在手机端显示的时候，节点与连线会错位，目前发现MIUI和鸿蒙系统会有这种问题，这有办法处理吗？谢谢
![微信图片_20240201095915](https://github.com/seeksdream/relation-graph/assets/25600876/0cf86c0c-50c1-45e5-94bc-a2e198b61dd6)

**Comment by xxd310** [comment]
目前用的relation-graph是2.1.24

**Comment by seeksdream** [comment]
没啥好办法，目前我手里也没有鸿蒙设备。
我会持续关注这个问题，以后有更多的人反馈这个问题或者有企业用户有需求时，会解决这个问题。
