### ISSUE TITLE
同样的options和data，两次渲染效果不同

### ISSUE THREAD

**Issue by zhaolei-hu** [seeksdream/relation-graph#272]
我用relation-graph的vue2版本绘制了一个图且正常渲染，有一个新的需求，需要在弹出的dialog中展示一个放大版本，我以相同的options和data渲染了一个新的图，其线条的渲染出现问题了。
> 我使用fixed布局，节点位置都是自定义的。

在页面正常渲染效果：
<img width="766" alt="image" src="https://github.com/seeksdream/relation-graph/assets/46555007/a6ed30b8-ac73-4637-b7d7-99b95339407d">
不更改任何配置的情况下，在dialog中渲染的一个新的：
<img width="881" alt="image" src="https://github.com/seeksdream/relation-graph/assets/46555007/caf7a387-04d9-4535-936f-df2cbeeb3ad0">
可以发现，线条的渲染出现了问题，好像是间距不够导致的绘制问题？
但是我两次渲染使用了相同的配置，出现这种问题有什么解决方案嘛？

**Comment by seeksdream** [comment]
可能是因为两次打开的dialog大小不一样，图谱会根据可见区域大小，适当的调整节点之间的距离，让画面尽量显得伸展舒畅。
我建议按你的需求设置好节点之间的横向距离和纵向，这样肯定就展示一致了。
设置固定横向纵向距离（即将横向最大和最小设置一样，将纵向最大和最小设置成一样）的方法可以参考：
https://www.relation-graph.com/#/demo/vue2?id=ever-changing-tree
<img width="1027" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/259ab6f5-1e18-4ce4-a365-7f01bd7298ac">
