### ISSUE TITLE
节点不居中

### ISSUE THREAD

**Issue by VVVLZ** [seeksdream/relation-graph#273]
![无标题](https://github.com/seeksdream/relation-graph/assets/87351068/3e3bfb8c-c4f4-4d07-b05b-1a3355b1f78f)
请问一下这个怎么解决啊

**Comment by seeksdream** [comment]
relation-graph有一个选项moveToCenterWhenRefresh,设置为true就可以在初始化时居中。https://www.relation-graph.com/#/docs/graph
或者你也可以在任何时候通过以下方法让图谱居中并缩放到和合适比例：
```typescript
graphInstance.setZoom(100);
graphInstance.moveToCenter();
graphInstance.zoomToFit();
``` 
如果还是不能满意，你可以通过设置画布偏移量，让图谱显示到你认为居中的位置：

https://www.relation-graph.com/#/options-tools
