### ISSUE TITLE
想请问下，最大能显示多少点和线，有没有优化方案。

### ISSUE THREAD

**Issue by zhangboxi** [seeksdream/relation-graph#276]
我在显示超过500+的点的时候，就有卡顿的情况出现

**Comment by seeksdream** [comment]
你可以升级到最新版2.1.42试试，有一些性能优化，普通电脑配置展示1000+节点完全没问题。
同时，针对大量数据可以做一些针对性的优化，也可以让普通电脑流畅展示5000节点+5000关系，这里有一个大量数据测试页面：
https://www.relation-graph.com/#/demo/vue2?id=layout-performance-test
