### ISSUE TITLE
树状布局每个层级的节点都是靠左显示应该怎么设置？

### ISSUE THREAD

**Issue by evinbob** [seeksdream/relation-graph#277]
![居左](https://github.com/seeksdream/relation-graph/assets/87006011/967bf80c-a20a-4b8f-9139-6204ff23f0b9)
大佬你好，请问树状布局由上之下显示，我想达到上图每层居左显示有相应的api参数可以直接使用吗？

**Comment by seeksdream** [comment]
你看看这个是不是你想要的效果：
https://www.relation-graph.com/#/demo/vue2?id=ever-changing-tree

<img width="1119" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/3b7379ab-152d-44d6-bfe3-f1c6b199f75f">
