### ISSUE TITLE
下载保存为图片的时候，节点太多的时候，会报错，无法下载保存图片

### ISSUE THREAD

**Issue by zhangjunqing123** [seeksdream/relation-graph#278]
当某个节点下存在许多子节点（500，600个）左右的时候，无法下载保存图片了，查看后台报错了，这个能否解决？
![微信图片_20240305155140](https://github.com/seeksdream/relation-graph/assets/162077721/a9d6dca2-99cb-44a1-b662-a6f919676165)

**Comment by seeksdream** [comment]
relation-graph中没有限制节点数据量，在导出图谱时，是使用html2canvas这个外部插件来实现的，如果节点太多无法导出，一般是因为节点多或者节点内容复杂（如包含图片）、导出时使用的电脑性能太差等等原因。
如果一定要解决这个问题，需要根据具体情况来分析并解决。
如果你的节点不复杂、电脑性能也不差，你可以QQ联系我，我们一起研究一下

**Comment by zhq1998** [comment]
我也遇到了这个问题，234条时候会下载报错
