### ISSUE TITLE
v2.1.35中，vue3，placeOtherGroup: true 失效，多个根节点依然会出现重叠

### ISSUE THREAD

**Issue by Whyjsee** [seeksdream/relation-graph#280]
### 配置了 placeOtherGroup: true 后，多个根节点布局依然会出现重叠
<img width="871" alt="Screenshot 2024-03-07 at 15 57 30" src="https://github.com/seeksdream/relation-graph/assets/7569533/c8f2103b-b946-4d33-8765-04f4eb751936">

### Options配置
```typescript
const graphOptions: RGV2Options = {
  // 这里可以参考"Graph 图谱"中的参数进行设置
  backgroundColor: "transparent",
  placeOtherGroup: true
}
```

### 测试数据（从 `objectkey_7` 后的节点都与根节点没有任何关联）
```typescript
  const __graph_json_data: RGJsonData = {
    rootId: "objectkey_1",
    nodes: [
      {
        id: "objectkey_1",
        text: "与辉同行主播、东方甄选高级合伙人",
      },
      {
        id: "subjectkey_1",
        text: "董宇辉",
      },
      {
        id: "objectkey_2",
        text: "157.3万",
      },
      {
        id: "objectkey_3",
        text: "天然反感热搜",
      },
      {
        id: "objectkey_4",
        text: "内衣内裤",
      },
      {
        id: "objectkey_5",
        text: "不买就说明你不需要这个东西",
      },
      {
        id: "objectkey_6",
        text: "上热搜后计划注销微博",
      },

      {
        id: "objectkey_7",
        text: "归巢计划",
      },
      {
        id: "subjectkey_7",
        text: "新东方",
      },
      {
        id: "objectkey_8",
        text: "安置老员工再就业，不涉及义务教育阶段学科类培训",
      },
      {
        id: "objectkey_9",
        text: "已完成义务教育阶段学科类培训整改",
      },
      {
        id: "objectkey_10",
        text: "不再审批新的学科类校外培训机构",
      },
      {
        id: "objectkey_11",
        text: "归巢计划招聘消息",
      }
    ],
    lines: [
      {
        from: "subjectkey_1",
        to: "objectkey_1",
      },
      {
        from: "subjectkey_1",
        to: "objectkey_2",
      },
      {
        from: "subjectkey_1",
        to: "objectkey_3",
      },
      {
        from: "subjectkey_1",
        to: "objectkey_4",
      },
      {
        from: "subjectkey_1",
        to: "objectkey_5",
      },
      {
        from: "subjectkey_1",
        to: "objectkey_6",
      },
      {
        from: "subjectkey_7",
        to: "objectkey_7",
      },
      {
        from: "objectkey_7",
        to: "objectkey_8",
      },
      {
        from: "subjectkey_7",
        to: "objectkey_9",
      },
      {
        from: "subjectkey_7",
        to: "objectkey_10",
      },
    ],
  };
```

**Comment by holyjunhui** [comment]
v2.1.35最新版本直接崩溃了。。。。

**Comment by seeksdream** [comment]
你可能在调用setJsonData的时候使用的实例graphInstance.setJsonData(),调用这个方法只会布局主关系网，如果需要布局其他的关系网，需要再调用一下graphInstance.refresh();完整代码应该是：
`
    const graphInstance = graphRef.value?.getInstance();
    if (graphInstance) {
        await graphInstance.setJsonData(__graph_json_data);
        await graphInstance.refresh();
    }
`
效果是这样的：
https://www.relation-graph.com/image/relation-graph-logo.svg#/demo/vue3?id=multi-group

还有一种方式，是调用组件本身的setJsonData方法：
graphRef.value?.setJsonData(__graph_json_data); 
这样也可以处理多个关系网。因为这个方法是一个快捷方法，它内部会调用
graphInstance.setJsonData(jsonData);
graphInstance.refresh()

总之，你再你的graphInstance.setJsonData(jsonData);方法后面再调用一下graphInstance.refresh()应该就好了。

以后的版本中会考虑在graphInstance.setJsonData方法中自动处理这些。

**Comment by seeksdream** [comment]
> v2.1.35最新版本直接崩溃了。。。。

你可以加我qq，反馈一下详细情况，使用什么样的代码导致了崩溃。
qq:
3235808353

**Comment by Whyjsee** [comment]
> 你可能在调用setJsonData的时候使用的实例graphInstance.setJsonData(),调用这个方法只会布局主关系网，如果需要布局其他的关系网，需要再调用一下graphInstance.refresh();完整代码应该是： `const graphInstance = graphRef.value?.getInstance(); if (graphInstance) { await graphInstance.setJsonData(__graph_json_data); await graphInstance.refresh(); }` 效果是这样的： https://www.relation-graph.com/image/relation-graph-logo.svg#/demo/vue3?id=multi-group
> 
> 还有一种方式，是调用组件本身的setJsonData方法： graphRef.value?.setJsonData(__graph_json_data); 这样也可以处理多个关系网。因为这个方法是一个快捷方法，它内部会调用 graphInstance.setJsonData(jsonData); graphInstance.refresh()
> 
> 总之，你再你的graphInstance.setJsonData(jsonData);方法后面再调用一下graphInstance.refresh()应该就好了。
> 
> 以后的版本中会考虑在graphInstance.setJsonData方法中自动处理这些。

感谢，refresh方法以及ref的setJsonData是生效的，重叠的布局恢复了
