### ISSUE TITLE
是否可以调整节点对齐方式

### ISSUE THREAD

**Issue by Wdam** [seeksdream/relation-graph#281]
我发现好像是顶端对齐的，如果节点高度不一样，看起来就不是很好看，能设置其他对齐方式吗

**Comment by seeksdream** [comment]
可以的，请查看这个示例：
<img width="939" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/30c16c17-ba0c-46b3-84be-df7c4ec0eba5">
这个示例中左侧节点都是尾部对齐，右侧节点都是左侧对齐，示例地址：
https://www.relation-graph.com/#/demo/vue2?id=investment-penetration
