### ISSUE TITLE
数据预览效果和开发效果布局不一致

### ISSUE THREAD

**Issue by jqdelove** [seeksdream/relation-graph#282]
预览效果
<img width="1904" alt="截屏2024-03-18 18 13 41" src="https://github.com/seeksdream/relation-graph/assets/33721560/766c2f9c-59cd-4524-b621-69f26967c738">
开发效果
![10791710752608_ pic](https://github.com/seeksdream/relation-graph/assets/33721560/144026c0-d1ab-4db0-85ce-639b6fccd18b)

**Comment by seeksdream** [comment]
那是因为设置的根节点不一样吧：
上图中的根节点是这个：
<img width="407" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/dca04b9d-d54d-4101-8f5b-8f08660e155d">
下图中的根节点变成了这个：
<img width="759" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/20ee383a-b26a-4892-afcc-8101d8cb4181">

以不同的节点作为根节点展示效果会差别巨大的

**Comment by jqdelove** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
