### ISSUE TITLE
连线显示有问题

### ISSUE THREAD

**Issue by zhangjunqing123** [seeksdream/relation-graph#283]
![511E694E-D01E-464b-A328-8EF63B0650DC](https://github.com/seeksdream/relation-graph/assets/162077721/780fca7d-470b-46f6-adac-1399f5801cb6)

**Comment by seeksdream** [comment]
你这俩节点本身就没对齐：
<img width="699" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/2d828ce2-6079-4c25-bc31-0674dd2be7cc">
