### ISSUE TITLE
火狐兼容性问题

### ISSUE THREAD

**Issue by lescc** [seeksdream/relation-graph#287]
页面报错加载不出来，火狐60版本

**Comment by seeksdream** [comment]
好的，这个问题我记下了，后续会在众多低版本的浏览器上统一做测试。
不过这个问题优先级为低，后续如果更多的人介意这个问题会提升优先级。如果着急解决这个兼容性问题，可以考虑使用企业会员服务（这里只做提醒，企业会员只是提供给大家的一个可选项，以避免耽误有此需求的朋友的事儿）
https://www.relation-graph.com/#/vip-services
