### ISSUE TITLE
节点的边框设置不生效

### ISSUE THREAD

**Issue by sorrytaobao** [seeksdream/relation-graph#289]
![image](https://github.com/seeksdream/relation-graph/assets/34848236/f3088f30-1117-41d4-b658-3614a00977f8)
节点的边框粗细，颜色设置都不起作用

**Comment by seeksdream** [comment]
这个问题现在看起来已经不存在：
<img width="1000" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/0fb8e033-7bbd-4f10-81cb-27ffd52a3727">
