### ISSUE TITLE
建议多加几个事件，就靠现在这四个事件，自由度太低了，可以多加几个事件啊

### ISSUE THREAD

**Issue by blcyzycc** [seeksdream/relation-graph#29]
1、节点开始拖动事件，可以进行阻止拖动
2、节点拖动实时触发
3、节点拖动结束

**Comment by seeksdream** [comment]
现在可以通过选项配置来禁用画布拖动、节点拖动
而节点拖动事件，尤其是实时拖动触发，这个暂时很少有人有这个需求。
这个组件主要是用于数据展示的，强交互的你可以将源代码下载下来自己修改一下，需要协助可以联系我
