### ISSUE TITLE
在开发环境上没有问题，但是打包部署之后就报错 React is not defined

### ISSUE THREAD

**Issue by BeiJiu123** [seeksdream/relation-graph#290]
![image](https://github.com/seeksdream/relation-graph/assets/74284601/d05c846e-344e-4c0f-a337-b1a5515dbe39)
![Uploading image.png…]()

**Comment by BeiJiu123** [comment]
![image](https://github.com/seeksdream/relation-graph/assets/74284601/f6d3e683-c722-4652-af5c-497bb8d464b4)
控制台是这样

**Comment by seeksdream** [comment]
你要确保你打包之后，React依然可用。
按说这种问题不应该发生，一般这样的问题也是关于项目打包配置的小问题，但在这里我也不知道怎么帮你解决，因为需要看你的项目的具体的配置信息。
