### ISSUE TITLE
Errors while rendering the graph in the 'tree' layout

### ISSUE THREAD

**Issue by slash006** [seeksdream/relation-graph#292]
The graph printout from example https://www.relation-graph.com/#/demo/vue2?id=line-text-position renders incorrectly
![relation-graph-18875](https://github.com/seeksdream/relation-graph/assets/11257579/ea83d05d-0dd4-4940-af9d-bad17ba68c35)

**Comment by seeksdream** [comment]
This bug should have been fixed already, you can update to 2.2.0 and give it a try. It might also be related to your browser version, you can try exporting the image again using your browser：
 https://www.relation-graph.com/#/demo/vue2?id=line-text-position
