### ISSUE TITLE
多次弹窗加载浏览器内存一直在增加

### ISSUE THREAD

**Issue by shmily-xxx** [seeksdream/relation-graph#297]
有清除 或者销毁方法吗  多次加载浏览器内存越来越大

**Comment by seeksdream** [comment]
要清除数据可以使用graphInstance.clearGraph();
要销毁方法可以通过vue或者react的方式即可：
vue:
<RelationGraph v-if=xxxxxx></RelationGraph>
react:
{
xxxxxx && <RelationGraph></RelationGraph>
}

**Comment by seeksdream** [comment]
要清除数据可以使用graphInstance.clearGraph();
要销毁方法可以通过vue或者react的方式即可：
vue:
```
<RelationGraph v-if=xxxxxx></RelationGraph>
```

react
```
{
xxxxxx && <RelationGraph></RelationGraph>
}
```
