### ISSUE TITLE
插槽在低版本vue上不可用，怎么办？

### ISSUE THREAD

**Issue by sorrytaobao** [seeksdream/relation-graph#298]
vue版本2.6.13可以正常显示
但是目前项目里用的是2.6.10，升级版本会有一些其他问题，不敢随便升级，请问有什么别的方案吗？
![image](https://github.com/seeksdream/relation-graph/assets/34848236/9afe0aab-487f-4107-83ad-c0f376b8bec8)

**Comment by seeksdream** [comment]
对于低版本的vue，如果插槽无法使用，可以通过额外设置以下选项来解决：
`
    ovUseNodeSlot: true, // 仅当你需要使用自定义节点插槽时才需要设置为true
    ovUseLineSlot: true, // 仅当你需要使用自定义连线插槽时才需要设置为true
    ovUseToolbarSlot: true,  // 仅当你需要使用自定义工具栏插槽时才需要设置为true
`

**Comment by qingyun1029** [comment]
> 问有什

非常感谢，我找到之前的回答了，也处理好了这个问题，后续如有需要，一定支持一些，很不错的项目，感谢分享，加油！
