### ISSUE TITLE
将数据使用axios会报错

### ISSUE THREAD

**Issue by cloris-l** [seeksdream/relation-graph#3]
我将渲染之后的graph_json_data数据，使用axios请求，会报错
![image](https://user-images.githubusercontent.com/6091535/97833108-83547f80-1d0f-11eb-9a4c-6dd38c69265f.png)
，我排查了下是nodes的数据会引起报错，可以看下这是什么问题吗

**Comment by seeksdream** [comment]
看这个异常应该是在尝试将graphJsonData发送到后台，发送前对graphJsonData进行序列化导致的错误。
通过setJsonData方法将数据传递给组建后，组件会对数据进行绑定dom、附加事件等操作，即数据会被组件污染。
包括通过graph.getNodes()方法（参考：http://relation-graph.com/#/docs/graph 中的《Methods / 方法》）获取到的节点对象，返回的也是非纯净的json数据对象。
后续版本会提供新的方法：getJsonNodes和getJsonLinks，可以获取图谱中当前所有的节点和关系数据（纯净的json数据）
