### ISSUE TITLE
请问下，有没有全屏，退出全屏的api呢？

### ISSUE THREAD

**Issue by qingyun1029** [seeksdream/relation-graph#301]
页面布局需要，不能使用自带的工具栏，所以需要自己通过点击某个按钮来实现全屏。谢谢！

**Comment by seeksdream** [comment]
可以的：
`
graphInstance.fullscreen();
`
工具栏所有的操作都可以通过api调用实现，其他工具栏的操作请参考这个示例：
https://www.relation-graph.com/#/demo/vue2?id=toolbar-tooltips
这个示例中完全使用自己的代码重写了一个工具栏，并添加了额外的按钮。

**Comment by qingyun1029** [comment]
> 可以的： `graphInstance.fullscreen();` 工具栏所有的操作都可以通过api调用实现，其他工具栏的操作请参考这个示例： https://www.relation-graph.com/#/demo/vue2?id=toolbar-tooltips 这个示例中完全使用自己的代码重写了一个工具栏，并添加了额外的按钮。

好的，谢谢！
