### ISSUE TITLE
请问同一棵树，是否支持纵向、横向多种方向布局呢？

### ISSUE THREAD

**Issue by qingyun1029** [seeksdream/relation-graph#302]
比如我的纵向树，里面的某一些节点希望可以横向布局，这种需求支持吗？
谢谢！

**Comment by seeksdream** [comment]
你是想要这样的效果吗：
<img width="1536" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/1acb3817-fdec-4d60-a76d-ab88a48af056">

这种布局目前只能通过混合布局来实现，实现起来会难一些，但是可以实现非常复杂的需求：
https://www.relation-graph.com/#/demo/vue2?id=mix-layout-2

**Comment by qingyun1029** [comment]
> 你是想要这样的效果吗： <img alt="image" width="1536" src="https://private-user-images.githubusercontent.com/40479975/329750135-1acb3817-fdec-4d60-a76d-ab88a48af056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDAzMDYsIm5iZiI6MTcxNTg0MDAwNiwicGF0aCI6Ii80MDQ3OTk3NS8zMjk3NTAxMzUtMWFjYjM4MTctZmRlYy00ZDYwLWE3NmQtYWI4OGE0OGFmMDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA2MTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOGZlNzM2M2Y2Y2ViMDU4OGJhMTZlZDQwMWEwZjZjZjU1ZWJmYzljNzAwNjIxOGMzN2VjYzliYzE3MTdhMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x9Pcd-O1Mqja3s7r3XOahe6I0W4Huvfd6WlPS6nCVq4">
> 
> 这种布局目前只能通过混合布局来实现，实现起来会难一些，但是可以实现非常复杂的需求： https://www.relation-graph.com/#/demo/vue2?id=mix-layout-2

谢谢，是的，不同类型的节点，希望可以布局方向不同。
另外，我发现你这个demo树，隐藏、展开节点时，布局不会乱，我看其他的例子，展开隐藏节点时，会先显示出来（和其他的节点重叠），然后重新布局位置，明显你这种方式好很多，请问怎么设置的呢？

**Comment by seeksdream** [comment]
> > 你是想要这样的效果吗： <img alt="image" width="1536" src="https://private-user-images.githubusercontent.com/40479975/329750135-1acb3817-fdec-4d60-a76d-ab88a48af056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDAzMDYsIm5iZiI6MTcxNTg0MDAwNiwicGF0aCI6Ii80MDQ3OTk3NS8zMjk3NTAxMzUtMWFjYjM4MTctZmRlYy00ZDYwLWE3NmQtYWI4OGE0OGFmMDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA2MTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOGZlNzM2M2Y2Y2ViMDU4OGJhMTZlZDQwMWEwZjZjZjU1ZWJmYzljNzAwNjIxOGMzN2VjYzliYzE3MTdhMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x9Pcd-O1Mqja3s7r3XOahe6I0W4Huvfd6WlPS6nCVq4">
> > 这种布局目前只能通过混合布局来实现，实现起来会难一些，但是可以实现非常复杂的需求： https://www.relation-graph.com/#/demo/vue2?id=mix-layout-2
> 
> 谢谢，是的，不同类型的节点，希望可以布局方向不同。 另外，我发现你这个demo树，隐藏、展开节点时，布局不会乱，我看其他的例子，展开隐藏节点时，会先显示出来（和其他的节点重叠），然后重新布局位置，明显你这种方式好很多，请问怎么设置的呢？

你说的【我看其他的例子，展开隐藏节点时，会先显示出来】这个可能指的是默认的展示多个关系网的方式：
https://www.relation-graph.com/#/demo/vue2?id=multi-group-2
这种只适用于简单的应用场景，比如有很多个小关系网、数据都不是很多、相关之间没有什么关联的。

而在【混合布局】中，是会针对不同分组的节点创建多个不同的布局器对象：
`
const layout1 = RGLayouterUtils.createLayout(layoutOptions, graphInstance.options, graphInstance);
`
布局器对象会为各自需要处理的节点们分配位置。【混合布局】的示例：
https://www.relation-graph.com/#/demo/vue2?id=mix-layout
https://www.relation-graph.com/#/demo/vue2?id=mix-layout-3
