### ISSUE TITLE
vue3 用v-if控制后多次切换后用clearGraph()方法清除数据后  浏览器内存并没有减少 还是一直在增加

### ISSUE THREAD

**Issue by shmily-xxx** [seeksdream/relation-graph#304]
![1715398751698](https://github.com/seeksdream/relation-graph/assets/84055095/9fa4a114-e9ea-40a3-8a51-04ff6758b911)
![1715398935197](https://github.com/seeksdream/relation-graph/assets/84055095/f179ca4b-615a-47a5-98f5-693c30671102)
内存在增加
![1715398867140](https://github.com/seeksdream/relation-graph/assets/84055095/c8d79e13-5c39-4a80-a555-1bccf063ac12)
node节点在增加
![1715398909215](https://github.com/seeksdream/relation-graph/assets/84055095/17d10ef0-6db3-455f-a70e-23e075a9196e)
x相比较刚进页面内存没有减少多少
如果是大量数据这个问题比较严重 用v-if和clearGraph()都没有实质效果
[relation-graph.zip](https://github.com/seeksdream/relation-graph/files/15281531/relation-graph.zip)
这个是官方例子我稍微修改了下

**Comment by seeksdream** [comment]
抱歉兄弟，今天才下载你的附件并运行起来。
不过发现你的附件可能放错了，附件中这个示例找不到任何和relation-graph有关的内容。
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/806a43eb-078c-43ce-9fd1-25a3a51f4b39">

**Comment by seeksdream** [comment]
实在抱歉这么晚答复你，如果您还需要解决这个问题，可以加我QQ: 3235808353
