### ISSUE TITLE
如何划分区域

### ISSUE THREAD

**Issue by LHK5921** [seeksdream/relation-graph#305]

**Comment by LHK5921** [comment]
我需要实现网络区域划分，比如：安全区、管理区

**Comment by LHK5921** [comment]
![image](https://github.com/seeksdream/relation-graph/assets/130959146/76914b4b-9e5a-485f-8720-c50bb2e38bd1)

**Comment by seeksdream** [comment]
> 我需要实现网络区域划分，比如：安全区、管理区

你可以通过画布插槽，完全自定义你的区域划分：
https://www.relation-graph.com/#/demo/vue2?id=area-set

**Comment by seeksdream** [comment]
> ![image](https://private-user-images.githubusercontent.com/130959146/331076927-76914b4b-9e5a-485f-8720-c50bb2e38bd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTEzMzgsIm5iZiI6MTcxNjM1MTAzOCwicGF0aCI6Ii8xMzA5NTkxNDYvMzMxMDc2OTI3LTc2OTE0YjRiLTllNWEtNDg1Zi04NzIwLWM1MGJiMmUzOGJkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwNDEwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDkyOGEyYjgyNjc1MTNkYzZjYjYwYTRjMDMxZTk3ZTUzZjgxZWYwMzEwNTg1YjA0ODdkMDk2YjI4NmViNjFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DB6Rxk0_BQfqUx2byZREYSjIdQqy6NmG_h4DppCvOX8) 在拖拽添加节点时，为什么节点不在鼠标的中间而是在鼠标的右下角

我这里好像没法重现这个问题，我这里鼠标指针都能指向节点的中心，你可以加我QQ 3235808353录个视频发我看看
