### ISSUE TITLE
怎么单独控制某个节点或多个节点的层级关系

### ISSUE THREAD

**Issue by LHK5921** [seeksdream/relation-graph#307]

**Comment by seeksdream** [comment]
能再详细描述一下吗？
以我的理解回答下：
节点所处的层级是根据节点与根节点之间的关系路径自动计算出来的，这个不建议自行更改。要更改也最好是通过更新关系数据 --> 刷新布局 来更改。

不知道我理解对了没有，你可以继续补充，或者你的需求复杂不好描述，也可以QQ 3235808353联系我。
