### ISSUE TITLE
能不能在调用refresh刷新时不让缩放跳动那么明显呢，强迫症的人看着很难受

### ISSUE THREAD

**Issue by liuzewei1990** [seeksdream/relation-graph#308]

**Comment by seeksdream** [comment]
$graphRef.refresh()方法是一个动作比较大的方法，内容包括缩放居中动画等各种效果以及重新布局。

你可以使用$graphRef.getInstance().doLayout()方法来重新布局，这样的话不会有缩放居中这样的效果，应该可以避免你说的跳来跳去
