### ISSUE TITLE
线条插槽不能使用-- 并且使用了ovUseLineSlot属性

### ISSUE THREAD

**Issue by ZhouJing0** [seeksdream/relation-graph#309]
relation-graph@2.1.42
vue@2.6.10
使用 线条插槽 组件里复制的dome
<template #line="{ line, link, lineIndex }">
  <LineSlot :link="link" :relation="line" :relation-index="lineIndex" />
</template>
线条不生效 报错 Cannot read properties of undefined (reading 'getArrow')
说明 relationGraph 为undefined

**Comment by seeksdream** [comment]
relation-graph@2.1.x中在自定义节点、线条插槽中通过依赖注入获取graphInstance的方式发生了变化：
以前是：通过依赖的对象graph获取：graph.instance
现在是：通过依赖的方法graphInstance来获取：graphInstance()

你可以将你的代码以下内容按照下图修改一下就可以了：
<img width="1008" alt="image" src="https://github.com/seeksdream/relation-graph/assets/40479975/80cacd0b-566f-48c3-85eb-8dd3a3a9409b">

相关的示例：
https://www.relation-graph.com/#/demo/vue2?id=adv-line-slot2
