### ISSUE TITLE
`max_per_width`或`min_per_width`仅设置其中一个，另一个为`undefined`时，而设置的那项又与默认配置冲突时，会出现非预期的情况

### ISSUE THREAD

**Issue by Justin3go** [seeksdream/relation-graph#310]
### 问题描述

标题描述可能稍微有一点绕，接下来详细解释一下，主要就是这段代码的逻辑：

![image](https://github.com/seeksdream/relation-graph/assets/63507251/b9d257ab-3880-4722-ab4c-5b4542c2340e)

**情况1**：`min_per_width`为`undefined`，而用户设置的`max_per_width < 430`时，比如200。

就会出现`__min_per_width = 430`，而`__max_per_width=200`的情况，然后执行最后两行的`if语句`，此时倒是没有问题，因为判断max的语句在判断min语句之后执行，会将其重新设置为`__per_width = __max_per_width`即`200`，这是符合用户预期的。（但其实内部的逻辑也是错误的，只是恰好语句的顺序让代码正确执行了）

**情况2**：`max_per_width`为`undefined`，而用户设置的`min_per_width > 650`时，比如1000。

就会出现`__max_per_width = 650`，而`__min_per_width = 1000`的情况，然后同样执行最后两行的`if语句`，**此时就会出现问题**，先是倒数第二行语句将`__per_width`设置为`1000`，然后最后一行的语句又会将其设置为650，**这并不符合用户预期**。（用户只设置了`min_per_width`，结果出现的距离还小于用户设置的最小值）

### 解决方案

也许可以像下面这样增加一点逻辑：

![image](https://github.com/seeksdream/relation-graph/assets/63507251/247b0126-4e72-490a-aa4b-4b42dd44b3b1)

当然，这也许并不需要修改，仅仅在官网文档中提示一下仅设置其中一项时，配置的max值不得小于默认min值，配置的min值不得小于默认max值

因为之前我根据官网的配置：

![image](https://github.com/seeksdream/relation-graph/assets/63507251/ad1ec0b7-71e6-41e7-99b9-46304b37038e)

其中就有一项为`undefined`，然后我试图修改另外一项，并超过了默认值，就出现了非预期的情况。

- 我理解用户不会出现自己设置的`max值 < min值`的情况，
- 但很容易出现`自己设置的max值 < 代码里默认的min值`、`自己设置的min值 > 代码里默认的max值`，这通常会导致一些误解。

### 最后

还是非常感谢作者开源了此框架，并且如果此方案是可行的，我可以来完成此项任务。

**Comment by seeksdream** [comment]
好嘞，兄弟用心了，写的很细致。
下个版本(2.2.1)会包含这段逻辑，本周内发布
