### ISSUE TITLE
请问可以设置固定线的长度吗，而不是通过levelDistance、XX_per_width控制

### ISSUE THREAD

**Issue by Justin3go** [seeksdream/relation-graph#312]
![image](https://github.com/seeksdream/relation-graph/assets/63507251/1dc9ba0a-9e3f-4ffd-ba0b-3cf8009a6df9)

**Comment by seeksdream** [comment]
目前不能的，因为当前的线条其实没有长度这个属性，它只是将两个点连接起来，长度完全取决于节点之间的距离。
所以没法设置线条的长度。
