### ISSUE TITLE
removeLinkById方法调用没有作用

### ISSUE THREAD

**Issue by Haoz03** [seeksdream/relation-graph#314]

**Comment by seeksdream** [comment]
removeLinkById这个方法不建议使用，因为这是一个内部方法被暴露出来了，因为removeLinkById方法要求传递的id其实是link.seeks_id这个属性，这是一个不看源代码都不知道怎么去调用的一个方法。

你可以使用removeLink来删除连个节点之间的关联，就像这样：
`
    onDeleteLine(line, link) { // remove line
      console.log('onDeleteLine');
      const graphInstance = this.$refs.graphRef.getInstance();
      graphInstance.removeLine(link, line);
    },
    onDeleteLink(line, link) { // remove link
      console.log('onDeleteLink');
      const graphInstance = this.$refs.graphRef.getInstance();
      graphInstance.removeLink(link);
    },
`
而这个link对象可以通过点击事件或右键事件获取到：
`
<RelationGraph
        ref="graphRef"
        :options="graphOptions"
        :on-line-click="onLineClick" />

    onLineClick(line, link, $event) {
      console.log('onLineClick:', line, link);
    }
`
