### ISSUE TITLE
demo中的右键，点击相同类型的节点，右键菜单的位置无编号

### ISSUE THREAD

**Issue by zhangsai521314** [seeksdream/relation-graph#318]
demo地址：https://relation-graph.com/#/demo/vue3?id=gee-diagram-editing-tool
问一下是不是demo问题，不是框架的的问题？

Uploading 2024-06-04_10-26-45.mp4…

**Comment by zhangsai521314** [comment]
点击位置对比图：
![1](https://github.com/seeksdream/relation-graph/assets/14134256/747f2e86-77c1-41f6-a091-17ea3afc4edf)
![2](https://github.com/seeksdream/relation-graph/assets/14134256/7bcffecd-201e-4c06-a284-0d1db6a22eae)

**Comment by seeksdream** [comment]
这是怎么操作的呢？我这试了一下没重现这个问题，方便的话可以加我qq告诉我操作步骤非常感谢：3235808353

这个示例是企业会员示例，所有遇到的问题都可以通过沟通解决的。

**Comment by zhangsai521314** [comment]
> 这是怎么操作的呢？我这试了一下没重现这个问题，方便的话可以加我qq告诉我操作步骤非常感谢：3235808353
> 
> 这个示例是企业会员示例，所有遇到的问题都可以通过沟通解决的。

![图片](https://github.com/seeksdream/relation-graph/assets/14134256/444fcf9e-fc50-4d00-8acc-3850638bf20a)
我就是用火狐浏览器的这个版本，直接打开页面右键点击不同的节点
