### ISSUE TITLE
为结点和它下方的子结点添加外框并可以编辑这个区域的标题

### ISSUE THREAD

**Issue by goodnighteveryone** [seeksdream/relation-graph#321]
![image](https://github.com/seeksdream/relation-graph/assets/49894559/499853c7-f68d-4c87-93ca-16d3fb9accd9)
如图所示，目前好像没有api可以做到这样的效果

**Comment by seeksdream** [comment]
这个功能可以实现，但是会复杂一些，你可以尝试一下：
1，通过画布插槽在画布中定义一个区域，你可以将这个区域显示为原型、正方形、或者任何形状。
2，编写一个规则，根据你的需求，让区域能与一个或者多个节点对应起来。
3，编写一个方法，根据一个区域对应的节点，获取这些节点的坐标，再根据这些坐标调整区域的大小、位置，让这个区域看起来像是能将这些节点包围起来。
4，在初始展示后、节点被拖动后、在有新节点被添加进来后等等可能导致节点位置发生变化的情况时，重新调用步骤3中的方法。
