### ISSUE TITLE
反馈一个bug，就是这个图的其他树节点收缩按钮丢失

### ISSUE THREAD

**Issue by zmk66** [seeksdream/relation-graph#323]
<img width="1065" alt="7b25fd87a48758271c56284a142f20cb" src="https://github.com/seeksdream/relation-graph/assets/93029910/cefdbde7-8be5-46be-bfe8-10dd24675206">

bug复现：
多个关系网2， option增加这两个配置
'defaultExpandHolderPosition': 'right',
reLayoutWhenExpandedOrCollapsed: true,

**Comment by seeksdream** [comment]
这是一个Bug，下个版本(2.2.2)会修复，下个版本本周内会发布。
