### ISSUE TITLE
Unable to find element in cloned iframe

### ISSUE THREAD

**Issue by Halecoder** [seeksdream/relation-graph#327]
```js
const getThumbnail = async () => {
  const graphInstance = graphRef.value!.getInstance();
  const thumbnail = await graphInstance.getImageBase64();
  return thumbnail;
};
```
获取base64为空，我在vue3的onBeforeUnmount钩子调用

**Comment by seeksdream** [comment]
```
<a>
  <b>
  </b>
</a>
```
按道理是这样的：
a.onBeforeUnmount
b.onBeforeUnmount
但a.onBeforeUnmount使用了异步函数，vue并不会等这些异步函数被执行完了才卸载b，也就是说getThumbnail方法还没开始执行图谱组件就已经被卸载了。
而你的a.onBeforeUnmount中的截图功能需要使用到b的dom，所以肯定是不行的。

加上截图是一个耗时的操作，所以想要实现在退出时获取最新截图的功能，这样简单的处理思路可能是不行的。
