### ISSUE TITLE
line插槽获取relationGraph为空

### ISSUE THREAD

**Issue by Halecoder** [seeksdream/relation-graph#328]
![image](https://github.com/seeksdream/relation-graph/assets/75030331/af9e5769-4bed-48f0-a0b9-8a4842b53ccd)

用的官网实例
https://www.relation-graph.com/#/demo/vue3?id=adv-line-slot

**Comment by seeksdream** [comment]
这个示例很老了（只不过因为这里根本没用到老的传参方式的relationGraph，所以也没更新代码）。
新的方式都是通过依赖注入的方式来获取graphInstance的：
```
...
inject: ['graph', 'graphInstance'],
...
computed: {
    ...
    relationGraph() {
      return this.graphInstance();
    }
}
```
参考这个示例：
https://www.relation-graph.com/#/demo/vue2?id=adv-line-slot2
