### ISSUE TITLE
如何设置树状图的初始布局居中？

### ISSUE THREAD

**Issue by xdlStrive** [seeksdream/relation-graph#33]
现在初始化时是这样的
![image](https://user-images.githubusercontent.com/26785115/119835750-af498380-bf33-11eb-85fa-09a79db90156.png)
但我希望所有节点能够自动居中，排列整齐
![image](https://user-images.githubusercontent.com/26785115/119835930-e029b880-bf33-11eb-959f-0d9995a0a80f.png)
大致是变成这样
另外还想请问下，树状图层级之间的间距可以设置吗？比如我希望两层之间可以更加紧凑一些

**Comment by seeksdream** [comment]
您好，这个问题在最新版v2.x中已经修正

你可以通过在线工具来设置一些数据试试

https://seeksdream.github.io/#/options-tools
