### ISSUE TITLE
isHide 有办法支持 仅隐藏节点本身，相关边不受到影响 吗?

### ISSUE THREAD

**Issue by xuanergg** [seeksdream/relation-graph#332]
Existing Component
否

Component Name
ishide
是否隐藏这个节点，隐藏节点的同时，子节点也会被隐藏

Description
仅隐藏节点本身，相关边不受到影响

**Comment by Halecoder** [comment]
你可以试试更改透明度？

**Comment by seeksdream** [comment]
你可以试着修改节点的透明度。但节点依然是可以被点击的，可被选中的。
如果你介意被点击，你可以为节点设置className（比如node.className = 'my-hide'），然后通过样式穿透设置:
```
.my-hide {
    pointer-events: none;
}
```
这样，节点就变得不可见，也不可被点击了。

希望能解决你的问题。
