### ISSUE TITLE
vue2 版本，怎么删除某些节点

### ISSUE THREAD

**Issue by luchaoqun123** [seeksdream/relation-graph#339]
需求：在展示的时候，需要更新某个或者某些节点的内容. 现在有addNode 有没有类似updateNode({nodeId}, text || Html)

操作：
1. 直接拼接新的{"id":"1","text":"bbb"}   页面显示还是{"id":"1", "text":"aaa"}
2.removeNodeById  只能删除单个，会多次调用`this._dataUpdated()`,请问有删除多个节点的方法么

不管怎样非常感谢作者的付出，加油。编码人

**Comment by luchaoqun123** [comment]
removeNodeById

**Comment by seeksdream** [comment]
在vue2和vue3中，node节点的所有属性都是响应式的，直接修改即可。
在react中，也是直接修改节点属性就可以，修改完后可以调用graphInstance.dataUpdated()即可刷新视图。


removeNodeById被多次调用完全没有关系，_dataUpdated方法也是通过requestAnimationFrame来调用的，完全不需要担心效率问题的，可以放心大胆的在循环中调用。
