### ISSUE TITLE
有没有API文档可以参考呢

### ISSUE THREAD

**Issue by xiaohaiqing** [seeksdream/relation-graph#340]
VIP用户有没有API文档可以参考呢

**Comment by seeksdream** [comment]
所有使用者都可以通过以下方法查看API文档，VIP用户可以查看更多的在线示例，但没有额外的文档。

relation-graph中的全局配置、节点、线条的配置信息、常用方法在：
https://www.relation-graph.com/#/docs/graph
<img width="901" alt="image" src="https://github.com/user-attachments/assets/631913ac-e6a1-4cba-bbb6-92da56220668">

同时，relation-graph的实例接口API可以通过typescript声明文件查看：
https://www.relation-graph.com/#/docs/graph-instance-api
<img width="1020" alt="image" src="https://github.com/user-attachments/assets/a57890d0-7551-412d-99a1-61950e043dbf">
查看类型RelationGraphInstance的描述信息可以找到所有的接口方法，RelationGraphInstance继承了多个类的，这些类按照功能区分，比如RelationGraphWith2Data中包含了数据操作api，新增节点/线条，删除节点/线条的操作都包含在这里：
<img width="1473" alt="image" src="https://github.com/user-attachments/assets/90bbd424-39ab-4e0f-8552-6c5c16462475">

精力有限，这些接口方法只有少部分有注释，但好在这些方法都是中文直译的英文，一看就懂。

希望这些信息对你有用。
