### ISSUE TITLE
节点折叠异常

### ISSUE THREAD

**Issue by WindWilliam** [seeksdream/relation-graph#341]
### 2.2.2版本节点折叠异常
代码中引用的是**vue2版本**组件。
刚在本地切换依赖的版本，试验结果如下：
- `2.2.1`版本，可以正常进行折叠。
- `2.2.2`版本，父节点折叠时，子节点是隐藏的，但是子节点后续还有节点的话，仍旧显示，貌似是**最后一级节点，不能正常进行折叠**。

### 介绍页的细节问题
下面截图里，中英文对应关系错乱了。
![image](https://github.com/user-attachments/assets/dca1a62e-9739-40a2-8075-571f0b58b7d6)

**Comment by vajacn** [comment]
![树菜单问题](https://github.com/user-attachments/assets/6c86500b-dc05-4512-a368-c4522469c70a)
同样的问题，上级菜单关闭后，下级还在显示。

**Comment by vajacn** [comment]
最新版 2.2.3 已经修复这个问题了

**Comment by seeksdream** [comment]
#342   fixed
