### ISSUE TITLE
多层级的时候，子层级节点堆叠在一起

### ISSUE THREAD

**Issue by MgGaHui** [seeksdream/relation-graph#342]
vue2，
relation-graph: 2.2.2 ，
![0183768635f71b08d57f38043a12914e](https://github.com/user-attachments/assets/68938c1e-dc86-4d86-a8f7-12daed0db127)

点级图中的加号（展开节点），能看到堆叠的块，回归正确的位置，未展开的节点依旧全部重合在一起

**Comment by seeksdream** [comment]
这是2.2.2这个版本的bug
你升级到2.2.3应该就好了。你试试，如果还是不行你可以重新打开这个问题或者qq联系我：3235808353
