### ISSUE TITLE
2.2.2版本线条指向箭头位置展示不正确

### ISSUE THREAD

**Issue by lichengze520** [seeksdream/relation-graph#343]
![f6dfb705f490ede73a77175f2b45f732](https://github.com/user-attachments/assets/a74dc36a-8dee-4645-97ad-71e1ead858a2)
亲测：2.1.25固定版崩可以正常显示，升级到最新^2.2.2，^2.1.25均不行

**Comment by seeksdream** [comment]
好的，以后版本会修正这个问题。
当前，你可以自行调整一下这些选项就可以了：
<img width="1189" alt="image" src="https://github.com/user-attachments/assets/e901deec-38c8-44cc-9507-bc531e6198cd">
对应配置中的：
<img width="960" alt="image" src="https://github.com/user-attachments/assets/2a1a470e-f715-4c0e-b26b-bf6e913f9f9c">
