### ISSUE TITLE
动态增加节点后，节点重合

### ISSUE THREAD

**Issue by xiaohaiqing** [seeksdream/relation-graph#347]
我是这样添加的，请问有解决方式吗？
已添加：placeOtherGroup: true，还是不行

 _graphInstance.addNodes(nodes);
      setTimeout(() => {
        _graphInstance.startAutoLayout();
        _graphInstance.refresh()
        _graphInstance.moveToCenter();
        _graphInstance.zoomToFit();
      }, 500);

![image](https://github.com/user-attachments/assets/c7183aa2-e4b8-489b-8a57-4ac20054d01a)

**Comment by seeksdream** [comment]
如果你使用force布局，有多个关系网络，目前常规方式无法对主关系网（与根节点有直接或者间接关系的节点组成的网）以外的内容进行布局.
常规方式指：
```
      // 新增节点数据
      graphInstance.addNodes(__graph_json_data.nodes);
      // 新增线条数据
      graphInstance.addLines(__graph_json_data.lines);
      // 重新布局，根据最新的节点和关系，为所有节点分配位置
      // await graphInstance.doLayout();
```
如果是力学布局，你需要额外处理下：
```
      // 新增节点数据
      graphInstance.addNodes(__graph_json_data.nodes);
      // 新增线条数据
      graphInstance.addLines(__graph_json_data.lines);
      // 如果是force布局
      await graphInstance.layouter.placeNodes(graphInstance.graphData.nodes, graphInstance.graphData.rootNode);
```

下个版本（2.2.4）会自动处理这些差异，让所有布局都可以通过doLayout方法完成操作，无需特殊处理。
