### ISSUE TITLE
示例：https://relation-graph.com/#/demos 点击跳转404

### ISSUE THREAD

**Issue by MayWu91** [seeksdream/relation-graph#348]
https://relation-graph.com/#/docs/about 页面，点击「示例：https://relation-graph.com/#/demos」跳转示例页面404

![20240730-191454](https://github.com/user-attachments/assets/a7cbb70e-39fa-4fd3-ad08-d057669c6cd4)
![screenshot-20240730-191524](https://github.com/user-attachments/assets/a5ec1d90-e0fa-4e54-b655-b86c95e005cf)

**Comment by seeksdream** [comment]
非常感谢反馈，现在已修改。
