### ISSUE TITLE
官方示例本地服务启动拖拽节点很卡

### ISSUE THREAD

**Issue by corki-y** [seeksdream/relation-graph#349]
- 配置信息
1、chrome 浏览器 版本 127.0.6533.72（正式版本） (arm64)
2、框架 vite(5.0.0) + react(18.2.0)
3、relation-graph-react 2.2.3
4、node v18.20.3
-描述
1、拷贝官网 [react 代码](https://www.relation-graph.com/#/demo/react?id=simple)
1、启动服务用 chrome 打开
2、不打开 console，拖拽节点很流畅
3、打开 console ，拖拽节点非常卡顿
4、关闭 console ，拖拽节点很流畅

Uploading 录屏2024-07-30 19.29.14 - Compressed with FlexClip.mp4…

**Comment by corki-y** [comment]
https://github.com/user-attachments/assets/3f278c7c-2131-40db-a9f8-9fccbaa42079

**Comment by seeksdream** [comment]
这个我也不太清楚是什么情况，我知道有的程序会判断是否开启了【开发者工具】，如果是会运行一些额外的无意义的消耗性能的代码，以阻止对网页进行调试。我只能确定relation-graph肯定没有这样的机制。

给你一个建议：
你用你的浏览器，打开relation-graph.com上这个示例，且打开【开发者工具】，看看是否也存在也很卡，如果不卡，那你就需要找一下其他原因了。如果还是很卡，你可以联系我的QQ: 3235808353
