### ISSUE TITLE
有没有类似于把几个node围起来这种combo，或者可以实现类似效果吗

### ISSUE THREAD

**Issue by zhou94** [seeksdream/relation-graph#351]

**Comment by vajacn** [comment]
同样有次需求，希望能增加

**Comment by zhangwen-ui** [comment]
同求

**Comment by seeksdream** [comment]
示例即将发布：
https://www.relation-graph.com/#/demo/vue2?id=NodeGroupAreaDemo
https://www.relation-graph.com/#/demo/vue2?id=NodeGroupEffect

由于暂时不能在线看示例源代码，示例源代码放这里：
[NodeGroupEffect.zip](https://github.com/user-attachments/files/17002776/NodeGroupEffect.zip)
