### ISSUE TITLE
uniapp使用relation-graph

### ISSUE THREAD

**Issue by Forgmt** [seeksdream/relation-graph#353]
uniapp使用当前组件直接报错，页面无法出来

**Comment by seeksdream** [comment]
你可能遇到了环境或配置问题，不过你给的信息不足，无法告诉你怎么处理。

我确定的是uniapp中可以使用，vue2版本或者vue3版本都可以，有不少朋友在uniapp中使用。只是目前无法作为微信小程序运行而已。
