### ISSUE TITLE
当出现多个点指向一个结束点时（数据多时），会导致UI结构混乱，有什么办法能解决这个问题吗

### ISSUE THREAD

**Issue by scriptren** [seeksdream/relation-graph#354]
![Snipaste_2024-08-20_10-28-38](https://github.com/user-attachments/assets/a3b7016f-c3e7-4d8e-8704-a379d354cbf7)

当出现多个点指向一个结束点时（数据多时），会导致UI结构混乱，有什么办法能解决这个问题吗
![image](https://github.com/user-attachments/assets/71e6d25b-da1c-47c9-9fc0-b8f21ada38fb)

**Comment by seeksdream** [comment]
我想你肯定是指定了连接点位置为【左/右】，在这种情况下使用折线或者直线就是这样的效果。

你可以将线条类型换成曲线，line.lineShape=6（2,3,5,6,7都可以试试，看看哪个效果好一些）。
