### ISSUE TITLE
force布局下，line出现异常长度

### ISSUE THREAD

**Issue by MicahZJ** [seeksdream/relation-graph#362]
![1 QI0XT}GSB3USQ`N4T0_R](https://github.com/user-attachments/assets/fdba1b30-19f9-4666-91f7-e44d778b527a)

RGOptions配置如下

const graphOptions: RGOptions = {
  backgroundImageNoRepeat: false,
  moveToCenterWhenRefresh: false,
  defaultExpandHolderPosition: 'right',
  defaultNodeShape: 0, //0圆形 1矩形
  defaultLineShape: 4,
  // defaultNodeBorderWidth: 0,
  // defaultPolyLineRadius: 2 ,
  defaultNodeWidth: 60,
  defaultNodeHeight: 60,
  defaultLineColor: 'rgba(149, 210, 227, 1)',
  // defaultLineColor: 'rgb(29, 169, 245)',
  // defaultNodeColor: 'rgba(0, 206, 209, 0)' ,
  defaultNodeColor: 'transparent',
  // defaultNodeBorderColor: 'rgba(0, 206, 209, 1)',
  // defaultLineWidth: 2, //默认线条粗细
  defaultLineMarker: {
    markerWidth: 0,
    markerHeight: 0,
    refX: 0,
    refY: 0,
  },
  layouts: [
    {
      label: "Center",
      layoutName: "force",
      centerOffset_x: 0,
      centerOffset_y: 0,
      // distance_coefficient: 1,
      from: "left",
      levelDistance: "",
      // min_per_width:200, //节点之间横向距离最小值
      // max_per_width: 200, //节点之间横向距离最大值
      // min_per_height: 200, //节点之间纵向距离最小值
      // max_per_height: 200, //节点之间纵向距离最大值
      // maxLayoutTimes: 150,//最大布局次数
      force_node_repulsion: 1,//节点之间的斥力系数
      force_line_elastic: 1, //连线的牵引力系数
    },
  ]
};

**Comment by zheng1249938304** [comment]
我现在也是遇到。求大佬解答。
<img width="1618" alt="image" src="https://github.com/user-attachments/assets/532e4aef-f755-4740-ab84-2ea78db397e1">

**Comment by MicahZJ** [comment]
> 我现在也是遇到。求大佬解答。 <img alt="image" width="1618" src="https://private-user-images.githubusercontent.com/36907973/362101413-532e4aef-f755-4740-ab84-2ea78db397e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjYwMDQsIm5iZiI6MTcyNTUyNTcwNCwicGF0aCI6Ii8zNjkwNzk3My8zNjIxMDE0MTMtNTMyZTRhZWYtZjc1NS00NzQwLWFiODQtMmVhNzhkYjM5N2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA4NDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZmU4ZGYxZDFhZGM3ZDc2YjYyNmU5NjU5ZTY4NzcxYTA3ODgzNzg5ZTg2YmZlNDVhZjJkMmNjNzg2NmU1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8NrnWY5JHhfhQhamOgz7_7ZrhN5EgouqNw4K-4BlfAE">

我看别的评论说更新到最新版本有用，你试试吧，这个组件开发者好像忙着开发收费项目，issue好久不看了

**Comment by seeksdream** [comment]
你可以更新到2.2.5试试，如果还是不行，你可以联系我QQ: 3235808353，将你的数据发给我，我需要这些数据来复现这个问题。

**Comment by MicahZJ** [comment]
> 你可以更新到2.2.5试试，如果还是不行，你可以联系我QQ: 3235808353，将你的数据发给我，我需要这些数据来复现这个问题。

qq上早发过了，你一直没有回复
