### ISSUE TITLE
【bug】自动布局按钮，title文件

### ISSUE THREAD

**Issue by cuilingh00** [seeksdream/relation-graph#363]
![562BF359-FF53-4950-BFF9-F437DE0DC597](https://github.com/user-attachments/assets/116d88d8-46b1-4434-ae8d-497166946a10)
如图

**Comment by nanarino** [comment]
呢issue可能同 https://github.com/seeksdream/relation-graph/issues/355 重複

**Comment by seeksdream** [comment]
此问题在relation-graph-react@2.2.5中已修复
