### ISSUE TITLE
初始化加载关系重叠

### ISSUE THREAD

**Issue by lichengze520** [seeksdream/relation-graph#364]
数据准备：
 const __graph_json_data = {
        rootId: "a",
        nodes: [
           { id: 'a', text: 'IP'},
           { id: 'b', text: 'IP'},
           { id: 'c', text: 'IP'},
           { id: 'e', text: 'IP'}
         ],
         lines: [
           { from: 'a', to: 'b', text: '关系1',},
           { from: 'b', to: 'c', text: '关系2' },
           { from: 'c', to: 'e', text: '关系3' },
           { from: 'e', to: 'a', text: '关系4' }
         ]
      }：
  异常结果：![image](https://github.com/user-attachments/assets/d3bc9fa3-d8fb-49fa-bd94-50c8014fce0b)
  期望结果：![image](https://github.com/user-attachments/assets/1703d940-4668-468d-9145-9d90c983e8b4)
  期望初始化加载结果关系显示不重合

**Comment by disappointao** [comment]
我也遇到了，中心布局是有这个问题，你把布局切换成力学布局就好了

**Comment by lichengze520** [comment]
force布局也有这个问题，上面的数据，也有问题；

**Comment by disappointao** [comment]
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/4c3da5e7-834e-45d1-8c9b-f1b058860508"> force 布局 用的你的数据，效果能接受

**Comment by lichengze520** [comment]
谢谢，用force可以，不会重叠了

**Comment by seeksdream** [comment]
> 谢谢，用force可以，不会重叠了 但是下面这种数据又会有新问题
> 
> 1. 数据
>    `jsonData = { rootId: 'aip', nodes: [ { id: 'aip', text: 'IP' }, { id: 'a1', text: '攻击' }, { id: 'vip1', text: 'IP' }, { id: 'a2', text: '攻击' }, { id: 'vip2', text: 'IP' }, { id: 'a3', text: '攻击' }, { id: 'vip3', text: 'IP' } ], lines: [ { from: 'aip', to: 'a1', text: '关系1' }, { from: 'a1', to: 'vip1', text: '关系2' }, { from: 'vip1', to: 'a2', text: '关系3' }, { from: 'a2', to: 'vip2', text: '关系4' }, { from: 'vip2', to: 'a3', text: '关系5' }, { from: 'a3', to: 'vip3', text: '关系6' } ] }`
>    2.结果截图
>    异常结果，未居中，并展示不全
>    ![image](https://private-user-images.githubusercontent.com/48404648/364606160-0e384cb1-b4b5-4a0a-919a-631906bde650.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMTY1ODIsIm5iZiI6MTcyNjMxNjI4MiwicGF0aCI6Ii80ODQwNDY0OC8zNjQ2MDYxNjAtMGUzODRjYjEtYjRiNS00YTBhLTkxOWEtNjMxOTA2YmRlNjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDEyMTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZjczMTU4NDU3ZWM2NzI3YmJjNGZhMDViNzlhNTc5YzYyMDIyODE4NzIyM2Y4MmEzOGI5ZjU1YTI5ODg1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gw8ftWHMOn_TAIaSXqbNMxEfEM-TwQvj6qKiTQj8Mjs)
>    希望结果，能居中展示
>    ![image](https://private-user-images.githubusercontent.com/48404648/364606735-465fa338-e075-460c-bacd-f7cc70618328.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMTY1ODIsIm5iZiI6MTcyNjMxNjI4MiwicGF0aCI6Ii80ODQwNDY0OC8zNjQ2MDY3MzUtNDY1ZmEzMzgtZTA3NS00NjBjLWJhY2QtZjdjYzcwNjE4MzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDEyMTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MTZhOTAwMTA3MzU5MGRiZDg4OGI3MmE0MThlN2IxZTE4ZmVkMGRjNmNiMTY5N2VkODQ1YjQ4NjRmMWMwNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0MurOy0AW0mJpy17nhtyi8wIiyUDbZvXYErR8C5xk4A)
>    备注：目前使用2.2.4版本

力学布局是基于中心布局的基础上开始力导，像你图中的数据，很容易继续保持一条直线的同时达到力学平衡；

你可以更新到2.2.5，然后在力学布局中使用这个新的属性，可以解决你的问题：
fastStart：true（使用这个属性后，布局器会现将所有节点随机分配位置，然后开始力导）
<img width="727" alt="image" src="https://github.com/user-attachments/assets/fd40c0f6-cb6a-49f0-bac4-2803b096ff4a">

你试试
