### ISSUE TITLE
下载图片线条错乱

### ISSUE THREAD

**Issue by xiaohaiqing** [seeksdream/relation-graph#365]
下载图片后，线条都错乱了，请问这个如何解决？
![image](https://github.com/user-attachments/assets/fc9eff92-8a6e-425c-873b-e920d438dbcf)

**Comment by seeksdream** [comment]
你可以联系我的QQ: 3235808353
提供你的浏览器版本、relation-graph版本、以及你的程序，我看能不能复现这个问题。
