### ISSUE TITLE
非常规数据排版有问题， 我直接复制官网代码运行还是错乱

### ISSUE THREAD

**Issue by zheng1249938304** [seeksdream/relation-graph#366]
官网的案例：
<img width="1834" alt="image" src="https://github.com/user-attachments/assets/de8316fc-947e-4d76-8417-1d601d18c0db">
但是我直接复制运行后效果如下，没有任何改动， 直接新建的vue3项目，然后直接copy跑。
<img width="1630" alt="image" src="https://github.com/user-attachments/assets/94d7d2c3-e88c-4d18-bb69-dab4eb619241">

求问下， 是因为版本问题吗。 还是....

**Comment by vajacn** [comment]
这个应该是最新版本 2.2.3 的问题，如果使用 2.2.1 版应该可以，和我之前提的问题类似 #352

**Comment by vajacn** [comment]
2.2.4 版本好像修复了这个问题，更新后试试看

**Comment by seeksdream** [comment]
这个是2.2.3的一个bug，你更新到2.2.4或者最新版2.2.5试试
