### ISSUE TITLE
HTML元素 & 节点内容连接点位置可以设置为border吗？目前测试只能连接到左右两边

### ISSUE THREAD

**Issue by YunMouWeb** [seeksdream/relation-graph#367]
HTML元素 & 节点内容连接点位置可以设置为border吗？目前测试只能连接到左右两边

**Comment by seeksdream** [comment]
你可以通过设置这两个属性来定义线条（普通线条、HTML元素连线都适用）的连接点位置
// 可选值：border/left/top/right/bottom/lr/tb
line.fromJunctionPoint = 'border' 
line.toJunctionPoint = 'border'
