### ISSUE TITLE
引入报错：import {     RGEditingController 等其他的 } from 'relation-graph';

### ISSUE THREAD

**Issue by zhangwen-ui** [seeksdream/relation-graph#368]
batch-operations-on-nodes.vue:41  Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/relation-graph.js?v=85dd7092' does not provide an export named 'RGEditingController' (at batch-operations-on-nodes.vue:41:1)

**Comment by seeksdream** [comment]
可能是你的环境有一些问题，因为我确定是可以通过这种方式使用的，包括很多朋友也通过这种方式在使用RGEditingController等内置组件。

你可以这样试试：
先下载一个以下完整的项目，然后在这些项目中运行示例代码试试。

完整的、可运行的示例vue2项目： 
https://github.com/seeksdream/relation-graph-vue2-demo
完整的、可运行的示例vue3项目(Typescript)： 
https://github.com/seeksdream/relation-graph-vue3-demo
完整的、可运行的示例React项目(Typescript)： 
https://github.com/seeksdream/relation-graph-react-demo

如果运行成功，你可以对比项目的配置差异。

如果还是不行，你可以将一个小型的，能复现这个问题的项目发给我，我的QQ: 3235808353
