### ISSUE TITLE
节点展开/收起 可以不考虑 虚线么，是否有配置项？

### ISSUE THREAD

**Issue by smartwower** [seeksdream/relation-graph#369]
![Uploading 哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈.png…]()

**Comment by seeksdream** [comment]
有一个属性：line.forDisplayOnly = true，这个属性默认是flase,设置为true时，这条线仅仅用于展示，不会用于上下级关系计算，在力学布局中也不会有牵引力。
你可以试试，将你说的虚线的这个属性设置为true
