### ISSUE TITLE
relation-graph插件在火狐浏览器显示异常

### ISSUE THREAD

**Issue by shangqi123** [seeksdream/relation-graph#37]
被选中的元素，旋转90度，并且位置有偏移
![image](https://user-images.githubusercontent.com/18298364/121988975-e4782180-cdcd-11eb-806a-1dfa6aaf66d8.png)
异常显示
![image](https://user-images.githubusercontent.com/18298364/121989016-f8bc1e80-cdcd-11eb-8da7-57651282bd5d.png)
正常显示

**Comment by Endless520** [comment]
样式里加上

<style scoped>
>>>.rel-node {
  transform: none;
}
</style>

**Comment by shangqi123** [comment]
<style scoped> .rel-node { transform: none; } </style>   
实测可以，感觉楼上

**Comment by shangqi123** [comment]
> 样式里加上
> 
> <style scoped> >>>.rel-node { transform: none; } </style>

实测可以，感谢感谢

**Comment by seeksdream** [comment]
现在v2已修复
