### ISSUE TITLE
连线文字是否可以设置显示和隐藏,还有文字的大小和位置可以考虑自定义?

### ISSUE THREAD

**Issue by 1433847925** [seeksdream/relation-graph#370]

**Comment by seeksdream** [comment]
1，连线文字可以通过样式穿透设置隐藏，如：
<div class="my-graph">
    <RelationGraph ........></RelationGraph>
</div>

<style>
::v-deep(.my-graph) {
    .relation-graph {
        .c-rg-line-text {
              display:none;
        }
    }
}
</style>
2，文字大小同理，可以用如上方法设变文字大小；
3，文字的位置可以通过线条文字偏移（line.textOffset_x和line.textOffset_y）来调整位置；或者通过全局线条设置options.defaultLineTextOffset_x和options.defaultLineTextOffset_y来调整位置；
参考示例：
https://www.relation-graph.com/#/demo/vue3?id=line-text-position
