### ISSUE TITLE
relation-graph 基于背景图 进行拖拽指定的不同点位

### ISSUE THREAD

**Issue by EThan-Jam** [seeksdream/relation-graph#371]
作者大佬您好，请问一下例如关系图中，有个背景图，在此背景图上加载 relation-graph，背景图中有标注 A\B\C\D 四个点位，若我把relation-graph 中的关系点分别拖拽到A\B\C\D点位后，下次打开还是 拖拽过后的点位吗？

**Comment by seeksdream** [comment]
这需要你在拖拽完成后通过graphInstance.getGraphJsonData()方法来将数据保存到服务器端，这些数据中的节点信息包含了你拖拽后的坐标。
在你再次打开时，需要从服务器端加载这些包含了节点坐标的数据，设置RelationGraph使用fixed布局，然后将这些数据交给setJsonData方法。
这样你就可以实现你要的效果了，你可以参考示例：
https://www.relation-graph.com/#/demo/vue3?id=my-graph-app
