### ISSUE TITLE
大佬！力导布局这种数据层级怎么可以美观一点的展示，所有的第二层节点 都同时指向了第三层节点,，大佬空了帮忙看看！

### ISSUE THREAD

**Issue by Ruizhongli1** [seeksdream/relation-graph#372]
![问题1](https://github.com/user-attachments/assets/64c42e45-5dd6-4d4c-83fb-e160077d0ab6)
我也没办法，后端说他的数据只能这样，我感觉很不合理 🤦‍

**Comment by seeksdream** [comment]
这个没有办法，除非根据数据的业务含义做具体的建议。
比如这个示例中的数据，如果用这个图中的展示方式，也会乱做一团：
https://www.relation-graph.com/#/demo/vue2?id=mix-layout-2
但如果根据数据的业务含义做分析，以示例中的展示方式来看，就很清晰合理。
