### ISSUE TITLE
导出图片，样式错乱，字体模糊，会出现黑块和半透明块

### ISSUE THREAD

**Issue by MgGaHui** [seeksdream/relation-graph#373]
使用自带的导出图片工具，出现“导出图片，样式错乱，会出现黑块和半透明块”问题
chrome 浏览器，
vue2，
relation-graph 2.2.3版本，
导出效果图
![1c35b37c7610c2b5623e6dee67212bc](https://github.com/user-attachments/assets/fe8bef07-18be-400d-adf9-8a74fdb8a76e)

**Comment by seeksdream** [comment]
图片导出是完全依赖html2canvas，在某些情况下的确会有问题，尤其是数据量比较大的时候吧。
要完全解决这个问题比较难，因为它好像也没什么规律。
如果导出图片这个功能很重要，必须要解决的话，可以考虑在后端渲染。这样，脱离了客户端的各种差异化，后端渲染可以稳定的生成有完全一致性的图片。
