### ISSUE TITLE
力学布局节点大小适应问题

### ISSUE THREAD

**Issue by DuskXi** [seeksdream/relation-graph#375]
目前我实验下来发现力学模型貌似是将node当作一个质点进行计算，如果在node的自定义插槽中放置了很多东西，就算修正了其width和height依然会出现很大的节点与其他节点的位置重合的问题

这个问题有可能解决吗？

**Comment by vbnew** [comment]
我也遇到同样的问题，但是目前只有设置 layout的 min_per_width和min_per_height，或者使用节点的偏移属性，这种做法不是很好用，而且打包过后容易出现样式紊乱问题，希望作者关注下

**Comment by seeksdream** [comment]
这是个好问题，目前默认的力学布局就是将node作为一个质点进行计算。
作为默认的基础算法，这里没有考虑节点的大小，因为考虑节点的大小还要考虑节点的形状，而节点是可以通过自定义插槽显示为任何形状。同时还要考虑性能问题，所以缩放中的确做了简化，目的是以最高效最稳定的方式运行于大部分使用场景。

如果你开发的时间预算足够，可以通过自定义力学布局，来实现你的具体业务需求：
https://www.relation-graph.com/#/demo/vue3?id=customer-layout-force
https://www.relation-graph.com/#/demo/vue2?id=circular-layout-force
https://www.relation-graph.com/#/demo/vue2?id=galaxy
如果你们想要节省时间，也可以考虑加入企业会员支持一些我们，我来帮你们实现：
https://www.relation-graph.com/#/demo/vue2?id=use-more-layout
