### ISSUE TITLE
图形化编辑界面，操作异常情况

### ISSUE THREAD

**Issue by lichengze520** [seeksdream/relation-graph#377]
选择节点类型，不小心点到了，被按下的节点在画布中显示不友好，建议可以拖动到画布时自动适配放在便于操作和查看的位置
![image](https://github.com/user-attachments/assets/957bc14f-ac98-40c8-8804-4a4628f5bcfc)

**Comment by seeksdream** [comment]
拖拽创建节点默认的逻辑非常简单：
1，鼠标按下时生成临时节点。
2，鼠标抬起时创建节点。
这个过程中并没有更多的限制。

如果你想要实现你的需求可以这样：
1，在onNodeCreate回调函数中，判断被创建节点的坐标如果距离左侧工具栏太近时、太靠近可见区域边缘时不执行emit('onMyContainerNodeCreateFinish', x, y, nodeTemplate);即可取消创建节点：
<img width="791" alt="image" src="https://github.com/user-attachments/assets/451b72f6-47c5-4997-a15b-72837f5ff1be">
2，如何判断节点距离左侧工具栏太近时、太靠近可见区域边缘，可以通过接口graphInstance.getCanvasPointByViewPoint来实现，具体在这里就不展开了。

通过上面的办法，你有足够大的自定义空间来实现各种复杂的需求。
