### ISSUE TITLE
版本号2.26无法支持在links线条的数组item里面使用isHide属性进行线条的隐藏修改。

### ISSUE THREAD

**Issue by fuyuneryi** [seeksdream/relation-graph#379]
通过 getLinks() 获取到的数据无法在遍历的时候使用isHide属性进行隐藏，但是在2.1版本这个属性是可以生效的。如果有新的隐藏线条的方法可以回复一下吗 谢谢

**Comment by seeksdream** [comment]
2.2的版本依然可以使用isHide=true来隐藏节点。
getLinks()获取到的对象是link,继续遍历link.relations可以获取到link下所有的线条，可以设置isHide属性。
Link和Line的区别:
<img width="1182" alt="image" src="https://github.com/user-attachments/assets/eb35ee10-c224-488e-95e2-7934196f219b">

https://www.relation-graph.com/#/docs/link
