### ISSUE TITLE
展开/关闭按钮 与 slot 的点击事件冲突

### ISSUE THREAD

**Issue by Endless520** [seeksdream/relation-graph#38]
存在展开按钮 无法触发右击菜单
![图片](https://user-images.githubusercontent.com/59154349/122152119-5bc3b900-ce93-11eb-824d-7358774e66ff.png)

不存在展开按钮
![图片](https://user-images.githubusercontent.com/59154349/122152345-b8bf6f00-ce93-11eb-85ee-55d91023cd52.png)

**Comment by seeksdream** [comment]
最新版v2.x已修正

可以看看这个例子，这个例子中展开/收缩按钮有在上方的，有在下方的，但都与节点事件互不影响：
https://seeksdream.github.io/#/demo/bothway-tree-faq
