### ISSUE TITLE
给他加一个antd的loading效果，然后调用focusNodeById方法，会跳到顶部

### ISSUE THREAD

**Issue by 1768220906** [seeksdream/relation-graph#380]

**Comment by 1768220906** [comment]
好像是里面的那个handleSelect方法的scrollTo，这个scrollTo有什么作用吗

**Comment by seeksdream** [comment]
> 好像是里面的那个handleSelect方法的scrollTo，这个scrollTo有什么作用吗

跳到顶部是为了确保图谱能处于浏览器的可见范围，让focus的节点能展示在眼前。

不过这个的确很突兀，后续版本会去掉。如果需要这个效果，交给用户自己处理。


那么目前，你可以通过node.x和node.y获取节点的位置，让后通过graphInstance.setCanvasCenter(x,y)来让一个节点显示在中心，效果是一样的。但是没有动画效果，同时你需要自己处理缩放比例产生的影响（简单处理办法就是graphInstance.setZoom(100)让缩放比例变成100%，就可以一切正常）
