### ISSUE TITLE
只能限制最小缩放倍数不能限制最大缩放倍数的限制吗

### ISSUE THREAD

**Issue by vbnew** [seeksdream/relation-graph#382]
项目用的vue3+ts，没有找到限制最大缩放倍数的配置项

**Comment by seeksdream** [comment]
目前没有最大缩放倍数配置项。下个大版本（relation-graph@3.0  计划明年）会加入这个配置项。

目前可以通过事件来解决，

**通过自定义事件处理函数**，在处理函数中根据你们的业务需求来控制是否允许继续放大。
比如：1，在放大之前，通过graphInstance.getNodes()获取所有节点，根据额节点位置的分布发现当前只有3个节点，且已经有节点处于可见范围边缘，那么则阻止继续放大。
           2，直接根据当前的缩放比例判断，graphInstance.opitons.canvasZoom > 200，则组织继续缩放。

**通过自定义事件处理函数**目前是为企业会员开发的前瞻性功能，它几乎可以控制各个环节的默认事件，能实现右键拖拽画布、节点移动限制（限制仅横向或仅纵向，或者限制在某个区域）、滚轮移动画布（默认只能拖拽移动画布）等等功能，当然也包括缩放控制。如果需要，可以咨询企业会员服务，QQ:  3235808353。
