### ISSUE TITLE
多节点选择功能

### ISSUE THREAD

**Issue by luisgdf** [seeksdream/relation-graph#385]
如何实现多节点选择功能（例如：选择一个节点，然后选择另一个节点，这样两个节点都被选中——而不是取消选择第一个节点并选择第二个节点）？

**Comment by variliui** [comment]
在节点批量操作的章节里有节点多选相关的 https://relation-graph.com/#/demo/vue3?id=batch-operations-on-nodes

**Comment by seeksdream** [comment]
1，禁用掉默认节点选中状态（通过css样式穿透就可以取消掉选中的样式，点击后不显示边框投影）
2，通过onNodeClick事件，来设置节点的node.selected属性（或者任何自定义属性都可以，比如：node.data.myChecked），所以你可以自己定义当节点被点击时是要多选还是单选。
3，通过自定义节点插槽，根据你的属性判断节点是否被选中，如果是，让节点的样式显示为你想要的选中样式。
4，你可以自定义清理掉所有选中节点的选中状态的时机（比如点击画布空白处是清理，可以通过onCanvasClick事件），操作也很简单，通过graphInstance.getNodes()获取所有节点，循环，将选中节点的node.selected或者node.data.myChecked重置。

可供参考的示例：
https://www.relation-graph.com/#/demo/vue3?id=selections
适用于编辑器模式的多选：
https://www.relation-graph.com/#/demo/vue3?id=batch-operations-on-nodes
