### ISSUE TITLE
drag-to-create-toolbar

### ISSUE THREAD

**Issue by wjc1989** [seeksdream/relation-graph#386]
请问示例代码中的一些组件在哪里可以找到，比如
import DragToCreateToolbar from './drag-to-create-toolbar.vue'

**Comment by seeksdream** [comment]
源代码在这里(一个示例的源代码可能会有多个文件)：
<img width="1144" alt="image" src="https://github.com/user-attachments/assets/e2c29c03-f6ca-4524-bf91-60f62a9abc64">
