### ISSUE TITLE
工具欄敘述 更改語言成英文

### ISSUE THREAD

**Issue by Po-wei** [seeksdream/relation-graph#387]
![image](https://github.com/user-attachments/assets/2c2b4712-73ac-4843-84c4-acd02e3bfbce)

請問有支援更改工具欄的語言成英文嗎?

**Comment by HQ222222** [comment]
> ![image](https://private-user-images.githubusercontent.com/17596021/391167089-2c2b4712-73ac-4843-84c4-acd02e3bfbce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjM2NjcsIm5iZiI6MTczMzQ2MzM2NywicGF0aCI6Ii8xNzU5NjAyMS8zOTExNjcwODktMmMyYjQ3MTItNzNhYy00ODQzLTg0YzQtYWNkMDJlM2JmYmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA1MzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyN2IwYWVlZDVlYjUwNDhkNDQwODczMTc4OTEyZTNjNmVlNWY2ZDU5ZDgzZjZkNzY4ZTA4ZWUwMmQxZjYyMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4zkhO4dfF0ejo0uoiTdzOy0yvNJj2dA-hX5j29UWZyQ)
> 
> 請問有支援更改工具欄的語言成英文嗎?

可以使用 slot="tool-bar"插槽自定义工具栏，工具栏的功能有提供对应的api，getInstance()就能使用，css样式也可以直接使用rel-toolbar相关的，很方便

**Comment by seeksdream** [comment]
https://www.relation-graph.com/#/demo/vue3?id=toolbar-tooltips
你可以参考这个示例
