### ISSUE TITLE
vue2/relation-graph.mjs 在vue2.6.14版本下引入报错

### ISSUE THREAD

**Issue by cat-uncles** [seeksdream/relation-graph#392]
Module not found: Error: Invalid "exports" target "vue2/relation-graph.mjs" defined for "." in the package config E:\project\asean-gateway\node_modules\relation-graph\package.json, targets must start with "./"

**Comment by cat-uncles** [comment]
webpack5 vue-cli5

**Comment by seeksdream** [comment]
这个错误可能和你的项目具体配置有关，relation-graph不管是在vite还是在webpack下，都是可以正确运行的：
webpack完整的、可运行的项目示例：
https://github.com/seeksdream/relation-graph-webpack
vite完整的、可运行的项目示例：
https://github.com/seeksdream/relation-graph-vue2-demo

你试试，如果还是不行，你可以联系我的qq：3235808353，将你的项目（在可以重现这个问题的前提下，尽量只保留必要的文件）发给我。

**Comment by seeksdream** [comment]
如果必须使用.mjs 文件，但 Webpack 处理不正确，可以配置 Webpack：
`
configureWebpack: {
    module: {
      rules: [{
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto'
      }]
    } },
`
