### ISSUE TITLE
双向树

### ISSUE THREAD

**Issue by z346158847** [seeksdream/relation-graph#4]
双向树中，设置线  isReverse: false 或  true  对箭头无影响

**Comment by seeksdream** [comment]
isReverse这个属性是图谱内置属性，目前不能用于配置的，比如通过一个linkA->B生成了一条线A-B,同时又有一个link是B->A，那么第二个link会被标记成是reverse的。
后续我会开发一个新的布局，专门用于显示双向树，敬请期待

**Comment by seven777777** [comment]
> isReverse这个属性是图谱内置属性，目前不能用于配置的，比如通过一个linkA->B生成了一条线A-B,同时又有一个link是B->A，那么第二个link会被标记成是reverse的。
> 后续我会开发一个新的布局，专门用于显示双向树，敬请期待

现在有了么

**Comment by zhoufanglu** [comment]
看样子已经停止开发了。。 我也遇到了这样的问题

**Comment by seeksdream** [comment]
你好，新版 v2.0.4中已为线条新增起始箭头、终止箭头，这样可以通过from,to满足双向树的数据要求，同时可以根据起始和终止箭头设置满足线条的方向要求。
线条配置项说明文档：https://seeksdream.github.io/#/docs/link
示例：
https://seeksdream.github.io/#/demo/bothway-tree-faq

文字是否沿着连线路径走的可选项。
示例：
https://seeksdream.github.io/#/demo/lineAdv
