### ISSUE TITLE
多个子图时显示异常

### ISSUE THREAD

**Issue by GekiKaraa** [seeksdream/relation-graph#40]
在使用这个组件创建图谱时，当一张图中有两个互不连通的子图时，只有包含root节点的子图能够正常显示，其他的结点会全部重叠在左上角，如 1 to 2，3 to4 时，节点3和节点4会重叠，请问是否能通过设置多个Root节点，使用每一个root节点对应一个非联通子图的方式来解决？
![微信图片_20210628180133](https://user-images.githubusercontent.com/37804269/123618576-eb297e80-d83a-11eb-8095-66952503a133.png)

**Comment by wookpecker** [comment]
> 在使用这个组件创建图谱时，当一张图中有两个互不连通的子图时，只有包含root节点的子图能够正常显示，其他的结点会全部重叠在左上角，如 1 to 2，3 to4 时，节点3和节点4会重叠，请问是否能通过设置多个Root节点，使用每一个root节点对应一个非联通子图的方式来解决？ ![微信图片_20210628180133](https://user-images.githubusercontent.com/37804269/123618576-eb297e80-d83a-11eb-8095-66952503a133.png)

大佬，能问下你解决了吗，谢谢

**Comment by GekiKaraa** [comment]
> 

你好，目前我的解决方法是设置一个透明的根节点，需要设置多个root节点时将这些节点与透明根节点间使用透明的线连接，希望能帮到你

**Comment by GekiKaraa** [comment]
> > 在使用这个组件创建图谱时，当一张图中有两个互不连通的子图时，只有包含root节点的子图能够正常显示，其他的结点会全部重叠在左上角，如 1 to 2，3 to4 时，节点3和节点4会重叠，请问是否能通过设置多个Root节点，使用每一个root节点对应一个非联通子图的方式来解决？ ![微信图片_20210628180133](https://user-images.githubusercontent.com/37804269/123618576-eb297e80-d83a-11eb-8095-66952503a133.png)
> 
> 大佬，能问下你解决了吗，谢谢

你好，目前我的解决方法是设置一个透明的根节点，需要设置多个root节点时将这些节点与透明根节点间使用透明的线连接，希望能帮到你

**Comment by wookpecker** [comment]
> > > 在使用这个组件创建图谱时，当一张图中有两个互不连通的子图时，只有包含root节点的子图能够正常显示，其他的结点会全部重叠在左上角，如 1 to 2，3 to4 时，节点3和节点4会重叠，请问是否能通过设置多个Root节点，使用每一个root节点对应一个非联通子图的方式来解决？ ![微信图片_20210628180133](https://user-images.githubusercontent.com/37804269/123618576-eb297e80-d83a-11eb-8095-66952503a133.png)
> > 
> > 
> > 大佬，能问下你解决了吗，谢谢
> 
> 你好，目前我的解决方法是设置一个透明的根节点，需要设置多个root节点时将这些节点与透明根节点间使用透明的线连接，希望能帮到你

好的，谢谢大佬

**Comment by a99463820** [comment]
大佬，请问如何解决的，可以更加细致的请教一下吗

**Comment by seeksdream** [comment]
您好，在v1中的确存在这个问题，主要是因为v1版本无法展示与根节点没有直接或间接关系的节点。
目前新版v2.x中这个问题已经解决，可以直接展示这些孤点。
示例：https://seeksdream.github.io/#/demo/line
