### ISSUE TITLE
自动布局force拖拽

### ISSUE THREAD

**Issue by userL0901** [seeksdream/relation-graph#43]
自动布局force拖拽，过几秒拖拽动画效果消失了，这个这么设置的呢

**Comment by mwh1209** [comment]
同问

**Comment by Leytton** [comment]
+1

**Comment by seeksdream** [comment]
force力学布局需要大量实时的计算，目前会默认自动布局300次，300次之后基本上就稳定了，所以就上限300次停止了。
如果想要一直力学布局，你可以设置个定时器，定时调用
（以下代码需要relation-graph v2.x下使用）
```
const graph = this.$refs.seeksRelationGraph.getInstance();
graph.doLayout();
```
频繁，多次的调用graph.doLayout();不会让图谱额外重复的布局，可以放心的在定时器中调用。
示例：
https://seeksdream.github.io/#/demo/adv-effect
在以上示例中点击按钮【给侯亮平加两个小弟】后会继续布局
