### ISSUE TITLE
node节点宽度设置 ，导致节点互相覆盖，没有间隔，间隔不是自动有的吗

### ISSUE THREAD

**Issue by HoroXu** [seeksdream/relation-graph#44]
![image](https://user-images.githubusercontent.com/23008872/128108521-423a86ae-8e07-4491-af3c-184c22e15ffe.png)

**Comment by seeksdream** [comment]
你可以通过调整柱状布局的配置【最小间隔距离】来让节点之间有间隔：
示例：
https://seeksdream.github.io/#/demo/tree-distance
