### ISSUE TITLE
树图如何初始自适应居中且自动调整Zoom使画布包含所有节点？

### ISSUE THREAD

**Issue by seven777777** [seeksdream/relation-graph#47]
使用时遇到一些问题想请教，如下：
1.如何设置根节点初始化是自动居中？
2.如何初始化时自适应zoom使画布包含所有节点？
3.子节点展开或收起点击时，为了使节点布局正常，使用refresh()总是会重置画布，有没有优化方案，使点击子节点时节点重绘但不改变当前位置？

**Comment by zhoufanglu** [comment]
12问题后面有解决方案吗？

**Comment by seeksdream** [comment]
你好，最新版v2.x可以实现自动居中，并自动缩放到可以显示所有节点（可配置）

问题3现在v2.x中是可以实现你的描述的效果的，你试试，如果不行你再找我
https://seeksdream.github.io/#/demo/tree-data
