### ISSUE TITLE
工具栏的全屏后，右键菜单和节点悬浮框层级有问题，都看不见

### ISSUE THREAD

**Issue by felicity23** [seeksdream/relation-graph#48]
案例中就有这个问题

**Comment by seeksdream** [comment]
之前的确存在这个问题
最新版v2.x的解决方案是：建议将右键菜单div放入图谱插槽中（slot=graph-plug）即可。
在全屏时指定要全屏的元素为图谱组件，而用户的自定义内容并不包含在图谱组件中。所以导致图谱全屏后那些右键菜单之类的无法显示

图谱插槽示例：
https://seeksdream.github.io/#/demo/adv-other-slot
