### ISSUE TITLE
npm install --save relation-graph

### ISSUE THREAD

**Issue by Yurui-Li** [seeksdream/relation-graph#5]
报错信息：
npm WARN saveError ENOENT: no such file or directory, open '/data/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/data/package.json'

**Comment by seeksdream** [comment]
这个看起来不像是在一个项目根目录执行了npm install --save命令，你需要在你的项目的根目录执行，如果是一个不包含package.json的项目或空项目，你得先执行npm init
