### ISSUE TITLE
提问：如何修改选中的线条的颜色

### ISSUE THREAD

**Issue by yonghengBao** [seeksdream/relation-graph#52]
如何修改选中的线条的颜色

**Comment by seeksdream** [comment]
使用最新版v2.x 在图谱选项中通过checkedLineColor来更改线条选中时的颜色。

你还可以通过在线工具尝试一下效果：
https://seeksdream.github.io/#/options-tools
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/40479975/210180615-684509f8-11a1-4173-8535-8559062f87d2.png">

**Comment by Rain20199** [comment]
失效了
