### ISSUE TITLE
当节点上有收缩展开功能后，节点详情悬浮窗鼠标移入移出事件不起作用，点击事件也不起作用

### ISSUE THREAD

**Issue by yalan-git** [seeksdream/relation-graph#54]
<SeeksRelationGraph
        ref="seeksRelationGraph"
        :options="graphOptions"
        :on-node-expand="onNodeExpand"
      >
        <div slot="node" slot-scope="{ node }">
          <div
            style="line-height: 98px; font-size: 16px"
            @click.stop="showNodeTips(node, $event)"
          >
            {{ node.text }}
          </div>
        </div>
      </SeeksRelationGraph>

**Comment by mwh1209** [comment]
我是换了一种思路去实现收缩展开

**Comment by yalan-git** [comment]
> 我是换了一种思路去实现成长
其实是他那个收缩展开那个按钮的覆盖在那个上面了，改下样式就可以点击了

**Comment by seeksdream** [comment]
最新版v2.x已修正

可以看看这个例子，这个例子中展开/收缩按钮有在上方的，有在下方的，但都与节点事件互不影响：
https://seeksdream.github.io/#/demo/bothway-tree-faq
