### ISSUE TITLE
 showSeeksGraph函数不能二次调用?

### ISSUE THREAD

**Issue by A-lie** [seeksdream/relation-graph#55]
watch: {
        props: {
            handler() {
                if (this.$refs.seeksRelationGraph) {
                    this.copyJson = this.props.configs[0].baseCfg.option
                    // this.$refs.seeksRelationGraph.setJsonData(this.copyJson, seeksRGGraph => {
                    //     console.log(1)
                    // })
                    // let self = this
                    // setTimeout(() => {
                    // self.showSeeksGraph()
                    // }, 100)
                }
            },
            deep: true,
        },
    },
    methods: {
        showSeeksGraph() {
            let __graph_json_data = this.props.configs[0].baseCfg.option
            this.$refs.seeksRelationGraph.setJsonData(__graph_json_data, (seeksRGGraph) => {
                // 这些写上当图谱初始化完成后需要执行的代码
                // console.log('seeksRGGraph',seeksRGGraph);
            })
        },
        onNodeClick(nodeObject, $event) {
            console.log('onNodeClick:', nodeObject)
        },
        onLineClick(lineObject, $event) {
            console.log('onLineClick:', lineObject)
        },
    },
watch里面再次调用会报"找不到from",graphData.rootNode没有数据

**Comment by mwh1209** [comment]
同问

**Comment by wtt0213** [comment]
我找到了解决方法，你需要修改原文件node_modules/relation-graph/dist/relation-graph.min.js，将5580行注释掉，这样可以重复加载一个已存在对象了

**Comment by Noctmiao** [comment]
我也遇到了这个问题，楼上的方法可以解决，谢谢。

**Comment by gy2986589** [comment]
> 我找到了解决方法，你需要修改原文件node_modules/relation-graph/dist/relation-graph.min.js，将5580行注释掉，这样可以重复加载一个已存在对象了

问一下 如果改了源码 重新install 会重新 覆盖 这个怎么解决

**Comment by seeksdream** [comment]
v1可能有一些问题
最新版v2可以无限次调用setOptions来更改图片选项配置。无限次调用setJsonData方法来更改图谱数据。
