### ISSUE TITLE
请问导出图片的名称如何设置，更换？

### ISSUE THREAD

**Issue by leson1986** [seeksdream/relation-graph#57]
如题，如果不能设置更换，建议新增此功能！

**Comment by seeksdream** [comment]
在当前最新版v2.0.2版本中，通过选项downloadImageFileName来设置
你可以使用在线工具体验一下：

https://seeksdream.github.io/#/options-tools

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/40479975/210131507-5aff5418-13b9-4bbd-8392-5bd3b27f2ad4.png">
