### ISSUE TITLE
打包后的relation-graph.min.js在ie10和ie11浏览器下不兼容，急急急！！！！

### ISSUE THREAD

**Issue by purpletastes** [seeksdream/relation-graph#59]
现象：
relation-graph.min.js里面仍然存在es6语法，比如箭头函数等
解决办法：
在根目录下添加.babelrc文件，并进行如下配置：
`{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
    ]
}
`
导致的问题：
版本不好管理，如果新拉的包就会覆盖掉上面兼容的文件
期望：
希望帮忙把这个兼容处理在源码中能够更新维护一下，谢谢！

**Comment by lb712** [comment]
请问如何配置IE呢，我现在也遇到了在IE上不能兼容的问题，能问你吗

**Comment by seeksdream** [comment]
你可以将relation-graph的源代码作为放入你的项目中，项目组件使用，跟随你的项目一期打包
