### ISSUE TITLE
   节点在没有关系的情况下会挤在一起，这个问题有解决的方法吗

### ISSUE THREAD

**Issue by gkc411493321** [seeksdream/relation-graph#61]
![SeeksRelationGraph-74847](https://user-images.githubusercontent.com/56286837/147622343-9e5513f4-8452-4db5-a2c3-b1f1bbef8081.png)

**Comment by gkc411493321** [comment]
> 请问这个问题解决了吗？

可以考虑获取可视区域中心点，以该点作为圆心，生成环形布局，手动计算各点的坐标

**Comment by wookpecker** [comment]
> > 请问这个问题解决了吗？
> 
> 可以考虑获取可视区域中心点，以该点作为圆心，生成环形布局，手动计算各点的坐标

大佬，能给下示例代码吗，谢谢

**Comment by wookpecker** [comment]
> 请问这个问题解决了吗？

大佬，能问下你解决了吗

**Comment by ShenGunJie** [comment]
> 请问这个问题解决了吗？

解决了吗

**Comment by a99463820** [comment]
tree布局下可以用这个方法么

**Comment by seeksdream** [comment]
目前v2版本已支持显示这些没有关系的孤点，示例：
https://seeksdream.github.io/#/demo/line
