### ISSUE TITLE
怎样修改连线上 显示的文字的样式。比如：添加背景图片或者加个背景色

### ISSUE THREAD

**Issue by zyq1221** [seeksdream/relation-graph#63]

**Comment by seeksdream** [comment]
目前v2版本中有连线插槽，但这个功能还没有文档开放出来，也没有示例，你可以看看源代码试着用一下
等连线插槽文档更新了再回复你

**Comment by zyq1221** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by seeksdream** [comment]
从v2.0.7开始， 新增连线插槽功能，以及相应的示例
连线插槽可以让你完全自定义连线的样式。
https://seeksdream.github.io/#/demo/adv-line-slot
