### ISSUE TITLE
连接线能自定义吗？比如说用图片

### ISSUE THREAD

**Issue by xiaoxian202** [seeksdream/relation-graph#64]

**Comment by seeksdream** [comment]
目前v2版本中有连线插槽，但这个功能还没有文档开放出来，也没有示例，你可以看看源代码试着用一下
等连线插槽文档更新了再回复你

**Comment by seeksdream** [comment]
从v2.0.7开始， 新增连线插槽功能，以及相应的示例
连线插槽可以让你完全自定义连线的样式。
https://seeksdream.github.io/#/demo/adv-line-slot
