### ISSUE TITLE
请问有连接线的鼠标移入移出事件吗？

### ISSUE THREAD

**Issue by forwardZhang** [seeksdream/relation-graph#65]
1.有连接线的输入移入移出事件吗？
2.在没有关系的情况下，所有node 会叠在一起，请问这个有办法控制吗？

**Comment by seeksdream** [comment]
**1.有连接线的输入移入移出事件吗？**
目前没有，只有连线的点击事件，目前来看这个需求不具有普遍性，但你可以将源代码放入自己的项目中，作为项目组件进行修改，也很容易实现
**2.在没有关系的情况下，所有node 会叠在一起，请问这个有办法控制吗？**
目前v2版本已支持显示孤点
