### ISSUE TITLE
vue3运行报错

### ISSUE THREAD

**Issue by yyyyffqqqq** [seeksdream/relation-graph#66]
不能支持vue3版本吗

**Comment by wo13182421766** [comment]
这个问题看了下，好像是在渲染的地方用的是 Vue2 写法。你后来有找到其他的组件吗

**Comment by wo13182421766** [comment]
我感觉这个组件其实蛮强大的，可惜不会用Vu3搞

**Comment by TAXIVAE** [comment]
有一种实现方案，图用vue2单独构建出一个项目打包成静态文件，在vue3通过iframe内嵌方法来调用图形页面

**Comment by TAXIVAE** [comment]
gitee有个作者做了vue3的适配，https://gitee.com/ghostgeek/vue-relation

**Comment by yyyyffqqqq** [comment]
最后用Echarts了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wo13182421766 ***@***.***&gt;
发送时间: 2022年6月19日 12:28
收件人: seeksdream/relation-graph ***@***.***&gt;
抄送: yyyyffqqqq ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [seeksdream/relation-graph] vue3运行报错 (Issue #66)





 
这个问题看了下，好像是在渲染的地方用的是 Vue2 写法。你后来有找到其他的组件吗

**Comment by seeksdream** [comment]
已发布，2023-02-19 最新版本v2.0.12起开始支持vue3

vue2使用方法： import RelationGraph from 'relation-graph'

vue3使用方法： import RelationGraph from 'relation-graph/vue3'

vue3完整小示例：https://github.com/seeksdream/relation-graph-vue3-demo
