### ISSUE TITLE
修改两个节点之间连接线的默认长度

### ISSUE THREAD

**Issue by AtroxEzerel** [seeksdream/relation-graph#67]
如何修改默认两个节点之间连接线的长度，如果一开始只有两个元素，那么他们之间的距离会非常近。

**Comment by pzheng98** [comment]
不知道

**Comment by seeksdream** [comment]
不同的布局都有调整连线长度（节点距离）的方法：


树状布局：
https://seeksdream.github.io/#/demo/tree-distance
中心布局：
https://seeksdream.github.io/#/demo/distance_coefficient
