### ISSUE TITLE
给节点动态添加expanded：false，节点并没有收起其子节点

### ISSUE THREAD

**Issue by wangaojiao1996** [seeksdream/relation-graph#68]
给节点动态添加expanded：false，节点并没有收起其子节点，只是把收起按钮的状态改变了，有什么方案解决吗

**Comment by niuyannet** [comment]
用show属性可以满足

**Comment by wangaojiao1996** [comment]
> 用show属性可以满足
谢谢，设置了子节点的isShow已经解决问题了

**Comment by seeksdream** [comment]
你好，v1版本实现这个需求确实很费劲。
现在的v2版本你可以这样做，可能会方便些：
`
const instance = this.$refs.graph.getInstance();
const node = instance.getNodeById();
instance.expandOrCollapseNode(node);
`
