### ISSUE TITLE
按了浏览器F12后，所有节点就不能拖动了

### ISSUE THREAD

**Issue by niuyannet** [seeksdream/relation-graph#69]
按了浏览器F12后，所有节点就不能拖动了

**Comment by niuyannet** [comment]
解决了，移动端不支持鼠标mousedown事件导致的

**Comment by seeksdream** [comment]
👍🏻，之前v1版本问题不少，代码也很乱，v2重构了代码，也对触摸屏有简单的支持，但还需完善，欢迎发送pull request，一起完善
