### ISSUE TITLE
展开放在右边时，右键菜单无效

### ISSUE THREAD

**Issue by pigpeak** [seeksdream/relation-graph#7]
展开放在右边时，右键菜单无效

**Comment by GCF15** [comment]
展开设置bottom也无效，left和top有效

**Comment by seeksdream** [comment]
最新版v2.x已修正

可以看看这个例子，这个例子中展开/收缩按钮有在上方的，有在下方的，但都与节点事件互不影响：
https://seeksdream.github.io/#/demo/bothway-tree-faq
