### ISSUE TITLE
移动端，拖动都失效了

### ISSUE THREAD

**Issue by niuyannet** [seeksdream/relation-graph#70]
移动端，页面拖动都失效了，放在手机和平板，感觉拖动都是有边界的感觉

**Comment by niuyannet** [comment]
解决了，移动端不支持鼠标mousedown事件导致的

**Comment by doudou-dream** [comment]
怎么解决的，我也遇到了在移动端用手拖拽没效果的问题

**Comment by TAXIVAE** [comment]
https://blog.csdn.net/xiuqing_/article/details/125722428

**Comment by niuyannet** [comment]
更完善的解决方案https://blog.csdn.net/u013003576/article/details/123523542?spm=1001.2014.3001.5501

**Comment by seeksdream** [comment]
您好，现在没有在触摸屏下做过测试。

今天发布的v2版本中简单支持了触摸屏。你可以试试

欢迎在发送pull request，共同开发，完善
