### ISSUE TITLE
设置为上下树，折折线样式的时候，两个节点的位置会出现偏移，不是直线展示

### ISSUE THREAD

**Issue by lanchuanglanyan** [seeksdream/relation-graph#71]
![image](https://user-images.githubusercontent.com/31338597/158730240-92398eb1-5cfb-4b55-8d31-1ce7a33ac14f.png)

**Comment by lanchuanglanyan** [comment]
@seeksdream 大佬，求助，我废了

**Comment by seeksdream** [comment]
您好，这个问题在今天发布的v2版本中已经解决
