### ISSUE TITLE
求助，生成的树状图，原始节点和子节点不是居中布局的

### ISSUE THREAD

**Issue by lanchuanglanyan** [seeksdream/relation-graph#72]
![image](https://user-images.githubusercontent.com/31338597/158926005-ac9239b4-f535-4a90-b747-ab0a583c0688.png)
@seeksdream 求大佬

**Comment by seeksdream** [comment]
您好，这个问题在v2版本中已经解决：
<img width="833" alt="image" src="https://user-images.githubusercontent.com/40479975/210127426-c10b7af8-503d-4896-ae9a-48ad933ff1b4.png">
