### ISSUE TITLE
求助，节点模块不是居中布局的，居左布局导致折线问题

### ISSUE THREAD

**Issue by lanchuanglanyan** [seeksdream/relation-graph#73]
![image](https://user-images.githubusercontent.com/31338597/158931259-aab284fa-f1c7-43ea-9be9-f038dbb6abaa.png)
@seeksdream 求大佬

**Comment by seeksdream** [comment]
您好，这个问题在新版本v2中已经解决：
<img width="833" alt="image" src="https://user-images.githubusercontent.com/40479975/210127405-921af4bf-d895-42e1-97be-6d7ed0218d77.png">
