### ISSUE TITLE
请问用了isShow默认收起节点后，展开后调刷新怎么才能保持用户缩放和位置不被刷新？

### ISSUE THREAD

**Issue by HGH666** [seeksdream/relation-graph#75]
按文档中案例默认收缩节点后，刷新会使得用户缩放和当前查看的位置都被重置。。。如果不掉刷新又会导致节点联线显示出问题，如何才能解决呢？如果可以的话最好节点的expanded属性能和子节点挂钩；当expanded为false时，自动隐藏子节点。

**Comment by seeksdream** [comment]
之前v1版本的确有这个问题，会在很多情形下重新刷新节点位置、画布位置、重置缩放比例。
目前v2版本你再看看，目前是可以做到在展开/收缩后不重置位置、缩放比例的：
http://relation-graph.com/#/demo/tree-data

**Comment by seeksdream** [comment]
> 

https://seeksdream.github.io/#/demo/tree-data
