### ISSUE TITLE
[需求]希望支持图形化操作功能，建立节点之间的连线

### ISSUE THREAD

**Issue by kilosangma** [seeksdream/relation-graph#77]
类似于didi的logic-flow能以拖拽的方式建立节点之间的关系(连线link)

**Comment by onlyWjl** [comment]
我也在想这个问题，嗨嗨嗨

**Comment by seeksdream** [comment]
这个组件目前的主要作用是数据展示，数据编辑功能会弱一些，如果是纯工作流编辑需求可能不太合适。
你的建议我会考虑的，后续如果要支持，也是单独做一个其他项目来实现。
