### ISSUE TITLE
能不能加上对没有关系的节点进行铺开，都叠在一起，不好看。

### ISSUE THREAD

**Issue by cl87703648** [seeksdream/relation-graph#78]
不知道这个功能是否是存在的。

**Comment by ShenGunJie** [comment]
> 不知道这个功能是否是存在的。

你有实现这个功能吗？请教一下

**Comment by woshierha** [comment]
请问这个有解决方案吗

**Comment by woshierha** [comment]
> > 不知道这个功能是否是存在的。
> 
> 你有实现这个功能吗？请教一下

我用了个笨方法就是添加一个没有意义的节点 让他们都连到这个中心节点 然后让这个中心节点变透明

**Comment by seeksdream** [comment]
现在v2版本已经支持显示这些孤点，可以参考这个示例：
https://seeksdream.github.io/#/demo/line

**Comment by shijunshen** [comment]
这个只是显示了，但是还是堆叠在一起的呀

**Comment by xxafei** [comment]
> > 不知道这个功能是否是存在的。
> 
> 你有实现这个功能吗？请教一下

ni你可以在绘制完成后加一句代码 refresh() 就可以让重叠的点自动展开

**Comment by xtthaop** [comment]
> > > 不知道这个功能是否是存在的。
> > 
> > 
> > 你有实现这个功能吗？请教一下
> 
> 我用了个笨方法就是添加一个没有意义的节点 让他们都连到这个中心节点 然后让这个中心节点变透明

我也是加了一个空节点把没有关联的都挂到那上面，整体会好一点
