### ISSUE TITLE
节点里面的text文字不显示

### ISSUE THREAD

**Issue by paobai** [seeksdream/relation-graph#8]
使用官方配置的demo也是这种情况，节点里面的文字不显示，
使用：
https://github.com/seeksdream/relation-graph/blob/master/doc/demo/Demo4TreeData.vue
的demo也是，图形其他都正常显示。就是node里面的文字是空的。
版本"relation-graph": "^1.1.0",
![image](https://user-images.githubusercontent.com/37954147/105123834-c4d91780-5b13-11eb-9fe3-7ba4ef84200c.png)
会是哪些情况啊？

**Comment by seeksdream** [comment]
你应该是使用低版本的vue，不过没关系，你可以通过插槽slot的方式来显示node节点的内容，我更建议使用slot的方式来显示节点内容，这样你自定义的空间更大。


http://relation-graph.com/#/demo/adv-slot


你可以参考这个例子使用插槽显示node节点内容






更多问题请加我qq，在git主页有我的qq，如果可以，顺便点个小星星。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: paobai <notifications@github.com&gt;
发送时间: 2021年1月20日 11:37
收件人: seeksdream/relation-graph <relation-graph@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[seeksdream/relation-graph] 节点里面的text文字不显示 (#8)

**Comment by paobai** [comment]
> 你应该是使用低版本的vue，不过没关系，你可以通过插槽slot的方式来显示node节点的内容，我更建议使用slot的方式来显示节点内容，这样你自定义的空间更大。 http://relation-graph.com/#/demo/adv-slot 你可以参考这个例子使用插槽显示node节点内容 更多问题请加我qq，在git主页有我的qq，如果可以，顺便点个小星星。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: paobai <notifications@github.com&gt; 发送时间: 2021年1月20日 11:37 收件人: seeksdream/relation-graph <relation-graph@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[seeksdream/relation-graph] 节点里面的text文字不显示 (#8)

感谢作者回复，通过slot的方式让我成功添加了文字。start我当然也点上了。请问vue版本应该多少以上，我的版本为2.5.16

**Comment by seeksdream** [comment]
可能2.6之前的版本都有这个问题？我没有用2.6之前的版本做过测试....

**Comment by gy2986589** [comment]
我是2.16.11版本 节点也不显示文字

**Comment by seeksdream** [comment]
> 

你可以qq联系我，我们再一起看看是啥原因。由于这个问题确实很久没人反馈了我先关闭了
