### ISSUE TITLE
ts引入报错

### ISSUE THREAD

**Issue by yunpeng6605** [seeksdream/relation-graph#80]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'version')
    at Proxy.created (relation-graph.min.js?0491:5081:1)

**Comment by seeksdream** [comment]
您好，由于之前的版本没有使用ts，我暂时没法判断问题原因。

不过我昨天新发布了v2版本，你试试v2是否还有这个问题。

接下来我会在vue3版本和react版本中使用ts开发，到时候我再回复你

**Comment by seeksdream** [comment]
现在vue3版本支持ts开发

2023-02-19 最新版本v2.0.12起开始支持vue3

vue2使用方法： import RelationGraph from 'relation-graph'

vue3使用方法： import RelationGraph from 'relation-graph/vue3'

vue3完整小示例：https://github.com/seeksdream/relation-graph-vue3-demo
