### ISSUE TITLE
作者都不维护了，慎用

### ISSUE THREAD

**Issue by ErricLu** [seeksdream/relation-graph#81]
看了下源码，慎用~~

**Comment by a99463820** [comment]
怎么说

**Comment by gy2986589** [comment]
？？？

**Comment by seeksdream** [comment]
抱歉，之前工作太忙，也很闹心，所以没怎么维护。

不过我想2023会是新的景象。我又开始维护了。

你看，在新年的第一天v2.x上线了。

而且会在近期上线支持vue3的relation-graph-vue3

会在项目1024 star时支持react的relation-graph-react

后续还会支持微信小程序

新的文档和在线配置工具：

http://relation-graph.com/ （国内用户，无需科学上网）

https://seeksdream.github.io/（For regions outside of China）
