### ISSUE TITLE
工具栏各种工具可单独控制显示隐藏，可设置默认比例

### ISSUE THREAD

**Issue by LEIHD** [seeksdream/relation-graph#82]
1、工具栏各种工具可单独控制显示隐藏，
2、可设置默认比例，
3、支持自定义工具样式，
4、搜索栏默认显示但是没找到搜索栏在哪儿？

**Comment by LEIHD** [comment]
数据量太大，显示卡顿，有什么解决方案吗？

**Comment by seeksdream** [comment]
**1、工具栏各种工具可单独控制显示隐藏，**
a:目前工具栏按钮基本上都支持显示设置，参考：https://seeksdream.github.io/#/docs/graph
也可以通过在线工具UI配置https://seeksdream.github.io/#/options-tools
<img width="498" alt="image" src="https://user-images.githubusercontent.com/40479975/210126000-5b5920f4-e8aa-4e09-a788-b20c7eec721c.png">

**2、可设置默认比例，**
目前v2.x支持图片在展示时自动缩放到合适大小（可配置）
如果要自定义比例可以这样：this.$refs.graph.getInstance().animateToZoom(finalZoom, time, callback);//finalZoom=100表示100%
**3、支持自定义工具样式，**
工具栏样式你可以使用/deep/样式穿透功能区修改
**4、搜索栏默认显示但是没找到搜索栏在哪儿？**
这个功能没有普遍性，去掉了。同时，不需要图谱提供也很容易做出来，回头我做个示例
