### ISSUE TITLE
没法展示单个节点自身的连接,比如a->a。

### ISSUE THREAD

**Issue by goodluck-yan** [seeksdream/relation-graph#83]
<img width="879" alt="微信截图_20220506140357" src="https://user-images.githubusercontent.com/44892486/167076455-78bf54c3-1c80-4f48-a021-275302ea97e8.png">

**Comment by better-pz** [comment]
自己写吧

**Comment by seeksdream** [comment]
抱歉这个暂时不支持，截止目前也没有其他人反馈过此需求。如果需要，你可以将源代码作为你的项目组件，自己实现一下
