### ISSUE TITLE
不编译的时候如何使用

### ISSUE THREAD

**Issue by AdorableGhost** [seeksdream/relation-graph#84]

**Comment by AdorableGhost** [comment]
直接  html 中引用 该怎么引入啊

**Comment by AtroxEzerel** [comment]
buzhichi

**Comment by seeksdream** [comment]
目前v2.x已支持cdn方式引用，请参考文档中的【二，通过CDN方式使用】

https://seeksdream.github.io/#/docs/start

或直接在线调试：https://codepen.io/seeksdream/pen/qByZYJg
