### ISSUE TITLE
自动布局与节点拖拽冲突

### ISSUE THREAD

**Issue by AtroxEzerel** [seeksdream/relation-graph#86]
当在自动布局模式下拖拽节点会出现节点疯狂抖动的现象，猜测是自动布局与节点位置拖拽计算冲突导致的问题，有没有解决方案。

**Comment by better-pz** [comment]
没有

**Comment by seeksdream** [comment]
这是因为在自动布局时会自动更改被拖拽节点的位置，但是被拖拽节点又会自动到鼠标所在的位置，所以就都抖动了。
但这可能不是啥大问题，好像也没必要为这个在布局的时候判断是否正在拖拽节点，拖拽的是哪一个。
如果一定要解决这个问题，方法是：在force布局时判断当前是否正在拖拽节点，拖拽的是哪一个，在force布局时不要更改正在被拖动的节点的位置。
