### ISSUE TITLE
超过3级树节点后，右边的布局会出现问题，救助

### ISSUE THREAD

**Issue by zhuzi001** [seeksdream/relation-graph#87]
![image](https://user-images.githubusercontent.com/15885818/177103002-890a48f9-14c5-4780-879c-00d1f9861d18.png)

没有超过的时候连接都没有问题，一旦超过一个就会这样

**Comment by seeksdream** [comment]
你可以通过设置层级距离来让不同层级的间隔距离变大一些
示例：https://seeksdream.github.io/#/demo/tree-distance
<img width="741" alt="image" src="https://user-images.githubusercontent.com/40479975/210125712-a8c8b4fe-6164-431c-9d96-8031c06acee9.png">
