### ISSUE TITLE
网站无法访问

### ISSUE THREAD

**Issue by zhouzhouyaya** [seeksdream/relation-graph#88]
http://relation-graph.com/#/demo/simple    官网访问不了了，

**Comment by AtroxEzerel** [comment]
确实 加QQ也没人

**Comment by better-pz** [comment]
作者跑路了

**Comment by TAXIVAE** [comment]
https://gitee.com/ghostgeek/vue-relation

**Comment by seeksdream** [comment]
http://relation-graph.com/ （国内用户，无需科学上网）

https://seeksdream.github.io/（For regions outside of China）
