### ISSUE TITLE
文档官网挂了，项目急着用咋办，有没有离线的文档

### ISSUE THREAD

**Issue by TAXIVAE** [seeksdream/relation-graph#89]

**Comment by erduoJiang** [comment]
同问，有没有离线文档

**Comment by TAXIVAE** [comment]
> 

https://gitee.com/ghostgeek/vue-relation
这个是vue3版本的，有部分文档

**Comment by zhuzi001** [comment]
![graph1](https://user-images.githubusercontent.com/15885818/179189868-131f7dd8-ed40-4d78-aee3-7807d4ba7e37.jpg)
![graph2](https://user-images.githubusercontent.com/15885818/179189890-d1c0cc33-5e93-4e53-ae5b-1129ae9cd96b.jpg)
![graph3](https://user-images.githubusercontent.com/15885818/179189898-1d772f11-eee4-4d58-bcfd-7267a8a85554.jpg)
![layout1](https://user-images.githubusercontent.com/15885818/179189909-ab031a96-0cf6-4d68-b7d7-87ea7c1e8a0a.jpg)
![layout2](https://user-images.githubusercontent.com/15885818/179189919-16cc0f75-b7cf-4420-920a-2611834d2d7c.jpg)
![link](https://user-images.githubusercontent.com/15885818/179189932-e52fa00b-1ab2-462d-a1d2-f2b42cb382ea.jpg)
![node1](https://user-images.githubusercontent.com/15885818/179189946-c86f1517-5710-4940-8671-58d4ed41f594.jpg)
![node2](https://user-images.githubusercontent.com/15885818/179189952-4a9d4194-6211-4615-92bc-e9b8149c610e.jpg)

**Comment by zhuzi001** [comment]
我是当时正在做这个东西，然后浏览器有缓存，回家电脑加载不出来，，然后再公司截图了，，只能这么多了。咳咳

**Comment by dingh123** [comment]
> 
兄弟，干的漂亮，感谢

**Comment by seeksdream** [comment]
http://relation-graph.com/ （国内用户，无需科学上网）

https://seeksdream.github.io/（For regions outside of China）
