### ISSUE TITLE
存在无关联节点时 节点重叠的变通修复方法

### ISSUE THREAD

**Issue by icksky** [seeksdream/relation-graph#9]
如题, 例如有1-10个节点, 1->2, 2->3, 1->4->5->6, 7,8,9 无关联. 此时会有节点重叠.
变通修复的方法就是添加一个节点0, 然后0->1, 0->7, 0->8, 0->9, 所有没有父节点的节点都以0为父节点. 然后隐藏0节点以及延申出来的连接线即可.
PS: 这个 issue 欠了好久了, 年底太忙了.

**Comment by Darling0604** [comment]
按照此方法实现后，隐藏0节点，所有的点又聚集在一起了

**Comment by icksky** [comment]
> 按照此方法实现后，隐藏0节点，所有的点又聚集在一起了

线的设置 `isHide: true`, 根节点不能隐藏

```javascript
{ id: '0', text: 'root', opacity: 0, disableDrag: true, disableDefaultClickEffect: true, styleClass: 'node-root' }
```
重点在于`opacity: 0`

**Comment by icksky** [comment]
用这个渲染太多节点会很卡 因为很多DOM, 后面放弃了 还是用canvas 的渲染方案了

**Comment by icksky** [comment]
@WindChimeBell 你这个可能得咨询一下作者~我也帮不上忙

**Comment by WindChimeBell** [comment]
> @WindChimeBell 你这个可能得咨询一下作者~我也帮不上忙

这个问题我一个个定位解决了，花了一周

**Comment by icksky** [comment]
@WindChimeBell 有时间可以分享一下, 给后来人引路
