### ISSUE TITLE
官网进不去了，谁有能用的文档地址呢

### ISSUE THREAD

**Issue by erduoJiang** [seeksdream/relation-graph#90]

**Comment by AtroxEzerel** [comment]
现在可以了

**Comment by wangaojiao1996** [comment]
感谢


| |
王轶峰
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Zuoda ***@***.***> |
| 发送日期 | 2022年8月11日 14:36 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [seeksdream/relation-graph] 官网进不去了，谁有能用的文档地址呢 (Issue #90) |

现在可以了

**Comment by wangaojiao1996** [comment]
感谢

**Comment by seeksdream** [comment]
之前的服务器到期了，没及时续费，现在好了。

http://relation-graph.com/ （国内用户，无需科学上网）

https://seeksdream.github.io/（For regions outside of China）
