### ISSUE TITLE
可以自定义线条的模式吗？比如字写在线条上面，字是线条的一部分类似于这种【 A——朋友——> B】

### ISSUE THREAD

**Issue by pandoraping** [seeksdream/relation-graph#93]

**Comment by seeksdream** [comment]
目前还没法通过配置来支持这样的效果。

v2版本中有连线插槽，可以通过插槽自定义连线（使用svg），但这个功能还没有文档开放出来，也没有示例，你可以看看源代码试着用一下
等连线插槽文档更新了再回复你

**Comment by seeksdream** [comment]
从v2.0.7开始， 新增连线插槽功能，以及相应的示例
连线插槽可以让你完全自定义连线的样式。
https://seeksdream.github.io/#/demo/adv-line-slot
