### ISSUE TITLE
vue3可以使用嘛

### ISSUE THREAD

**Issue by xie392** [seeksdream/relation-graph#94]
我用vue3写，但是去报这样的错误
![image](https://user-images.githubusercontent.com/61953437/190850891-e2173f65-f3db-4b4c-95df-2374fc757696.png)

**Comment by Tuzki-Link** [comment]
有一个Vue3的版本
https://gitee.com/ghostgeek/vue-relation

**Comment by xie392** [comment]
好的，谢谢，这个确实可以使用

**Comment by seeksdream** [comment]
v3马上发布，就在下周内。会包含最新版本所有功能。
后续v2和v3会功能会同步更新。
等支持vue3的发布好了我再回复你

**Comment by wangzy813** [comment]
期待vue3+ts版本早日发布

**Comment by kitymore** [comment]
期待vue3+ts版本早日发布

**Comment by xakoy** [comment]
> v3马上发布，就在下周内。会包含最新版本所有功能。 后续v2和v3会功能会同步更新。 等支持vue3的发布好了我再回复你

期待

**Comment by Peter-Lpt** [comment]
期待 vue3 版本 https://gitee.com/ghostgeek/vue-relation 的版本有一点老了，期待期待

**Comment by foolishcc1986** [comment]
> v3马上发布，就在下周内。会包含最新版本所有功能。 后续v2和v3会功能会同步更新。 等支持vue3的发布好了我再回复你

大佬，v3啥时候发布？

**Comment by Redwinam** [comment]
期待…………………………

**Comment by seeksdream** [comment]
已发布，2023-02-19 最新版本v2.0.12起开始支持vue3

vue2使用方法： import RelationGraph from 'relation-graph'

vue3使用方法： import RelationGraph from 'relation-graph/vue3'

vue3完整小示例：https://github.com/seeksdream/relation-graph-vue3-demo
