### ISSUE TITLE
文档描述错误 Document description error

### ISSUE THREAD

**Issue by zhaolei-hu** [seeksdream/relation-graph#96]
在links中修改连线的颜色应该使用`color`属性，而不是`lineColor`，但是文档中写的是`lineColor`，如果作者还维护的话麻烦修改一下，免得误导他人。

The `color` attribute, rather than `lineColor`, should be used to modify the color of the connection in `links` array. However, the `lineColor` is written in the document. If the author still maintains it, please modify it to avoid misleading others.

**Comment by seeksdream** [comment]
感谢反馈，现在已修改
