### ISSUE TITLE
能否动态修改单个节点的属性？

### ISSUE THREAD

**Issue by GCF15** [seeksdream/relation-graph#97]
我想定时更新单个节点的数据，能否在不进行setJsonData的情况下动态显示？

**Comment by seeksdream** [comment]
目前有一些方法，你可以参考：https://seeksdream.github.io/#/demo/adv-effect
你可以通过getNodeById(nodeId)或者getNodes()获取节点，然后直接对属性进行修改。（这些方法的使用方式参考：https://seeksdream.github.io/#/docs/graph）
理论上讲你可以修改节点的所有选项，修改后都可以马上在图谱中看到效果
记得自定义属性放到data中，节点选项参考：https://seeksdream.github.io/#/docs/node
