### ISSUE TITLE
当节点直接没有关系的时候能否让节点不要缩到一起呢

### ISSUE THREAD

**Issue by ShineHarry** [seeksdream/relation-graph#99]
如neo4j的broswer 上面的效果一样 点左侧的标签 默认不展示关系 只查询所有的节点 这时候所有节点之间是没有线的
目前用的时候如果节点直接没有线默认会以 0,0为坐标 导致所有的节点都放到了一起效果不是特别好

**Comment by seeksdream** [comment]
在v2.x版本中已支持，会在根节点周围随机分配位置，且会对这些孤点使用force布局自动调整位置。
效果请参考这个示例：https://seeksdream.github.io/#/demo/line

**Comment by LiangYongH** [comment]
@seeksdream 还是叠在一起呢
